import { ProcessPath } from '../components/Teaching'
import { unitTitle, slide, visualSlide, formulaSlide, examClose } from './helpers'
import {
  AnalogWave,
  DigitalWave,
  SignalImpairment,
  LineCodingViz,
  PcmPipeline,
  ModulationViz,
  NyquistShannonViz,
  NetworkJourney,
} from './CnKit'

const closeSlides = examClose({
  id: 'cn2-concept-map',
  unitNumber: 2,
  title: 'Unit 2 Concept Map',
  mapSteps: [
    'Signals',
    'Impairments',
    'Rate limits',
    'Performance',
    'Line coding',
    'PCM',
    'Transmission modes',
    'Modulation',
  ],
  notes: [
    'Define analog and digital signals with waveforms.',
    'Separate attenuation, distortion, and noise clearly.',
    'Practice Nyquist and Shannon numericals.',
    'Draw line coding, PCM, and modulation diagrams.',
  ],
  pyq: [
    'Explain transmission impairments with neat diagrams.',
    'Derive and apply Nyquist and Shannon capacity formulas.',
    'Compare polar, bipolar, and Manchester encoding.',
    'Explain PCM and digital-to-analog conversion techniques.',
  ],
  important: [
    'Analog versus digital signal characteristics.',
    'Nyquist and Shannon data rate limits.',
    'Bandwidth, throughput, latency, and bandwidth-delay product.',
    'PCM sampling, quantization, and encoding.',
    'ASK, FSK, PSK, and QAM modulation.',
  ],
  revision: [
    'Signal type',
    'Channel damage',
    'Maximum rate',
    'Encoding',
    'Conversion',
    'Transmission',
  ],
}).map((s) => ({ ...s, id: s.id.replace('cn-u2', 'cn2') }))

export const cnUnit2Slides = [
  {
    ...unitTitle(
      2,
      'Physical Layer-I',
      'Signals, impairments, limits, encoding, PCM, transmission modes, and modulation.',
      <NetworkJourney stage="signal" />,
    ),
    id: 'cn2-title',
  },
  visualSlide({
    id: 'cn2-roadmap',
    kicker: 'Unit Roadmap',
    title: 'From Data to Signals',
    lead: 'The physical layer decides how bits become energy on a medium.',
    contentDensity: 'sparse',
    visual: (
      <ProcessPath
        steps={[
          'Message bits',
          'Signal choice',
          'Channel limits',
          'Encoding',
          'Conversion',
          'Transmission',
        ]}
      />
    ),
    takeaway: 'Unit 2 explains the signal side of communication.',
  }),
  slide({
    id: 'cn2-physical-layer-role',
    kicker: 'Physical Layer',
    title: 'What the Physical Layer Does',
    subtitle: 'It moves raw bits across a physical medium.',
    visual: <NetworkJourney stage="medium" />,
    points: [
      'Defines electrical, optical, or radio signals.',
      'Specifies bit timing and data rate.',
      'Connects devices through media and interfaces.',
      'Hides signal details from upper layers.',
    ],
    takeaway: 'The physical layer is about representation and movement of bits.',
  }),
  visualSlide({
    id: 'cn2-signal-big-picture',
    kicker: 'Signals',
    title: 'Bits Need a Physical Shape',
    lead: 'Data is abstract; a signal is the measurable form that travels.',
    visual: <ProcessPath steps={['Data', 'Encoder', 'Signal', 'Medium', 'Receiver']} />,
    takeaway: 'Every later topic asks: what shape is sent, and what happens to it?',
  }),
  slide({
    id: 'cn2-analog-signal',
    kicker: 'Analog Signals',
    title: 'Continuous Waveforms',
    subtitle: 'An analog signal varies smoothly over time.',
    visual: <AnalogWave label="Analog signal" />,
    ratio: 'visual-copy',
    points: [
      'Amplitude can take infinitely many values.',
      'Time is continuous, not divided into bit slots.',
      'Common in voice, radio, and sensor signals.',
      'Can carry analog or digital information.',
    ],
    takeaway: 'Analog means continuous, not necessarily old or low quality.',
  }),
  slide({
    id: 'cn2-analog-characteristics',
    kicker: 'Analog Signals',
    title: 'Amplitude, Frequency, and Phase',
    subtitle: 'A sine wave is described by three main properties.',
    visual: <ProcessPath steps={['Amplitude', 'Frequency', 'Phase', 'Composite signal']} />,
    points: [
      'Amplitude measures signal strength.',
      'Frequency measures cycles per second.',
      'Phase gives position within a cycle.',
      'Composite signals combine many sine waves.',
    ],
    takeaway: 'Modulation works by changing these properties.',
  }),
  slide({
    id: 'cn2-digital-signal',
    kicker: 'Digital Signals',
    title: 'Discrete Signal Levels',
    subtitle: 'A digital signal uses distinct levels to represent bits.',
    visual: <DigitalWave bits="1011001" label="Digital signal" />,
    ratio: 'visual-copy',
    points: [
      'Values are chosen from a finite set.',
      'Bit intervals give timing boundaries.',
      'Receivers decide each bit from the level.',
      'Digital signals still travel as physical energy.',
    ],
    takeaway: 'Digital does not remove analog physics; it simplifies decisions.',
  }),
  slide({
    id: 'cn2-bit-rate-bit-interval',
    kicker: 'Digital Signals',
    title: 'Bit Rate and Bit Interval',
    subtitle: 'The bit interval is the time assigned to one bit.',
    visual: <DigitalWave bits="1011001" label="Bit slots" />,
    points: [
      'Bit rate is bits transmitted per second.',
      'Bit interval is the inverse of bit rate.',
      'Shorter intervals require faster changes.',
      'Fast changes need more bandwidth.',
    ],
    takeaway: 'High bit rate demands a channel that can follow rapid transitions.',
  }),
  slide({
    id: 'cn2-baseband-broadband',
    kicker: 'Digital Signals',
    title: 'Baseband and Broadband',
    subtitle: 'Digital data may be sent directly or shifted onto a carrier.',
    visual: <ProcessPath steps={['Bits', 'Baseband line code', 'or Carrier modulation', 'Medium']} />,
    points: [
      'Baseband sends digital pulses directly.',
      'Broadband uses modulation on an analog carrier.',
      'Medium and distance influence the choice.',
      'Both still represent the same bit stream.',
    ],
    takeaway: 'Line coding and modulation are two different physical strategies.',
  }),
  slide({
    id: 'cn2-transmission-impairment',
    kicker: 'Transmission Impairment',
    title: 'Channels Damage Signals',
    subtitle: 'A received signal is rarely identical to the transmitted signal.',
    visual: <ProcessPath steps={['Transmit', 'Attenuation', 'Distortion', 'Noise', 'Receive']} />,
    points: [
      'Energy weakens with distance.',
      'Different frequencies may arrive differently.',
      'Unwanted energy mixes with the signal.',
      'Receivers must still decide the data correctly.',
    ],
    takeaway: 'Impairments explain why capacity is limited.',
  }),
  slide({
    id: 'cn2-attenuation',
    kicker: 'Transmission Impairment',
    title: 'Attenuation',
    subtitle: 'Attenuation is loss of signal strength.',
    visual: <SignalImpairment kind="attenuation" />,
    points: [
      'Signal amplitude decreases over distance.',
      'Weak signals become harder to detect.',
      'Amplifiers or repeaters may be required.',
      'Loss is often measured in decibels.',
    ],
    takeaway: 'Attenuation reduces power, not the intended shape.',
  }),
  slide({
    id: 'cn2-distortion',
    kicker: 'Transmission Impairment',
    title: 'Distortion',
    subtitle: 'Distortion changes the signal shape.',
    visual: <SignalImpairment kind="distortion" />,
    points: [
      'Composite signal components travel differently.',
      'Some frequencies may be delayed more.',
      'The receiver sees a changed waveform.',
      'High-speed links are more sensitive.',
    ],
    takeaway: 'Distortion damages timing and shape.',
  }),
  slide({
    id: 'cn2-noise',
    kicker: 'Transmission Impairment',
    title: 'Noise',
    subtitle: 'Noise is unwanted energy added to the signal.',
    visual: <SignalImpairment kind="noise" />,
    points: [
      'Thermal noise comes from random electron motion.',
      'Induced noise comes from other devices.',
      'Crosstalk leaks from nearby channels.',
      'Impulse noise appears as sudden spikes.',
    ],
    takeaway: 'Noise can flip receiver decisions even when the sender is correct.',
  }),
  slide({
    id: 'cn2-snr',
    kicker: 'Transmission Impairment',
    title: 'Signal-to-Noise Ratio',
    subtitle: 'SNR compares useful signal power with noise power.',
    visual: <ProcessPath steps={['Signal power', 'Noise power', 'SNR', 'Capacity impact']} />,
    points: [
      'Higher SNR means cleaner reception.',
      'Lower SNR means more uncertainty.',
      'SNR is often expressed in decibels.',
      'Shannon capacity depends directly on SNR.',
    ],
    takeaway: 'Good bandwidth is not enough if the channel is noisy.',
  }),
  visualSlide({
    id: 'cn2-rate-limits-intro',
    kicker: 'Data Rate Limits',
    title: 'How Fast Can We Send?',
    lead: 'Forouzan separates the noiseless ideal from the noisy real channel.',
    visual: <NyquistShannonViz />,
    takeaway: 'Nyquist uses signal levels; Shannon uses noise.',
  }),
  formulaSlide({
    id: 'cn2-nyquist-formula',
    kicker: 'Data Rate Limits',
    title: 'Nyquist Bit Rate',
    formula: 'C = 2B log2 M',
    symbols: [
      'C is maximum bit rate in bps.',
      'B is channel bandwidth in hertz.',
      'M is number of signal levels.',
      'Assumes a noiseless channel.',
    ],
    visual: <NyquistShannonViz />,
    takeaway: 'More levels increase bit rate only if the receiver can distinguish them.',
  }),
  formulaSlide({
    id: 'cn2-nyquist-worked-example',
    kicker: 'Worked Example',
    title: 'Nyquist Example',
    formula: 'C = 2B log2 M',
    symbols: [
      'B = 3000 Hz.',
      'M = 8 signal levels.',
      'log2 8 = 3 bits per signal.',
      'C = 2 x 3000 x 3.',
    ],
    example: 'C = 18,000 bps. A noiseless 3000 Hz channel with 8 levels can carry 18 kbps.',
    visual: <ProcessPath steps={['B = 3000', 'M = 8', 'log2 M = 3', 'C = 18000 bps']} />,
    takeaway: 'Nyquist rewards both bandwidth and distinguishable signal levels.',
  }),
  formulaSlide({
    id: 'cn2-shannon-formula',
    kicker: 'Data Rate Limits',
    title: 'Shannon Capacity',
    formula: 'C = B log2(1 + SNR)',
    symbols: [
      'C is capacity in bps.',
      'B is channel bandwidth in hertz.',
      'SNR is signal-to-noise power ratio.',
      'Applies to a noisy channel.',
    ],
    visual: <NyquistShannonViz />,
    takeaway: 'Shannon gives the theoretical ceiling for noisy channels.',
  }),
  formulaSlide({
    id: 'cn2-shannon-worked-example',
    kicker: 'Worked Example',
    title: 'Shannon Example',
    formula: 'C = B log2(1 + SNR)',
    symbols: [
      'B = 3000 Hz.',
      'SNR = 3162.',
      'C = 3000 log2(3163).',
      'log2(3163) is about 11.63.',
    ],
    example: 'C is about 34,890 bps. A noisy 3000 Hz channel at SNR 3162 is limited to about 34.9 kbps.',
    visual: <ProcessPath steps={['B = 3000', 'SNR = 3162', 'log2(3163)', 'C about 34.9 kbps']} />,
    takeaway: 'Even with clever coding, noise fixes a hard upper limit.',
  }),
  slide({
    id: 'cn2-nyquist-vs-shannon',
    kicker: 'Data Rate Limits',
    title: 'Nyquist vs Shannon',
    subtitle: 'Use the correct formula for the channel assumption.',
    visual: <NyquistShannonViz />,
    points: [
      'Nyquist assumes no noise.',
      'Shannon includes noise through SNR.',
      'Nyquist includes signal levels.',
      'Shannon gives a capacity ceiling.',
    ],
    takeaway: 'In exams, identify the assumption before substituting values.',
  }),
  slide({
    id: 'cn2-performance-bandwidth',
    kicker: 'Performance',
    title: 'Bandwidth',
    subtitle: 'Bandwidth can mean frequency range or bit rate depending on context.',
    visual: <ProcessPath steps={['Analog bandwidth', 'Hz', 'Digital bandwidth', 'bps']} />,
    points: [
      'Analog bandwidth is measured in hertz.',
      'Digital bandwidth often means data rate.',
      'More bandwidth can allow higher capacity.',
      'Context decides the unit.',
    ],
    takeaway: 'Always state whether bandwidth is in Hz or bps.',
  }),
  slide({
    id: 'cn2-performance-throughput',
    kicker: 'Performance',
    title: 'Throughput',
    subtitle: 'Throughput is the actual rate achieved by data transfer.',
    visual: <ProcessPath steps={['Offered rate', 'Protocol overhead', 'Errors', 'Actual throughput']} />,
    points: [
      'It is usually lower than bandwidth.',
      'Errors and retransmissions reduce it.',
      'Protocol headers consume capacity.',
      'Congestion also reduces throughput.',
    ],
    takeaway: 'Bandwidth is potential; throughput is observed delivery.',
  }),
  slide({
    id: 'cn2-performance-latency',
    kicker: 'Performance',
    title: 'Latency',
    subtitle: 'Latency is the time needed for data to reach the destination.',
    visual: <ProcessPath steps={['Propagation', 'Transmission', 'Queuing', 'Processing']} />,
    points: [
      'Propagation delay depends on distance.',
      'Transmission delay depends on packet size and rate.',
      'Queuing delay depends on traffic load.',
      'Processing delay occurs inside devices.',
    ],
    takeaway: 'A fast link can still feel slow if latency is high.',
  }),
  formulaSlide({
    id: 'cn2-bandwidth-delay-product',
    kicker: 'Performance',
    title: 'Bandwidth-Delay Product',
    formula: 'BDP = bandwidth x delay',
    symbols: [
      'Bandwidth is in bits per second.',
      'Delay is in seconds.',
      'BDP is bits in the pipe.',
      'Large BDP links need enough in-flight data.',
    ],
    visual: <ProcessPath steps={['Sender', 'Long pipe', 'Bits in flight', 'Receiver']} />,
    takeaway: 'BDP tells how much data can occupy the link at once.',
  }),
  visualSlide({
    id: 'cn2-digital-to-digital-intro',
    kicker: 'Digital-to-Digital',
    title: 'Line Coding',
    lead: 'Line coding converts digital data into digital signals.',
    visual: <LineCodingViz scheme="manchester" bits="1011001" />,
    contentDensity: 'sparse',
    takeaway: 'The receiver needs both bit values and timing clues.',
  }),
  slide({
    id: 'cn2-polar-line-coding',
    kicker: 'Line Coding',
    title: 'Polar Encoding',
    subtitle: 'Polar schemes use positive and negative voltage levels.',
    visual: <LineCodingViz scheme="polar" bits="1011001" />,
    ratio: 'visual-copy',
    points: [
      'Two polarities represent binary values.',
      'NRZ-L maps level directly to bit value.',
      'Long constant runs can hurt synchronization.',
      'Simple hardware makes it easy to explain.',
    ],
    takeaway: 'Polar coding is simple but timing can be weak.',
  }),
  slide({
    id: 'cn2-bipolar-line-coding',
    kicker: 'Line Coding',
    title: 'Bipolar Encoding',
    subtitle: 'Bipolar AMI uses zero plus alternating polarities.',
    visual: <LineCodingViz scheme="bipolar" bits="1011001" />,
    ratio: 'visual-copy',
    points: [
      'Binary 0 is represented by zero voltage.',
      'Binary 1 alternates positive and negative.',
      'No DC component for balanced data.',
      'Long runs of zeros still cause timing issues.',
    ],
    takeaway: 'Bipolar encoding helps balance, but not every synchronization problem.',
  }),
  slide({
    id: 'cn2-manchester-line-coding',
    kicker: 'Line Coding',
    title: 'Manchester Encoding',
    subtitle: 'Manchester places a transition inside every bit interval.',
    visual: <LineCodingViz scheme="manchester" bits="1011001" />,
    ratio: 'visual-copy',
    points: [
      'Mid-bit transition carries clock information.',
      'Each bit has guaranteed signal change.',
      'Requires more bandwidth than simple NRZ.',
      'Used where synchronization matters.',
    ],
    takeaway: 'Manchester trades bandwidth for reliable timing.',
  }),
  slide({
    id: 'cn2-line-coding-comparison',
    kicker: 'Line Coding',
    title: 'Choosing a Line Code',
    subtitle: 'Line codes balance simplicity, bandwidth, and synchronization.',
    visual: <ProcessPath steps={['DC component', 'Bandwidth', 'Synchronization', 'Error visibility']} />,
    points: [
      'Polar is simple and direct.',
      'Bipolar reduces DC component.',
      'Manchester gives strong clock recovery.',
      'No scheme is best for every medium.',
    ],
    takeaway: 'State the trade-off, not only the waveform.',
  }),
  visualSlide({
    id: 'cn2-analog-to-digital-intro',
    kicker: 'Analog-to-Digital',
    title: 'Pulse Code Modulation',
    lead: 'PCM converts an analog signal into a digital bit stream.',
    visual: <PcmPipeline />,
    contentDensity: 'sparse',
    takeaway: 'PCM is the core analog-to-digital method for this unit.',
  }),
  slide({
    id: 'cn2-pcm-sampling',
    kicker: 'PCM',
    title: 'Sampling',
    subtitle: 'Sampling measures the analog signal at regular time intervals.',
    visual: <PcmPipeline />,
    ratio: 'visual-copy',
    points: [
      'Each sample records signal amplitude.',
      'Sampling rate must be high enough.',
      'Too few samples cause aliasing.',
      'The result is discrete in time.',
    ],
    takeaway: 'Sampling captures when the signal is measured.',
  }),
  slide({
    id: 'cn2-pcm-quantization',
    kicker: 'PCM',
    title: 'Quantization',
    subtitle: 'Quantization maps sample amplitudes to allowed levels.',
    visual: <PcmPipeline />,
    ratio: 'visual-copy',
    points: [
      'Continuous amplitudes become level numbers.',
      'More levels reduce quantization error.',
      'Quantization introduces small approximation noise.',
      'Level count determines bits per sample.',
    ],
    takeaway: 'Quantization captures how precisely amplitude is stored.',
  }),
  slide({
    id: 'cn2-pcm-encoding',
    kicker: 'PCM',
    title: 'Encoding',
    subtitle: 'Encoding converts quantized levels into binary codewords.',
    visual: <PcmPipeline />,
    ratio: 'visual-copy',
    points: [
      'Each level receives a binary pattern.',
      'n bits can represent 2^n levels.',
      'The output is a digital bit stream.',
      'Transmission can now use digital links.',
    ],
    takeaway: 'PCM ends with bits, not samples on paper.',
  }),
  slide({
    id: 'cn2-pcm-rate',
    kicker: 'PCM',
    title: 'PCM Bit Rate',
    subtitle: 'PCM rate depends on samples per second and bits per sample.',
    visual: <ProcessPath steps={['Sampling rate', 'Bits/sample', 'Multiply', 'PCM bit rate']} />,
    points: [
      'Higher sampling rate increases bit rate.',
      'More quantization levels need more bits.',
      'Voice PCM commonly illustrates this idea.',
      'Compression is separate from basic PCM.',
    ],
    takeaway: 'PCM quality and required bandwidth rise together.',
  }),
  visualSlide({
    id: 'cn2-transmission-modes-intro',
    kicker: 'Transmission Modes',
    title: 'How Bits Are Sent',
    lead: 'Transmission modes describe grouping and timing of bit movement.',
    visual: <ProcessPath steps={['Parallel', 'Serial', 'Asynchronous', 'Synchronous', 'Isochronous']} />,
    takeaway: 'Mode affects wires, timing, cost, and delay.',
  }),
  slide({
    id: 'cn2-parallel-serial',
    kicker: 'Transmission Modes',
    title: 'Parallel and Serial Transmission',
    subtitle: 'Parallel sends many bits at once; serial sends one bit after another.',
    visual: <ProcessPath steps={['Parallel: many wires', 'Short distance', 'Serial: one stream', 'Long distance']} />,
    points: [
      'Parallel can be fast over short distances.',
      'Skew makes long parallel links difficult.',
      'Serial is cheaper for long links.',
      'Most network communication is serial.',
    ],
    takeaway: 'Parallel saves time locally; serial scales better across distance.',
  }),
  slide({
    id: 'cn2-async-sync-iso',
    kicker: 'Transmission Modes',
    title: 'Asynchronous, Synchronous, Isochronous',
    subtitle: 'Serial transmission also differs by timing discipline.',
    visual: <ProcessPath steps={['Start/stop bits', 'Shared clock blocks', 'Time-bound stream']} />,
    points: [
      'Asynchronous sends character-sized units.',
      'Synchronous sends blocks with shared timing.',
      'Isochronous reserves timing for continuous media.',
      'Each mode solves a different timing need.',
    ],
    takeaway: 'Timing is as important as voltage for correct bit recovery.',
  }),
  visualSlide({
    id: 'cn2-digital-to-analog-intro',
    kicker: 'Digital-to-Analog',
    title: 'Modulating a Carrier',
    lead: 'Digital data can ride on an analog carrier by changing carrier properties.',
    visual: <ModulationViz mode="ASK" />,
    contentDensity: 'sparse',
    takeaway: 'ASK, FSK, PSK, and QAM are carrier modulation methods.',
  }),
  slide({
    id: 'cn2-ask',
    kicker: 'Digital-to-Analog',
    title: 'Amplitude Shift Keying',
    subtitle: 'ASK changes carrier amplitude to represent bits.',
    visual: <ModulationViz mode="ASK" />,
    ratio: 'visual-copy',
    points: [
      'One amplitude may represent 1.',
      'Another amplitude may represent 0.',
      'Simple, but sensitive to noise.',
      'Useful for basic modulation examples.',
    ],
    takeaway: 'ASK changes strength.',
  }),
  slide({
    id: 'cn2-fsk',
    kicker: 'Digital-to-Analog',
    title: 'Frequency Shift Keying',
    subtitle: 'FSK changes carrier frequency to represent bits.',
    visual: <ModulationViz mode="FSK" />,
    ratio: 'visual-copy',
    points: [
      'Different frequencies represent different bits.',
      'More robust to amplitude noise than ASK.',
      'Requires enough frequency separation.',
      'Common in simple modems and radio links.',
    ],
    takeaway: 'FSK changes frequency.',
  }),
  slide({
    id: 'cn2-psk',
    kicker: 'Digital-to-Analog',
    title: 'Phase Shift Keying',
    subtitle: 'PSK changes carrier phase to represent data.',
    visual: <ModulationViz mode="PSK" />,
    ratio: 'visual-copy',
    points: [
      'Phase shifts mark symbol changes.',
      'Can encode more than one bit per symbol.',
      'Needs accurate phase detection.',
      'Forms the base for many modern schemes.',
    ],
    takeaway: 'PSK changes position within the wave cycle.',
  }),
  slide({
    id: 'cn2-qam',
    kicker: 'Digital-to-Analog',
    title: 'Quadrature Amplitude Modulation',
    subtitle: 'QAM combines amplitude and phase changes.',
    visual: <ModulationViz mode="QAM" />,
    ratio: 'visual-copy',
    points: [
      'Symbols are points in a constellation.',
      'Each symbol can carry multiple bits.',
      'Higher QAM needs better SNR.',
      'Used in many broadband systems.',
    ],
    takeaway: 'QAM gains rate by packing more bits into each symbol.',
  }),
  slide({
    id: 'cn2-modulation-summary',
    kicker: 'Digital-to-Analog',
    title: 'Modulation Comparison',
    subtitle: 'Each method changes a different carrier property.',
    visual: <ProcessPath steps={['ASK: amplitude', 'FSK: frequency', 'PSK: phase', 'QAM: amplitude + phase']} />,
    points: [
      'ASK is simplest and noise-sensitive.',
      'FSK separates bits by frequency.',
      'PSK improves symbol efficiency.',
      'QAM needs clean channels for high rates.',
    ],
    takeaway: 'Match modulation complexity to channel quality.',
  }),
  ...closeSlides,
]
