import { ProcessPath } from '../components/Teaching'
import { unitTitle, slide, visualSlide, formulaSlide, examClose } from './helpers'
import {
  NetworkJourney,
  MultiplexerViz,
  SpreadSpectrumViz,
  CircuitSwitchScene,
  DatagramRouting,
  VirtualCircuitScene,
} from './CnKit'

const closeSlides = examClose({
  id: 'cn3-concept-map',
  unitNumber: 3,
  title: 'Unit 3 Concept Map',
  mapSteps: [
    'Multiplexing',
    'FDM',
    'WDM',
    'TDM',
    'Spread spectrum',
    'Switching',
    'Circuit switching',
    'Packet switching',
  ],
  notes: [
    'Draw MUX/DEMUX for FDM, WDM, and TDM.',
    'Separate FHSS and DSSS by how spreading happens.',
    'Explain setup, transfer, and teardown in circuit switching.',
    'Compare datagram and virtual-circuit packet switching.',
  ],
  pyq: [
    'Explain FDM, WDM, and TDM with diagrams.',
    'Compare FHSS and DSSS spread spectrum techniques.',
    'Describe circuit switching phases with an example.',
    'Differentiate datagram and virtual-circuit networks.',
  ],
  important: [
    'Frequency, wavelength, and time division multiplexing.',
    'FHSS and DSSS operating ideas.',
    'Circuit-switched network phases and delays.',
    'Datagram routing independence.',
    'Virtual-circuit setup and label forwarding.',
    'Comparison of switching methods.',
  ],
  revision: [
    'Share a link',
    'Spread a signal',
    'Choose a switch',
    'Reserve or route',
    'Compare behavior',
  ],
}).map((s) => ({ ...s, id: s.id.replace('cn-u3', 'cn3') }))

export const cnUnit3Slides = [
  {
    ...unitTitle(
      3,
      'Physical Layer-II & Switching',
      'Multiplexing, spread spectrum, and switched-network communication.',
      <NetworkJourney stage="medium" />,
    ),
    id: 'cn3-title',
  },
  visualSlide({
    id: 'cn3-roadmap',
    kicker: 'Unit Roadmap',
    title: 'Sharing Links and Choosing Paths',
    lead: 'Unit 3 starts with many signals on one medium and ends with networks selecting paths.',
    visual: (
      <ProcessPath
        steps={[
          'Multiplex',
          'Spread',
          'Switch',
          'Reserve circuit',
          'Route datagram',
          'Use virtual circuit',
        ]}
      />
    ),
    takeaway: 'The unit connects physical sharing with network switching.',
  }),
  slide({
    id: 'cn3-why-multiplex',
    kicker: 'Multiplexing',
    title: 'Why Multiplex?',
    subtitle: 'Multiplexing lets multiple transmissions share one high-capacity link.',
    visual: <MultiplexerViz mode="MUX" />,
    points: [
      'A MUX combines several input channels.',
      'A DEMUX separates them at the destination.',
      'Sharing improves link utilization.',
      'Users remain logically separate.',
    ],
    takeaway: 'Multiplexing is controlled sharing of a medium.',
  }),
  slide({
    id: 'cn3-multiplexing-basic-model',
    kicker: 'Multiplexing',
    title: 'MUX to DEMUX Model',
    subtitle: 'The sender side combines; the receiver side reconstructs.',
    visual: <MultiplexerViz mode="Shared" />,
    points: [
      'Inputs enter the multiplexer separately.',
      'The composite signal crosses one link.',
      'The demultiplexer uses the same rule in reverse.',
      'Synchronization is essential.',
    ],
    takeaway: 'A MUX system works only when both ends agree on the separation rule.',
  }),
  slide({
    id: 'cn3-fdm-overview',
    kicker: 'FDM',
    title: 'Frequency-Division Multiplexing',
    subtitle: 'FDM divides link bandwidth into frequency bands.',
    visual: <MultiplexerViz mode="FDM" />,
    points: [
      'Each channel gets a different frequency band.',
      'Channels transmit at the same time.',
      'Guard bands reduce overlap interference.',
      'Used for radio, TV, and cable systems.',
    ],
    takeaway: 'FDM shares by frequency.',
  }),
  slide({
    id: 'cn3-fdm-guard-bands',
    kicker: 'FDM',
    title: 'Guard Bands',
    subtitle: 'Guard bands are unused gaps between adjacent channels.',
    visual: <ProcessPath steps={['Channel 1', 'Guard band', 'Channel 2', 'Guard band', 'Channel 3']} />,
    points: [
      'Filters are not perfectly sharp.',
      'Adjacent channels can otherwise interfere.',
      'Guard bands reduce usable capacity.',
      'They trade efficiency for cleaner separation.',
    ],
    takeaway: 'Guard bands are the price of practical frequency separation.',
  }),
  slide({
    id: 'cn3-wdm-overview',
    kicker: 'WDM',
    title: 'Wavelength-Division Multiplexing',
    subtitle: 'WDM is FDM for optical fiber using light wavelengths.',
    visual: <MultiplexerViz mode="WDM" />,
    points: [
      'Different light wavelengths carry different channels.',
      'A prism-like device combines beams.',
      'Optical demultiplexing separates wavelengths.',
      'Common in high-capacity fiber backbones.',
    ],
    takeaway: 'WDM shares fiber by color of light.',
  }),
  slide({
    id: 'cn3-tdm-overview',
    kicker: 'TDM',
    title: 'Time-Division Multiplexing',
    subtitle: 'TDM divides link use into repeating time slots.',
    visual: <MultiplexerViz mode="TDM" />,
    points: [
      'Users take turns on the full channel.',
      'Slots repeat in frames.',
      'Synchronization keeps slot ownership clear.',
      'Works naturally with digital signals.',
    ],
    takeaway: 'TDM shares by time.',
  }),
  slide({
    id: 'cn3-synchronous-tdm',
    kicker: 'TDM',
    title: 'Synchronous TDM',
    subtitle: 'Each source receives a fixed slot whether it has data or not.',
    visual: <ProcessPath steps={['Frame', 'Slot A', 'Slot B', 'Slot C', 'Repeat']} />,
    points: [
      'Slot position identifies the source.',
      'No address is needed inside each slot.',
      'Idle sources can waste capacity.',
      'Timing must be tightly maintained.',
    ],
    takeaway: 'Synchronous TDM is predictable but can be inefficient.',
  }),
  slide({
    id: 'cn3-statistical-tdm',
    kicker: 'TDM',
    title: 'Statistical TDM',
    subtitle: 'Statistical TDM assigns slots only to active sources.',
    visual: <ProcessPath steps={['Active inputs', 'Dynamic slots', 'Address field', 'Efficient frame']} />,
    points: [
      'Slots are allocated on demand.',
      'Frames need addressing information.',
      'Link utilization improves for bursty data.',
      'Buffers handle temporary bursts.',
    ],
    takeaway: 'Statistical TDM improves efficiency by adding control information.',
  }),
  slide({
    id: 'cn3-fdm-wdm-tdm-compare',
    kicker: 'Multiplexing',
    title: 'FDM, WDM, and TDM',
    subtitle: 'The three methods separate users along different dimensions.',
    visual: <ProcessPath steps={['FDM: frequency', 'WDM: wavelength', 'TDM: time']} />,
    points: [
      'FDM is common for analog frequency bands.',
      'WDM is optical wavelength sharing.',
      'TDM is digital time-slot sharing.',
      'All need matching DEMUX logic.',
    ],
    takeaway: 'Ask: what resource is being divided?',
  }),
  visualSlide({
    id: 'cn3-spread-spectrum-intro',
    kicker: 'Spread Spectrum',
    title: 'Using More Bandwidth on Purpose',
    lead: 'Spread spectrum spreads a signal over a wider band than the minimum required.',
    visual: <SpreadSpectrumViz mode="FHSS" />,
    takeaway: 'It trades bandwidth for resistance to noise, jamming, and interception.',
  }),
  slide({
    id: 'cn3-spread-spectrum-purpose',
    kicker: 'Spread Spectrum',
    title: 'Why Spread the Signal?',
    subtitle: 'A spread signal is harder to disrupt and easier to separate by code.',
    visual: <ProcessPath steps={['Original data', 'Spreading code', 'Wideband signal', 'Despread receiver']} />,
    points: [
      'Energy is distributed over a wide band.',
      'Narrowband interference affects only part.',
      'A receiver uses the same code to recover data.',
      'Bandwidth is used for robustness.',
    ],
    takeaway: 'Spread spectrum is deliberate expansion, not waste.',
  }),
  slide({
    id: 'cn3-fhss',
    kicker: 'Spread Spectrum',
    title: 'Frequency Hopping Spread Spectrum',
    subtitle: 'FHSS rapidly changes carrier frequency using a hopping pattern.',
    visual: <SpreadSpectrumViz mode="FHSS" />,
    points: [
      'Sender and receiver follow the same hop sequence.',
      'Each hop uses a narrow frequency for a short time.',
      'Interference on one frequency affects only one hop.',
      'Synchronization is required.',
    ],
    takeaway: 'FHSS spreads by moving the carrier.',
  }),
  slide({
    id: 'cn3-dsss',
    kicker: 'Spread Spectrum',
    title: 'Direct Sequence Spread Spectrum',
    subtitle: 'DSSS multiplies data by a faster chip sequence.',
    visual: <SpreadSpectrumViz mode="DSSS" />,
    points: [
      'Each data bit becomes multiple chips.',
      'The chip sequence spreads energy widely.',
      'Receiver correlates with the same code.',
      'Processing gain improves robustness.',
    ],
    takeaway: 'DSSS spreads by coding each bit into chips.',
  }),
  slide({
    id: 'cn3-fhss-vs-dsss',
    kicker: 'Spread Spectrum',
    title: 'FHSS vs DSSS',
    subtitle: 'Both spread energy, but the mechanism differs.',
    visual: <ProcessPath steps={['FHSS: hop frequencies', 'DSSS: chip sequence', 'Both: robust link']} />,
    points: [
      'FHSS changes carrier frequency over time.',
      'DSSS stays wide using a chip code.',
      'FHSS needs hop synchronization.',
      'DSSS needs code synchronization.',
    ],
    takeaway: 'For comparison answers, name the spreading mechanism first.',
  }),
  visualSlide({
    id: 'cn3-switching-intro',
    kicker: 'Switching',
    title: 'Connecting Many Devices',
    lead: 'Switching chooses how data moves across intermediate nodes.',
    visual: <ProcessPath steps={['Source', 'Switching nodes', 'Path decision', 'Destination']} />,
    takeaway: 'A switched network avoids needing a direct link between every pair.',
  }),
  slide({
    id: 'cn3-switching-need',
    kicker: 'Switching',
    title: 'Why Switching Is Needed',
    subtitle: 'Large networks cannot dedicate one physical link to every pair of devices.',
    visual: <NetworkJourney stage="router" />,
    points: [
      'Intermediate nodes forward traffic.',
      'Paths may be reserved or chosen per packet.',
      'Resources are shared across users.',
      'Switching method affects delay and reliability.',
    ],
    takeaway: 'Switching is the network answer to scale.',
  }),
  slide({
    id: 'cn3-switching-methods',
    kicker: 'Switching',
    title: 'Three Switching Methods',
    subtitle: 'Forouzan groups switching into circuit, packet, and message switching.',
    visual: <ProcessPath steps={['Circuit switching', 'Packet switching', 'Message switching']} />,
    points: [
      'Circuit switching reserves a path.',
      'Packet switching forwards small packets.',
      'Message switching stores whole messages.',
      'Modern data networks mostly use packet switching.',
    ],
    takeaway: 'The main difference is when resources and paths are decided.',
  }),
  visualSlide({
    id: 'cn3-circuit-switching-overview',
    kicker: 'Circuit Switching',
    title: 'Dedicated Path Communication',
    lead: 'Circuit switching establishes a dedicated path before data transfer.',
    visual: <CircuitSwitchScene phase="setup" />,
    takeaway: 'Telephone networks are the classic circuit-switching example.',
  }),
  slide({
    id: 'cn3-circuit-setup',
    kicker: 'Circuit Switching',
    title: 'Setup Phase',
    subtitle: 'The network finds and reserves a path before data moves.',
    visual: <CircuitSwitchScene phase="setup" />,
    points: [
      'A connection request travels through switches.',
      'Each switch reserves required resources.',
      'Setup delay occurs before communication.',
      'Failure can happen if resources are unavailable.',
    ],
    takeaway: 'Circuit switching pays delay first to get a stable path.',
  }),
  slide({
    id: 'cn3-circuit-transfer',
    kicker: 'Circuit Switching',
    title: 'Data Transfer Phase',
    subtitle: 'After setup, data flows on the reserved circuit.',
    visual: <CircuitSwitchScene phase="transfer" />,
    points: [
      'All data follows the same path.',
      'Reserved bandwidth gives predictable service.',
      'No per-packet routing decision is needed.',
      'Idle time can waste reserved resources.',
    ],
    takeaway: 'Transfer is simple because setup already made the decision.',
  }),
  slide({
    id: 'cn3-circuit-teardown',
    kicker: 'Circuit Switching',
    title: 'Teardown Phase',
    subtitle: 'The circuit is released after communication ends.',
    visual: <CircuitSwitchScene phase="teardown" />,
    points: [
      'A release signal frees switch resources.',
      'Reserved bandwidth returns to the network.',
      'The path no longer exists after teardown.',
      'New communication needs a new setup.',
    ],
    takeaway: 'Circuit resources should not stay reserved after use.',
  }),
  slide({
    id: 'cn3-circuit-delay',
    kicker: 'Circuit Switching',
    title: 'Circuit Switching Delay',
    subtitle: 'Delay is dominated by setup first, then steady transfer.',
    visual: <ProcessPath steps={['Setup delay', 'Data transfer', 'Propagation', 'Teardown']} />,
    points: [
      'Initial setup can be significant.',
      'After setup, forwarding is predictable.',
      'Reserved resources reduce queuing variation.',
      'Efficiency is poor for bursty traffic.',
    ],
    takeaway: 'Circuit switching fits continuous traffic better than bursty data.',
  }),
  visualSlide({
    id: 'cn3-datagram-overview',
    kicker: 'Datagram Networks',
    title: 'Packet-by-Packet Routing',
    lead: 'In a datagram network, each packet is treated independently.',
    visual: <DatagramRouting />,
    takeaway: 'Packets from the same message may take different paths.',
  }),
  slide({
    id: 'cn3-datagram-forwarding',
    kicker: 'Datagram Networks',
    title: 'Forwarding Datagrams',
    subtitle: 'Each packet carries enough destination information for routing.',
    visual: <DatagramRouting />,
    points: [
      'No setup phase is required.',
      'Routers choose the next hop per packet.',
      'Packets may arrive out of order.',
      'Destination address is carried in every packet.',
    ],
    takeaway: 'Datagram service is flexible but less predictable.',
  }),
  slide({
    id: 'cn3-datagram-pros-cons',
    kicker: 'Datagram Networks',
    title: 'Datagram Strengths and Limits',
    subtitle: 'Independence makes datagrams resilient and efficient for bursty traffic.',
    visual: <ProcessPath steps={['No reservation', 'Dynamic routing', 'Possible reordering', 'Best effort']} />,
    points: [
      'No connection setup delay.',
      'Failures can be routed around.',
      'Congestion can change packet paths.',
      'Delivery guarantees need higher-layer support.',
    ],
    takeaway: 'Datagrams favor adaptability over guaranteed order.',
  }),
  visualSlide({
    id: 'cn3-virtual-circuit-overview',
    kicker: 'Virtual-Circuit Networks',
    title: 'A Logical Path for Packets',
    lead: 'Virtual-circuit networks set up a logical path, then send packets along it.',
    visual: <VirtualCircuitScene />,
    takeaway: 'It combines setup like circuits with packet forwarding.',
  }),
  slide({
    id: 'cn3-vc-setup',
    kicker: 'Virtual-Circuit Networks',
    title: 'Virtual-Circuit Setup',
    subtitle: 'Setup creates table entries before packets are sent.',
    visual: <VirtualCircuitScene />,
    points: [
      'A setup request selects a path.',
      'Switches store virtual-circuit identifiers.',
      'Resources may or may not be reserved.',
      'Packets later use short labels.',
    ],
    takeaway: 'The path is logical, not a dedicated physical wire.',
  }),
  slide({
    id: 'cn3-vc-data-transfer',
    kicker: 'Virtual-Circuit Networks',
    title: 'Virtual-Circuit Transfer',
    subtitle: 'All packets follow the same established logical route.',
    visual: <VirtualCircuitScene />,
    points: [
      'Packets carry a virtual-circuit identifier.',
      'Switches translate labels at each hop.',
      'Ordering is easier to maintain.',
      'A broken path affects the connection.',
    ],
    takeaway: 'Virtual circuits improve order and control at the cost of setup.',
  }),
  slide({
    id: 'cn3-vc-teardown',
    kicker: 'Virtual-Circuit Networks',
    title: 'Virtual-Circuit Teardown',
    subtitle: 'Teardown removes the logical path from switching tables.',
    visual: <ProcessPath steps={['End signal', 'Remove labels', 'Free entries', 'Close VC']} />,
    points: [
      'Switch table entries are cleared.',
      'Labels become available for reuse.',
      'State must be maintained while active.',
      'Failures require recovery or new setup.',
    ],
    takeaway: 'Virtual circuits are stateful packet networks.',
  }),
  slide({
    id: 'cn3-message-switching',
    kicker: 'Switching',
    title: 'Message Switching',
    subtitle: 'Message switching stores and forwards the whole message.',
    visual: <ProcessPath steps={['Whole message', 'Store at switch', 'Forward later', 'Destination']} />,
    points: [
      'No dedicated path is reserved.',
      'Each switch stores the complete message.',
      'Large storage and delay are required.',
      'It is less common than packet switching.',
    ],
    takeaway: 'Message switching explains store-and-forward, but packets scale better.',
  }),
  slide({
    id: 'cn3-switching-comparison',
    kicker: 'Switching',
    title: 'Comparing Switching Methods',
    subtitle: 'Circuit, datagram, and virtual-circuit switching make different trade-offs.',
    visual: <ProcessPath steps={['Circuit: reserved', 'Datagram: independent', 'Virtual circuit: logical path']} />,
    points: [
      'Circuit switching gives predictable service after setup.',
      'Datagrams need no setup and adapt to changes.',
      'Virtual circuits keep packet order through a setup path.',
      'Traffic pattern decides the better fit.',
    ],
    takeaway: 'Compare by setup, path, resource use, ordering, and delay.',
  }),
  formulaSlide({
    id: 'cn3-comparison-exam-frame',
    kicker: 'Exam Frame',
    title: 'Five Comparison Axes',
    formula: 'Switching choice = setup + path + state + delay + efficiency',
    symbols: [
      'Setup: required or not required.',
      'Path: dedicated, independent, or logical.',
      'State: stored in switches or carried in packets.',
      'Efficiency: continuous traffic versus bursty traffic.',
    ],
    visual: <ProcessPath steps={['Setup', 'Path', 'State', 'Delay', 'Efficiency']} />,
    takeaway: 'Use the same axes for clean comparison answers.',
  }),
  visualSlide({
    id: 'cn3-unit-wrap',
    kicker: 'Unit Wrap',
    title: 'One Story for Unit 3',
    lead: 'First share the physical medium; then decide how traffic crosses a network.',
    visual: <ProcessPath steps={['FDM/WDM/TDM', 'FHSS/DSSS', 'Circuit', 'Datagram', 'Virtual circuit']} />,
    takeaway: 'Multiplexing shares a link; switching shares a network.',
  }),
  ...closeSlides,
]
