import { ProcessPath } from '../components/Teaching'
import { unitTitle, slide, visualSlide, formulaSlide, examClose } from './helpers'
import { FramingViz, StopWaitTimeline, SlidingWindowViz, HdlcFrame, PppPhases, NetworkJourney, ErrorChannel } from './CnKit'

const closeIds = (unitNumber, slides) =>
  slides.map((item) => ({
    ...item,
    id: String(item.id).replace(`cn-u${unitNumber}-`, `cn${unitNumber}-`),
  }))

const ProtocolStack = ({ active = 'ARQ' }) => (
  <ProcessPath
    steps={[
      { label: 'Frame', desc: active === 'Frame' ? 'boundary' : 'unit' },
      { label: 'Flow', desc: active === 'Flow' ? 'pace' : 'control' },
      { label: 'ACK', desc: active === 'ACK' ? 'feedback' : 'status' },
      { label: 'Timer', desc: active === 'Timer' ? 'recovery' : 'wait' },
      { label: active, desc: 'protocol' },
    ]}
  />
)

const PppFrame = () => (
  <ProcessPath
    steps={[
      { label: 'Flag', desc: '01111110' },
      { label: 'Address', desc: '11111111' },
      { label: 'Control', desc: '00000011' },
      { label: 'Protocol', desc: 'payload type' },
      { label: 'Info', desc: 'data' },
      { label: 'FCS', desc: 'check' },
      { label: 'Flag', desc: 'end' },
    ]}
  />
)

export const unit5Slides = [
  {
    ...unitTitle(
      5,
      'Data Link Control',
      'Forouzan Ch. 11.1-11.7 and 12.1-12.3: framing, flow control, ARQ, HDLC and PPP framing phases.',
      <NetworkJourney stage="frame" />
    ),
    id: 'cn5-title',
  },
  visualSlide({
    id: 'cn5-roadmap',
    kicker: 'Unit 5 roadmap',
    title: 'Controlling a Link Conversation',
    lead: 'After Unit 4 detects errors, Unit 5 decides how frames are delimited, paced, acknowledged and retransmitted.',
    visual: <ProcessPath steps={['Framing', 'Flow control', 'Error control', 'Noiseless protocols', 'Noisy ARQ', 'HDLC', 'PPP']} />,
    takeaway: 'Data link control is protocol discipline for one hop.',
  }),
  slide({
    id: 'cn5-data-link-control-functions',
    kicker: 'DLC purpose',
    title: 'What Data Link Control Adds',
    subtitle: 'The raw physical bit stream becomes a managed sequence of frames.',
    visual: <ProtocolStack active="DLC" />,
    points: [
      'Framing marks where each frame begins and ends.',
      'Flow control prevents a fast sender from overwhelming a slow receiver.',
      'Error control uses ACKs, NAKs, timers and retransmission after detected damage or loss.',
      'Line discipline decides who may send on the link.',
    ],
    takeaway: 'DLC turns bits on a wire into a reliable local conversation.',
  }),
  slide({
    id: 'cn5-frame-as-pdu',
    kicker: 'Frame',
    title: 'The Frame Is the Data-Link PDU',
    subtitle: 'A frame packages network-layer data with control information for one link.',
    visual: <FramingViz mode="byte-stuffing" />,
    ratio: 'visual-copy',
    points: [
      'The header can carry address and control fields.',
      'The trailer commonly carries an error-detection field such as FCS.',
      'The frame boundary lets the receiver separate one unit from the next.',
    ],
    takeaway: 'Without framing, the receiver sees only an undivided stream of bits.',
  }),
  slide({
    id: 'cn5-framing-problem',
    kicker: 'Framing',
    title: 'The Receiver Needs Boundaries',
    subtitle: 'A continuous bit stream must be cut into meaningful data-link frames.',
    visual: <ProcessPath steps={['bits arrive', 'find start', 'read fields', 'find end', 'deliver payload']} />,
    points: [
      'The receiver must know where the frame starts.',
      'It must know where the frame ends before applying checks.',
      'The framing method must also handle delimiter patterns inside data.',
    ],
    takeaway: 'Framing is synchronization at the data-link layer.',
  }),
  slide({
    id: 'cn5-character-count',
    kicker: 'Framing method',
    title: 'Character Count Uses a Length Field',
    subtitle: 'The header carries the number of characters or bytes in the frame.',
    visual: <ProcessPath steps={['Count=5', 'A', 'B', 'C', 'D', 'next frame']} />,
    points: [
      'The receiver reads the count and consumes that many bytes.',
      'A corrupted count field can misalign the receiver for later frames.',
      'Because synchronization loss is serious, this method is mainly a teaching baseline.',
    ],
    takeaway: 'A length field is simple, but the count itself becomes critical.',
  }),
  slide({
    id: 'cn5-byte-stuffing',
    kicker: 'Framing method',
    title: 'Byte Stuffing Protects Flag Bytes',
    subtitle: 'Special flag bytes delimit frames; escape bytes mark literal flag-like data.',
    visual: <FramingViz mode="byte-stuffing" />,
    ratio: 'visual-copy',
    points: [
      'A flag byte marks the beginning and end of a frame.',
      'If the flag appears in data, the sender inserts an escape byte before it.',
      'The receiver removes escape bytes after recognizing protected data bytes.',
      'The technique is used when the payload is handled as characters or bytes.',
    ],
    takeaway: 'Stuffing lets a delimiter appear inside data without ending the frame.',
  }),
  slide({
    id: 'cn5-bit-stuffing',
    kicker: 'Framing method',
    title: 'Bit Stuffing Protects the Flag Pattern',
    subtitle: 'Bit-oriented protocols insert a 0 after five consecutive 1s in the payload.',
    visual: <FramingViz mode="bit-stuffing" />,
    ratio: 'visual-copy',
    points: [
      'The HDLC flag pattern is 01111110.',
      'After five consecutive 1s in data, the sender stuffs a 0.',
      'The receiver removes a 0 that follows five consecutive 1s.',
      'This prevents data from imitating the flag.',
    ],
    takeaway: 'Bit stuffing preserves transparency for bit-oriented links.',
  }),
  slide({
    id: 'cn5-framing-comparison',
    kicker: 'Framing comparison',
    title: 'Three Ways to Find a Frame',
    subtitle: 'Each framing method solves the boundary problem with a different tradeoff.',
    visual: <ProcessPath steps={['Count field', 'byte flags + ESC', 'bit flags + stuffed 0', 'receiver unpacks']} />,
    points: [
      'Character count is compact but fragile if the count is corrupted.',
      'Byte stuffing is natural for byte-oriented payloads.',
      'Bit stuffing is natural for bit-oriented protocols such as HDLC.',
    ],
    takeaway: 'All framing methods must preserve payload transparency.',
  }),
  slide({
    id: 'cn5-flow-control-need',
    kicker: 'Flow control',
    title: 'Fast Sender, Slow Receiver',
    subtitle: 'Flow control prevents the sender from filling the receiver buffer faster than it can be emptied.',
    visual: <ProcessPath steps={['sender ready', 'frame burst', 'receiver buffer', 'processing delay', 'pace sender']} />,
    points: [
      'A receiver has finite memory and finite processing speed.',
      'If frames arrive too quickly, correct frames may still be discarded.',
      'Flow control is a receiver-protection mechanism, not a noise mechanism.',
    ],
    takeaway: 'A reliable link still fails if the receiver is flooded.',
  }),
  slide({
    id: 'cn5-flow-vs-error-control',
    kicker: 'Control split',
    title: 'Flow Control and Error Control Are Different',
    subtitle: 'They often appear together in protocols, but they answer different questions.',
    visual: <ProtocolStack active="Control" />,
    points: [
      'Flow control asks: may the sender transmit more frames now?',
      'Error control asks: did the receiver get the correct frames?',
      'ACKs can support both pacing and reliability depending on protocol design.',
    ],
    takeaway: 'Do not confuse receiver speed with transmission correctness.',
  }),
  slide({
    id: 'cn5-error-control-ingredients',
    kicker: 'Error control',
    title: 'ACK, NAK and Timeout Drive Recovery',
    subtitle: 'Error control reacts to damaged or missing frames using feedback and timers.',
    visual: <ProtocolStack active="ARQ" />,
    points: [
      'ACK confirms that a frame or group of frames arrived acceptably.',
      'NAK explicitly reports that a frame was damaged or missing.',
      'A timeout handles lost frames and lost acknowledgements.',
      'Retransmission supplies a fresh copy after a failure is inferred.',
    ],
    takeaway: 'ARQ combines detection from Unit 4 with retransmission in Unit 5.',
  }),
  slide({
    id: 'cn5-protocols-overview',
    kicker: 'Protocols',
    title: 'Forouzan Protocol Family',
    subtitle: 'The textbook builds protocols from ideal links to noisy links.',
    visual: <ProcessPath steps={['Simplest', 'Stop-and-Wait', 'Stop-and-Wait ARQ', 'Go-Back-N ARQ', 'Selective Repeat ARQ']} />,
    points: [
      'Noiseless protocols teach sequencing and pacing without errors.',
      'Noisy protocols add sequence numbers, timers and retransmission.',
      'Sliding-window protocols improve utilization by allowing multiple outstanding frames.',
    ],
    takeaway: 'The protocol sequence is a gradual relaxation of ideal assumptions.',
  }),
  slide({
    id: 'cn5-noiseless-assumptions',
    kicker: 'Noiseless channel',
    title: 'Noiseless Protocols Start with Ideal Delivery',
    subtitle: 'Forouzan first assumes frames are not lost, duplicated or damaged.',
    visual: <ProcessPath steps={['no damage', 'no loss', 'ordered arrival', 'finite receiver speed', 'protocol still needed']} />,
    points: [
      'Even without errors, sender and receiver speeds may differ.',
      'The receiver can process only one finite stream of frames.',
      'The protocol can ignore retransmission but not communication order.',
    ],
    takeaway: 'Noiseless does not mean protocol-free.',
  }),
  slide({
    id: 'cn5-simplest-protocol',
    kicker: 'Noiseless protocol',
    title: 'Simplest Protocol Has No Flow Control',
    subtitle: 'The sender transmits frames whenever data is available; the receiver is assumed always ready.',
    visual: <ProcessPath steps={['sender has data', 'make frame', 'send frame', 'receiver accepts', 'repeat']} />,
    points: [
      'There are no acknowledgements.',
      'There are no sequence numbers or timers.',
      'It works only when the receiver can always keep up.',
      'Its value is conceptual: it shows the minimum frame-transfer loop.',
    ],
    takeaway: 'The simplest protocol is a baseline, not a realistic general solution.',
  }),
  visualSlide({
    id: 'cn5-stop-wait-noiseless',
    kicker: 'Noiseless protocol',
    title: 'Stop-and-Wait Adds Receiver Permission',
    lead: 'The sender sends one frame and waits for an acknowledgement before sending the next.',
    visual: <StopWaitTimeline />,
    contentDensity: 'sparse',
    takeaway: 'Stop-and-Wait is simple flow control: one outstanding frame at a time.',
  }),
  formulaSlide({
    id: 'cn5-stop-wait-utilization',
    kicker: 'Efficiency',
    title: 'Stop-and-Wait Wastes Long Links',
    formula: 'Utilization roughly = T_frame / (T_frame + 2T_prop)',
    symbols: [
      'T_frame is the time to transmit the data frame.',
      'T_prop is one-way propagation delay.',
      'The sender is idle while the frame and ACK travel.',
    ],
    example: 'On a long-delay link, most time can be spent waiting rather than transmitting.',
    visual: <StopWaitTimeline />,
    takeaway: 'Sliding windows exist because Stop-and-Wait underuses high-delay links.',
  }),
  slide({
    id: 'cn5-noisy-channel-assumptions',
    kicker: 'Noisy channel',
    title: 'Noisy Links Need Memory and Timers',
    subtitle: 'Once frames can be damaged or lost, both sides must identify which frame is being discussed.',
    visual: <ErrorChannel flipped={5} />,
    ratio: 'visual-copy',
    points: [
      'A frame may arrive corrupted and be discarded.',
      'A frame or ACK may disappear completely.',
      'A retransmitted frame may duplicate one already accepted.',
      'Sequence numbers let the receiver recognize old and new frames.',
    ],
    takeaway: 'Reliability requires state, not only redundancy.',
  }),
  slide({
    id: 'cn5-stop-wait-arq-normal',
    kicker: 'Stop-and-Wait ARQ',
    title: 'Normal Case: Frame, ACK, Next Frame',
    subtitle: 'Stop-and-Wait ARQ extends Stop-and-Wait with numbering and retransmission.',
    visual: <StopWaitTimeline />,
    ratio: 'visual-copy',
    points: [
      'The sender transmits one numbered frame.',
      'The receiver checks the frame and sends an ACK if it is acceptable.',
      'The sender starts the next frame only after the expected ACK arrives.',
      'One-bit sequence numbers are enough because only one frame is outstanding.',
    ],
    takeaway: 'Stop-and-Wait ARQ is easy to reason about but low in throughput.',
  }),
  slide({
    id: 'cn5-stop-wait-lost-frame',
    kicker: 'Stop-and-Wait ARQ',
    title: 'Lost Frame: Timeout Causes Retransmission',
    subtitle: 'If no ACK arrives before the timer expires, the sender assumes failure.',
    visual: <ProcessPath steps={['send frame 0', 'frame lost', 'timer expires', 'resend frame 0', 'ACK 1']} />,
    points: [
      'The timer must be longer than normal round-trip delay.',
      'Retransmission may happen even if the original was only delayed.',
      'The receiver uses the sequence number to reject duplicates.',
    ],
    takeaway: 'Timeout converts silence into a recovery action.',
  }),
  slide({
    id: 'cn5-stop-wait-damaged-frame',
    kicker: 'Stop-and-Wait ARQ',
    title: 'Damaged Frame: NAK or Timeout Recovers',
    subtitle: 'A damaged frame is detected using FCS/CRC and then discarded.',
    visual: <ProcessPath steps={['frame arrives', 'CRC fails', 'discard', 'NAK or no ACK', 'retransmit']} />,
    points: [
      'The receiver must not deliver a failed frame to the network layer.',
      'Some protocols send NAK to speed up retransmission.',
      'If NAK is not used or is lost, timeout still recovers.',
    ],
    takeaway: 'Error detection is local; recovery is protocol behavior.',
  }),
  slide({
    id: 'cn5-sequence-numbers',
    kicker: 'Sequence numbers',
    title: 'Sequence Numbers Stop Duplicate Delivery',
    subtitle: 'A lost ACK can make the sender retransmit a frame that the receiver already accepted.',
    visual: <ProcessPath steps={['Frame 0 accepted', 'ACK lost', 'Frame 0 resent', 'receiver sees duplicate', 'discard + ACK']} />,
    points: [
      'The receiver remembers the next expected sequence number.',
      'A duplicate frame is acknowledged but not delivered again.',
      'Stop-and-Wait alternates sequence numbers 0 and 1.',
    ],
    takeaway: 'Correctness means exactly-once delivery upward, even when frames repeat on the link.',
  }),
  visualSlide({
    id: 'cn5-sliding-window-concept',
    kicker: 'Sliding window',
    title: 'Sliding Window Sends Several Frames Before Waiting',
    lead: 'A sender window marks the sequence numbers that may be transmitted but are not yet fully acknowledged.',
    visual: <SlidingWindowViz size={4} />,
    contentDensity: 'sparse',
    takeaway: 'Windowing trades more state for better link utilization.',
  }),
  slide({
    id: 'cn5-window-terms',
    kicker: 'Sliding window',
    title: 'Window Terms Used in ARQ',
    subtitle: 'Go-Back-N and Selective Repeat use the same vocabulary with different receiver behavior.',
    visual: <SlidingWindowViz size={5} />,
    ratio: 'visual-copy',
    points: [
      'Sender window: frames allowed to be outstanding.',
      'Receiver window: frames the receiver is prepared to accept.',
      'Acknowledgement advances the lower edge of the sender window.',
      'Modulo sequence numbers are reused after the sequence space wraps.',
    ],
    takeaway: 'The window is a moving permission range.',
  }),
  slide({
    id: 'cn5-go-back-n-intro',
    kicker: 'Go-Back-N ARQ',
    title: 'Go-Back-N Allows a Pipeline',
    subtitle: 'The sender may transmit multiple frames, but the receiver accepts only the next expected one.',
    visual: <SlidingWindowViz size={4} />,
    ratio: 'visual-copy',
    points: [
      'The sender has a window size greater than one.',
      'The receiver window size is one in the basic Go-Back-N model.',
      'Frames received out of order are discarded.',
      'Cumulative ACKs report the next expected frame.',
    ],
    takeaway: 'Go-Back-N improves throughput but may retransmit good frames.',
  }),
  slide({
    id: 'cn5-gbn-sender-window',
    kicker: 'Go-Back-N ARQ',
    title: 'Sender Window Holds Outstanding Frames',
    subtitle: 'The sender keeps copies of unacknowledged frames for possible retransmission.',
    visual: <SlidingWindowViz size={4} />,
    ratio: 'visual-copy',
    points: [
      'Frames inside the window can be sent without waiting one by one.',
      'The timer is commonly associated with the oldest outstanding frame.',
      'When an ACK advances the base, new sequence numbers enter the window.',
    ],
    takeaway: 'The sender window is both a permission set and a retransmission buffer.',
  }),
  slide({
    id: 'cn5-gbn-cumulative-ack',
    kicker: 'Go-Back-N ARQ',
    title: 'Cumulative ACKs Summarize Ordered Receipt',
    subtitle: 'ACK n usually means all frames before n have been received correctly.',
    visual: <ProcessPath steps={['receive 0', 'receive 1', 'receive 2', 'ACK 3', 'window slides']} />,
    points: [
      'The receiver does not need to ACK every frame separately.',
      'A single ACK can move the sender window across several frames.',
      'If a frame is missing, later out-of-order frames do not advance the cumulative ACK.',
    ],
    takeaway: 'Cumulative ACKs are compact but tied to in-order delivery.',
  }),
  slide({
    id: 'cn5-gbn-loss-example',
    kicker: 'Go-Back-N ARQ',
    title: 'Loss Forces a Go-Back',
    subtitle: 'If frame 2 is lost, frames 3, 4 and 5 may arrive but be discarded.',
    visual: <ProcessPath steps={['0 OK', '1 OK', '2 lost', '3 discarded', 'timeout', 'resend 2,3,4,5']} />,
    points: [
      'The receiver keeps expecting frame 2.',
      'Later frames are outside the receiver window and are not buffered.',
      'After timeout, the sender retransmits from the missing frame onward.',
    ],
    takeaway: 'Go-Back-N sacrifices bandwidth to keep receiver logic simple.',
  }),
  slide({
    id: 'cn5-selective-repeat-intro',
    kicker: 'Selective Repeat ARQ',
    title: 'Selective Repeat Retransmits Only Missing Frames',
    subtitle: 'The receiver can accept and buffer out-of-order frames within its window.',
    visual: <SlidingWindowViz size={4} />,
    ratio: 'visual-copy',
    points: [
      'Each correctly received frame may be acknowledged individually.',
      'Only damaged or lost frames are retransmitted.',
      'The receiver needs buffer space and reordering logic.',
    ],
    takeaway: 'Selective Repeat saves bandwidth by spending receiver memory.',
  }),
  slide({
    id: 'cn5-sr-receiver-buffer',
    kicker: 'Selective Repeat ARQ',
    title: 'Receiver Buffers Out-of-Order Frames',
    subtitle: 'Frames after a gap are held until the missing frame arrives.',
    visual: <ProcessPath steps={['receive 3', 'buffer 3', 'receive 4', 'buffer 4', 'receive 2', 'deliver 2,3,4']} />,
    points: [
      'Buffered frames are not delivered upward until order is restored.',
      'Individual ACKs tell the sender exactly which frames arrived.',
      'The receiver window slides when the lowest missing frame is filled.',
    ],
    takeaway: 'Selective Repeat separates link arrival order from delivery order.',
  }),
  formulaSlide({
    id: 'cn5-sr-window-rule',
    kicker: 'Selective Repeat ARQ',
    title: 'Selective Repeat Window Must Avoid Ambiguity',
    formula: 'Window size <= 2^(m-1)',
    symbols: [
      'm is the number of bits in the sequence number field.',
      'The sequence number space has 2^m values.',
      'Keeping each window at most half the space prevents old frames from looking new.',
    ],
    example: 'With m = 3, sequence numbers 0-7 allow a Selective Repeat window of at most 4.',
    visual: <SlidingWindowViz size={4} />,
    takeaway: 'Selective Repeat needs a stricter window bound than Go-Back-N.',
  }),
  slide({
    id: 'cn5-gbn-vs-sr',
    kicker: 'ARQ comparison',
    title: 'Go-Back-N vs Selective Repeat',
    subtitle: 'Both pipeline frames, but they choose different complexity tradeoffs.',
    visual: <ProcessPath steps={['GBN: simple receiver', 'GBN: resend many', 'SR: buffer out of order', 'SR: resend selected']} />,
    points: [
      'Go-Back-N uses receiver window size one and cumulative ACKs.',
      'Selective Repeat uses a receiver window larger than one and individual acceptance.',
      'Go-Back-N is simpler; Selective Repeat is more efficient on noisy links.',
    ],
    takeaway: 'Protocol design often trades bandwidth for memory and bookkeeping.',
  }),
  slide({
    id: 'cn5-hdlc-intro',
    kicker: 'HDLC',
    title: 'HDLC Is a Bit-Oriented Data-Link Protocol',
    subtitle: 'High-level Data Link Control standardizes framing, control fields and operating modes.',
    visual: <HdlcFrame />,
    ratio: 'visual-copy',
    points: [
      'HDLC uses bit stuffing with the flag 01111110.',
      'It supports point-to-point and multipoint configurations.',
      'Its frame format inspired several later data-link protocols.',
    ],
    takeaway: 'HDLC is the textbook bridge from ARQ ideas to a real protocol format.',
  }),
  slide({
    id: 'cn5-hdlc-stations',
    kicker: 'HDLC stations',
    title: 'HDLC Station Types and Configurations',
    subtitle: 'Forouzan describes primary, secondary and combined stations.',
    visual: <ProcessPath steps={['Primary', 'Secondary', 'Combined', 'Unbalanced', 'Balanced']} />,
    points: [
      'A primary station controls the link and issues commands.',
      'A secondary station responds to the primary.',
      'A combined station can both command and respond.',
      'Balanced configuration uses combined stations at both ends.',
    ],
    takeaway: 'HDLC separates who controls the link from how frames are formatted.',
  }),
  slide({
    id: 'cn5-hdlc-frame-fields',
    kicker: 'HDLC frame',
    title: 'HDLC Frame Fields',
    subtitle: 'The HDLC frame combines delimiters, addressing, control, payload and error detection.',
    visual: <HdlcFrame />,
    ratio: 'visual-copy',
    points: [
      'Flag fields delimit the frame and use bit stuffing for transparency.',
      'Address identifies the secondary station or destination context.',
      'Control carries sequence numbers, ACKs and frame type information.',
      'FCS detects transmission errors before the frame is accepted.',
    ],
    takeaway: 'The control field is where HDLC protocol behavior is encoded.',
  }),
  slide({
    id: 'cn5-hdlc-frame-types',
    kicker: 'HDLC frame types',
    title: 'I, S and U Frames Have Different Jobs',
    subtitle: 'HDLC classifies frames by the purpose encoded in the control field.',
    visual: <ProcessPath steps={['I-frame: data', 'S-frame: supervision', 'U-frame: management']} />,
    points: [
      'I-frames carry user data plus sequence and acknowledgement information.',
      'S-frames supervise flow and error control when no user data is sent.',
      'U-frames manage link setup, disconnection and mode control.',
    ],
    takeaway: 'HDLC uses one frame format family for data, supervision and management.',
  }),
  slide({
    id: 'cn5-ppp-framing',
    kicker: 'PPP framing',
    title: 'PPP Uses an HDLC-Like Frame',
    subtitle: 'Point-to-Point Protocol frames packets over a direct point-to-point link.',
    visual: <PppFrame />,
    ratio: 'visual-copy',
    points: [
      'PPP frames begin and end with the same flag pattern used by HDLC.',
      'The protocol field identifies the payload protocol being carried.',
      'FCS provides frame error detection.',
      'This unit stops at PPP framing and transition phases.',
    ],
    takeaway: 'PPP is important here as a point-to-point framing protocol.',
  }),
  visualSlide({
    id: 'cn5-ppp-phases',
    kicker: 'PPP transition phases',
    title: 'PPP Moves Through Link Phases',
    lead: 'Forouzan describes PPP operation through phase transitions: dead, establish, authenticate, network, open and terminate.',
    visual: <PppPhases />,
    contentDensity: 'sparse',
    takeaway: 'Know the phase order and purpose; do not expand PPP beyond framing and phases for this unit.',
  }),
  ...closeIds(5, examClose({
    unitNumber: 5,
    title: 'Unit 5 Exam Map',
    mapSteps: ['Framing', 'Flow control', 'Error control', 'Stop-and-Wait', 'Go-Back-N', 'Selective Repeat', 'HDLC', 'PPP phases'],
    notes: [
      'Draw byte stuffing and bit stuffing with before-and-after payload examples.',
      'Explain flow control separately from error control.',
      'Use timelines for Stop-and-Wait ARQ and window diagrams for GBN/SR.',
      'Memorize HDLC fields and PPP transition phases in order.',
    ],
    pyq: [
      'Explain character count, byte stuffing and bit stuffing.',
      'Compare Stop-and-Wait ARQ, Go-Back-N ARQ and Selective Repeat ARQ.',
      'Draw and explain the HDLC frame format and frame types.',
      'Describe PPP framing and transition phases only.',
    ],
    important: [
      'Framing methods and transparency.',
      'ACK, NAK, timeout and sequence numbers.',
      'Stop-and-Wait ARQ operation.',
      'Go-Back-N and Selective Repeat window behavior.',
      'HDLC station types, fields and frame types.',
      'PPP frame fields and phase order.',
    ],
    revision: ['Frame boundary', 'Stuffing', 'ACK/Timer', 'Stop-Wait', 'GBN', 'SR', 'HDLC', 'PPP phases'],
  })),
]

export default unit5Slides
