function m(title, domain, visual, topics, problem, principle, process, equationSteps, example, comparison, misconception, application, extras = {}) {
  return { title, domain, visual, topics, problem, principle, process, equationSteps, example, comparison, misconception, application, ...extras }
}

export const aeroModules = {
  aeoIntro: m(
    'Aviation History, Aircraft Anatomy, Helicopters and Structures',
    'aero', 'aircraft',
    ['History of aviation', 'Atmosphere', 'Aircraft classification', 'Axes and motions', 'Control surfaces and high-lift devices', 'Helicopter parts', 'Monocoque, semi-monocoque, geodesic', 'Airframe materials'],
    'What parts of an aeroplane actually move the air, and how is the structure more than a painted shell?',
    'Control surfaces change moments about body axes. The airframe is a designed load path (often semi-monocoque).',
    ['Identify axis', 'Name the control surface', 'See the motion (pitch/roll/yaw)', 'Look inside: skins + stringers/frames', 'Material chosen for the load'],
    [['pitch', 'elevator', 'Rotation about lateral axis.'], ['roll', 'aileron', 'About longitudinal axis.'], ['yaw', 'rudder', 'About vertical axis.'], ['semi-monocoque', 'skin + stiffeners share load', 'Common metal airframe.']],
    ['To raise the nose, which surface moves, and which axis rotates?', 'longitudinal control', 'elevator, pitch', 'down-force or moment at tail', 'pitch about lateral axis', 'elevator -> pitch', 'elevator / pitch', 'Rudder is yaw, not pitch.'],
    [['construction', 'monocoque', 'semi-monocoque', 'geodesic'], ['load', 'skin primary', 'skin + members', 'lattice']],
    'Flaps are high-lift devices, not the same as ailerons. Do not mix roll control with take-off lift devices.',
    'Every later aero module hangs on this anatomy.',
    { secondaryVisual: 'flight' },
  ),
  aeoAero: m(
    'Aerodynamics: Bernoulli, Lift, Drag and Mach Effects',
    'aero', 'lift',
    ['Speed of sound, airspeed vs groundspeed', 'Standard atmosphere', 'Bernoulli and airspeed measurement', 'Airfoil nomenclature', 'Pressure distribution', 'Lift and drag components', 'Aspect ratio, Mach, supersonic effects'],
    'Why does a wing produce lift, and why does drag come in more than one flavour?',
    'Pressure difference and turning of the flow produce lift. Drag has several named sources; Mach number changes the picture.',
    ['Oncoming flow', 'Airfoil shape + AoA', 'Pressure field', 'Lift and drag resultants', 'Read CL, CD, CP, AC'],
    [['Bernoulli', 'p + 1/2 rho V^2 = const along a streamline (inviscid)', 'Used for pitot airspeed and lift discussion at this level.'], ['lift', 'L = 1/2 rho V^2 S CL', 'From pressure and shear integrated, taught as this formula.'], ['drag', 'D = 1/2 rho V^2 S CD', 'CD includes several types.'], ['Mach', 'M = V / a', 'Compressibility when M is not << 1.']],
    ['If speed doubles and CL is unchanged, what happens to lift?', 'L ~ V^2', 'factor', 'lift x4', 'dynamic pressure quadruples', '4 times', '4L', 'Students often scale lift with V instead of V^2.'],
    [['speed', 'indicated/air', 'ground'], ['depends on', 'relative air', 'air plus wind over ground']],
    'Centre of pressure can move; aerodynamic centre is defined to keep moment behaviour cleaner. Do not treat them as one point without comment.',
    'Wing design, stall margins and airspeed instruments live here.',
    { secondaryVisual: 'aircraft', graphX: 'alpha', graphY: 'CL', graphNote: 'Lift curve: slope then stall drop' },
  ),
  aeoProp: m(
    'Aircraft Propulsion from Piston Engines to Scramjets',
    'aero', 'jet',
    ['Power-plant classification and location', 'Piston, turboprop, turbojet, turbofan', 'Ramjet and scramjet', 'Brayton cycle', 'Propellers vs jets', 'Thrust augmentation'],
    'Where is energy added in a turbojet, and why can a ramjet not take off like a turbofan?',
    'Air is compressed, heated, expanded. Piston + propeller and turbo-machines differ in how they make thrust. Ramjets need forward speed to compress.',
    ['Intake', 'Compression', 'Combustion', 'Turbine (if present) work for compressor', 'Nozzle/propeller thrust'],
    [['thrust', 'mdot (Ve - V0) + pressure term', 'Momentum change of the jet.'], ['Brayton', 'compress-heat-expand', 'Ideal gas-turbine sketch.'], ['turbofan', 'bypass air for efficiency', 'Civil transports.'], ['ramjet', 'no rotating compressor', 'Needs speed; poor static thrust.']],
    ['Why is a scramjet not a first-choice take-off engine?', 'scramjet needs supersonic through-flow', 'reason', 'cannot compress enough at zero speed', 'needs a booster/other engine', 'not for static take-off', 'needs high M', 'Compare with turbofan which produces static thrust.'],
    [['engine', 'piston+prop', 'turbojet', 'turbofan', 'ramjet'], ['best at', 'low speed', 'high speed/high alt', 'transport efficiency', 'very high speed']],
    'A turboprop is not a turbojet with a fan doodle. The propeller is the main thrust maker at lower speeds.',
    'Mission (take-off, cruise Mach, altitude) picks the engine family.',
    { secondaryVisual: 'aircraft' },
  ),
  aeoFlight: m(
    'Flight Performance, Manoeuvres and Stability',
    'aero', 'flight',
    ['Equations of motion', 'Climb, stall, glide, turn', 'Power curves', 'Bank angle', 'Aerobatics and ground effect', 'Static and dynamic stability', 'Neutral point and static margin'],
    'When is the aircraft climbing, stalling or stably returning after a gust?',
    'Performance is force balance along the path. Stability is what the moments do after a disturbance. Static margin measures longitudinal static stability.',
    ['Write force balance', 'Identify climb/glide/turn case', 'Read stall as max CL / min speed', 'Look at moment about CG', 'Static margin = (Xn - Xcg)/c'],
    [['steady level', 'L=W, T=D', 'Four-force balance.'], ['climb', 'T > D, path inclined', 'Excess power/thrust.'], ['stall', 'CL max exceeded / flow separates', 'Not “engine stopped”.'], ['static margin', 'positive => stable', 'CG ahead of neutral point.']],
    ['In a steady level turn, why is lift greater than weight?', 'banked turn', 'L cos phi = W', 'L = W / cos phi', 'vertical component of L balances W', 'L > W', 'L > W', 'The horizontal component of L provides centripetal force.'],
    [['stability', 'static', 'dynamic'], ['question', 'which way first', 'how the oscillation dies']],
    'Stall is an aerodynamic limit, not a power-off condition. Power-off glide is a different performance case.',
    'Training manoeuvres and type-certification language start from these balances.',
    { secondaryVisual: 'lift' },
  ),
  aeoSystems: m(
    'Mechanical and Electrical Aircraft Systems',
    'aero', 'aircraft',
    ['Hydraulics and pneumatics', 'ECS, fuel, oxygen', 'Flight controls', 'Cockpit displays', 'Communication and navigation', 'Engine-driven alternators, APU, RAT', 'Power conversion and distribution'],
    'How does a pilot input become a control-surface move, and where does the electricity come from if an engine quits?',
    'Mechanical systems move energy as fluid pressure; electrical systems generate, convert and distribute power to avionics and controls.',
    ['Pilot or computer command', 'Hydraulic/electric actuator', 'Surface or system response', 'Generators/APU/RAT supply electrical bus', 'Displays/nav/comm stay powered'],
    [['hydraulic', 'pressure -> force at actuator', 'Flight controls, gear, brakes examples.'], ['RAT', 'ram air turbine emergency power', 'Deployed in some failures.'], ['APU', 'auxiliary power on ground/air', 'Independent of main engines to a point.'], ['ECS', 'bleed or electric environmental control', 'Pressurisation/temperature.']],
    ['If both main generators fail, which syllabus devices may still power essential buses?', 'electrical emergency', 'APU and/or RAT depending on aircraft', 'independent energy conversion', 'emergency electrical', 'APU/RAT', 'APU / RAT', 'The battery is limited; RAT converts remaining airspeed to power.'],
    [['energy', 'hydraulic fluid', 'electrical bus'], ['typical', 'actuators', 'avionics, pumps, controls']],
    'More screens do not mean more power sources. Name generator, APU, battery, RAT separately.',
    'Airworthiness is a systems problem: energy, control, life support and navigation together.',
    { secondaryVisual: 'jet' },
  ),
}
