function m(title, domain, visual, topics, problem, principle, process, equationSteps, example, comparison, misconception, application, extras = {}) {
  return { title, domain, visual, topics, problem, principle, process, equationSteps, example, comparison, misconception, application, ...extras }
}

export const mechanicalModules = {
  emeMaterials: m(
    'Engineering, Composite, Smart and Nano Materials',
    'mechanical', 'material',
    ['Ferrous and non-ferrous metals', 'Properties and uses', 'Composite constituents', 'Matrix and reinforcement', 'Piezoelectrics, MR fluids, SMA', 'Nano materials'],
    'Why does a material family exist, and what actually changes when we go from steel to a composite or a smart alloy?',
    'Classification is by structure and response: metals, composites, smart and nano each couple load/environment to a different behaviour.',
    ['Need stated', 'Family chosen', 'Structure/constituents named', 'Property identified', 'Application justified'],
    [['composite', 'matrix + reinforcement', 'Load sharing between phases.'], ['SMA', 'temperature recovers shape', 'Phase change produces strain.'], ['piezo', 'stress <-> voltage', 'Sensor or actuator.'], ['nano', 'high surface/volume', 'Scale changes properties.']],
    ['A car bumper uses polymer + glass fibre. Identify matrix, reinforcement and why.', 'GFRP bumper', 'roles', 'polymer matrix, glass fibres', 'fibres carry load, matrix binds and shapes', 'composite for light stiffness', 'light stiff panel', 'Do not call the whole part “plastic” without naming the fibres.'],
    [['family', 'metal', 'composite', 'smart'], ['response', 'plastic/elastic metal', 'anisotropic high specific strength', 'stimulus-driven change']],
    'A composite is not a metal with a new name. You must name matrix, fibre and the property you bought.',
    'Aerospace and automobile parts are chosen from this map, not from a generic materials list.',
    { secondaryVisual: 'vehicle' },
  ),
  emeThermo: m(
    'Heat, Steam, IC Engines and Electric/Hybrid Vehicles',
    'mechanical', 'engine',
    ['Work, energy, heat', 'Conduction, convection, radiation', 'Steam properties', 'Heat engines and heat pumps', 'Two-stroke and four-stroke SI/CI', 'EV and hybrid storage'],
    'How does heat become piston work in an engine, and what replaces the fuel tank in an electric vehicle?',
    'Heat engines convert heat to work; steam tables quantify phase; EVs store electrical energy instead of chemical fuel in a tank.',
    ['Energy input', 'Working fluid changes state', 'Piston/crank produces work', 'Exhaust or heat rejection', 'EV: battery -> motor -> wheels'],
    [['heat', 'Q is energy in transit by temperature difference', 'Not a stored fluid called heat.'], ['conduction', 'Q ~ k A dT/dx', 'Through a solid.'], ['four-stroke', 'intake-compression-power-exhaust', 'One power stroke in two revolutions.'], ['EV', 'battery energy -> inverter -> motor', 'No tank of petrol.']],
    ['Steam at 100 C with dryness x=0.9: why is enthalpy not that of saturated liquid?', 'wet steam x=0.9', 'h', 'h = hf + x hfg', 'part liquid, part vapour energy', 'use dryness in the steam table mix', 'hf + 0.9 hfg', 'Dryness is a state variable, not a decoration.'],
    [['plant', 'heat engine', 'heat pump'], ['goal', 'work from heat', 'heat moved by work'], ['EV vs ICE', 'stored electricity', 'stored fuel']],
    'Two-stroke and four-stroke are not “faster and slower”. They differ in how many piston strokes make a cycle.',
    'Campus generators, cars and heat pumps are the same energy-conversion idea at different scales.',
    { secondaryVisual: 'vehicle' },
  ),
  emeTools: m(
    'Lathe, Drilling, Milling and Joining Processes',
    'mechanical', 'lathe',
    ['Lathe operations', 'Drilling operations', 'Milling operations', 'Temporary vs permanent joints', 'Soldering', 'Brazing', 'Electric arc welding'],
    'What physically moves in turning, drilling or milling, and how does a joint form in welding versus soldering?',
    'Machine tools shape by relative motion of tool and work. Joining may melt filler (solder/braze) or parent metal (arc weld).',
    ['Work held', 'Tool/work motion set', 'Chip or hole produced', 'If joining: heat + filler or arc', 'Finished geometry or joint'],
    [['turning', 'work rotates, tool feeds', 'Cylindrical surfaces.'], ['drilling', 'rotating tool into work', 'Hole making.'], ['milling', 'rotating multi-tooth cutter', 'Planes, slots, angles.'], ['weld vs solder', 'parent metal melts in arc weld', 'solder melts, parent usually does not.']],
    ['Name the lathe operation that produces a screw thread versus a knurled grip.', 'thread vs knurl', 'operations', 'thread cutting vs knurling', 'thread uses timed tool motion; knurl is a pattern impression', 'distinct operations', 'thread cutting and knurling', 'Do not call every lathe job “turning”.'],
    [['join', 'soldering', 'brazing', 'arc welding'], ['temperature', 'lowest', 'higher', 'melts parent'], ['strength', 'electrical/light', 'stronger filler', 'structural']],
    'Sketches explain operations; the syllabus does not require drawing the whole machine tool.',
    'Every workshop job is a motion recipe plus a joining recipe.',
    { secondaryVisual: 'material' },
  ),
  emeDrives: m(
    'Belt Drives, Gear Trains and Robot Anatomy',
    'mechanical', 'gear',
    ['Open and cross belts', 'Flat and V belts', 'Gear types', 'Simple and compound trains', 'Velocity ratio', 'Robot links, joints, DOF, sensors'],
    'How does rotation at one shaft become rotation at another, and what is a robot joint actually doing?',
    'Belts transmit by friction/tension; gears by meshing teeth. Robot DOF is the number of independent joint motions.',
    ['Input shaft turns', 'Belt or gear mesh acts', 'Output shaft turns', 'VR = N1/N2 related to diameters or teeth', 'Robot: joint motions sweep a work volume'],
    [['belt open', 'same rotation sense', 'No crossing.'], ['VR gears', 'N1/N2 = T2/T1', 'More teeth on driven means it is slower.'], ['compound train', 'idlers on shared shafts', 'Product of stage ratios.'], ['payload', 'max mass at rated accuracy', 'Robot specification.']],
    ['A simple train has T1=20 and T2=60. If N1=1200 rpm, find N2.', 'T1=20, T2=60, N1=1200', 'N2', 'N1 T1 = N2 T2', 'N2=1200*20/60', 'N2=400 rpm', '400 rpm', 'The driven gear is slower and opposite in a simple external mesh.'],
    [['drive', 'belt', 'gear'], ['slip', 'possible', 'no slip if teeth mesh'], ['use', 'large centre distance', 'exact ratio, compact']],
    'Velocity ratio is not “always T1/T2”. Track which shaft is driver.',
    'Machine tools, vehicles and robot arms are all motion-transmission systems.',
    { secondaryVisual: 'belt', tertiaryVisual: 'robot' },
  ),
  emeCnc: m(
    'CNC, Automation, Additive Manufacturing and AI in Mechanical Engineering',
    'mechanical', 'cnc',
    ['NC vs CNC', 'CAD CAM CAE CIM', 'Types of automation', 'Additive process steps', 'Photopolymer, extrusion, powder fusion', 'AI in auto, manufacturing and design'],
    'How does a CAD model become tool motion, and how is a 3D print a different process family from a lathe?',
    'CNC interprets a program into axis motion. Additive manufacturing builds by joining material layer by layer.',
    ['Model in CAD', 'CAM toolpath or slice file', 'Controller', 'Motion or layer fusion', 'Finished part'],
    [['CNC', 'computer updates the program easily', 'NC was more hardwired/tape era.'], ['CIM', 'computers integrate the factory', 'CAD to planning to machines.'], ['AM steps', 'design-slice-build-remove-finish', 'Layerwise.'], ['AI', 'inspect, schedule, design assist', 'Syllabus application domains.']],
    ['Order the additive steps: build, design, slice, finish.', 'AM process', 'order', 'design -> slice -> build -> finish', 'controller follows slices', 'layer stack becomes the solid', 'design-slice-build-finish', 'Skipping slice planning is not how printers work.'],
    [['make', 'subtractive CNC', 'additive'], ['material', 'chip removed', 'material added'], ['geometry', 'tool access limits', 'overhang/support limits']],
    'CAD is not the machine. CAD is the model; CAM/CNC is the motion.',
    'Modern shops mix CNC metal cutting, 3D printing and software automation.',
    { secondaryVisual: 'lathe' },
  ),
  imeIntro: m(
    'Mechanical Engineering Streams, Energy Conversion and Vehicle/Flying Systems',
    'mechanical', 'pump',
    ['Mechanical streams and careers', 'Pelton turbine', 'Centrifugal pump', 'Steering, brake, gear, power steering', 'Drone parts', 'Refrigeration and air conditioning'],
    'Where does mechanical engineering actually change energy form in a campus-scale machine?',
    'Turbines extract work from fluid; pumps add energy to fluid; vehicle systems steer, stop and transmit; drones convert electrical energy to lift.',
    ['Input energy identified', 'Machine principle', 'Output motion or cooling', 'System parts named', 'Social/career context'],
    [['Pelton', 'jet impulse on buckets', 'Work from high-head water.'], ['pump', 'impeller adds KE then pressure', 'Opposite job to a turbine.'], ['power steering', 'assist torque at the wheel', 'Driver input remains.'], ['VCRS idea', 'work moves heat from cold to hot', 'Refrigerator.']],
    ['A Pelton wheel: what is input and what is output?', 'impulse turbine', 'energy forms', 'water jet KE -> shaft work', 'buckets turn the runner', 'mechanical rotation out', 'fluid in, shaft out', 'Do not call it a pump.'],
    [['machine', 'turbine', 'pump'], ['fluid energy', 'decreases', 'increases'], ['use', 'power plant', 'water supply']],
    'A drone is not “a small aeroplane” only. Rotors, battery, controller and frame are the teaching parts.',
    'Water, mobility and comfort systems are the first mechanical map a first-year student should see.',
    { secondaryVisual: 'vehicle' },
  ),
  imeEngines: m(
    'IC Engines, Future Mobility and Power Transmission',
    'mechanical', 'engine',
    ['Petrol and diesel engines', 'Four-stroke working', 'EV and hybrid components', 'Gear classification', 'Simple and compound trains', 'Automatic and CVT concepts'],
    'What repeats every four strokes, and what does a gearbox or CVT change between engine and wheel?',
    'Four-stroke SI/CI engines convert fuel energy to crank work. Transmissions match speed/torque; EVs replace the ICE with motor + battery.',
    ['Intake', 'Compression', 'Power', 'Exhaust', 'Gearbox/CVT or EV motor path to wheels'],
    [['four-stroke', 'two revolutions per cycle', 'One power stroke.'], ['diesel vs petrol', 'CI autoignition vs SI spark', 'Different mixture and ignition.'], ['simple train', 'N1/N2 = T2/T1', 'Tooth count sets speed.'], ['hybrid', 'ICE + electric path', 'Two energy sources.']],
    ['If engine crank speed is 3000 rpm and a simple pair has 20 and 50 teeth, find output shaft speed.', 'N1=3000, T1=20, T2=50', 'N2', 'N2=N1 T1/T2', 'N2=1200 rpm', '1200 rpm', '1200 rpm', 'The gearbox exists to make this kind of match.'],
    [['vehicle', 'ICE', 'EV', 'hybrid'], ['store', 'fuel', 'battery', 'both'], ['spin source', 'crankshaft', 'motor', 'either/both']],
    'CVT is not “more gears”. It is a continuously variable ratio, conceptually different from stepped gears.',
    'Campus-to-highway mobility is this module’s system.',
    { secondaryVisual: 'gear' },
  ),
  imeMaterials: m(
    'Metals, Composites and Smart Materials for Mechanical Design',
    'mechanical', 'material',
    ['Ferrous and non-ferrous', 'Properties and applications', 'Composite classification', 'Matrix and reinforcement', 'Piezo, MR fluid, SMA'],
    'Which property are you buying when you specify a steel, an aluminium, a composite or an SMA?',
    'Metals: crystalline load-bearing. Composites: tailored anisotropy. Smart materials: a stimulus produces a useful response.',
    ['Function needed', 'Property listed', 'Family selected', 'Limitation named', 'Application'],
    [['ferrous', 'iron-based, strength/cost', 'Steels and cast irons.'], ['Al', 'light, corrosion resistant', 'Non-ferrous example.'], ['composite', 'fibre direction matters', 'Not isotropic like many metals.'], ['MR fluid', 'field changes yield stress', 'Damping/clutch.']],
    ['Why is SMA useful in an actuator but not as a cheap structural beam?', 'shape memory alloy', 'role', 'large recoverable strain with heat', 'cost and limited structural modulus', 'actuator/smart, not bulk beam', 'stimulus actuator', 'Match material to function.'],
    [['choose', 'steel', 'composite', 'SMA'], ['for', 'general strength', 'light stiffness', 'shape/force on cue']],
    'Calling everything “metal” hides heat treatment, alloying and corrosion behaviour.',
    'Frames, panels and actuators are specified from this property map.',
    { secondaryVisual: 'vehicle' },
  ),
  imeMfg: m(
    'Manufacturing Processes, Machine Tools, CNC and 3D Printing',
    'mechanical', 'lathe',
    ['Process classification and selection', 'Welding, soldering, brazing', 'Lathe: turning, facing, knurling', 'Drilling, reaming, tapping', 'Milling: end and face', 'CNC components', '3D printing principle'],
    'Given a part, why would you turn it, mill it, weld it or print it?',
    'Process selection follows geometry, material, quantity and tolerance. Each process has a distinct motion or fusion mechanism.',
    ['Part requirement', 'Process family', 'Machine/operation', 'Heat or motion acts', 'Finished feature'],
    [['turning', 'rotation of work', 'Cylinders.'], ['facing', 'flat on the end', 'Lathe.'], ['CNC', 'program + drives + feedback', 'Repeatable axes.'], ['3D print', 'layered addition', 'No cutting toolpath in the subtractive sense.']],
    ['A through hole needs an accurate diameter after drilling. Which follow-up operation?', 'hole quality', 'reaming', 'reaming sizes a drilled hole', 'drill then ream', 'reaming', 'reaming', 'Tapping is for internal threads, not diameter finish.'],
    [['make', 'machining', 'joining', 'additive'], ['mechanism', 'chip', 'fusion/filler', 'layer bond']],
    'CNC is not automatic intelligence. It is programmed motion with feedback.',
    'Workshops and product labs live in this decision tree.',
    { secondaryVisual: 'cnc' },
  ),
  imeAdvances: m(
    'Automation, Mechatronics, Sensors and ADAS',
    'mechanical', 'robot',
    ['Automation definition and types', 'Mechatronic elements', 'Potentiometer', 'Capacitive sensor', 'Optical encoder', 'Need for integration', 'ADAS'],
    'How does a mechanical system become a mechatronic loop that can assist a driver?',
    'Sensors measure, controllers decide, actuators move. ADAS integrates those loops into a vehicle.',
    ['Physical variable', 'Sensor signal', 'Controller', 'Actuator', 'Assisted driving function'],
    [['potentiometer', 'position -> voltage divider', 'Analog position.'], ['encoder', 'rotation -> pulses', 'Digital angle/speed.'], ['capacitive', 'proximity/displacement via C', 'Non-contact.'], ['ADAS', 'sense-plan-act for the driver', 'Lane, brake, cruise examples.']],
    ['A shaft speed is needed for closed-loop motor control. Which sensor from the syllabus fits best?', 'rotation rate', 'optical encoder', 'pulse frequency ~ speed', 'encoder', 'optical encoder', 'encoder', 'A potentiometer measures position, not pulse speed.'],
    [['loop', 'open automation', 'mechatronic closed loop'], ['human', 'may be absent', 'driver still in ADAS'], ['example', 'fixed sequence', 'ABS/ADAS']],
    'ADAS is assistance, not a claim of full autonomy, at this syllabus depth.',
    'Modern cars and factory cells are integrated sensor-controller-actuator systems.',
    { secondaryVisual: 'vehicle' },
  ),
}
