function m(title, domain, visual, topics, problem, principle, process, equationSteps, example, comparison, misconception, application, extras = {}) {
  return { title, domain, visual, topics, problem, principle, process, equationSteps, example, comparison, misconception, application, ...extras }
}

export const electronicsModules = {
  eceDiodes: m(
    'Diodes, Rectifiers, Filters and Zener Regulation',
    'electronics', 'diode',
    ['Diode characteristics', 'DC load line', 'Half-wave rectifier', 'Full-wave bridge', 'Capacitor filter', 'Zener regulator', 'Diode logic'],
    'Why does a diode pass one polarity and block the other, and how does that create DC from AC?',
    'Forward bias opens a current path; reverse bias blocks it. A rectifier uses that switch-like behaviour on a sine wave.',
    ['AC applied', 'Diode forward in one half-cycle', 'Current through load', 'Opposite half blocked or rerouted', 'Filter capacitor holds voltage'],
    [['ideal diode', 'VF approx 0.7 V silicon', 'A conducting silicon diode drops about 0.7 V.'], ['half-wave', 'Vdc approx Vm/pi', 'Average of one surviving half-cycle.'], ['bridge', 'Vdc approx 2 Vm/pi', 'Both half-cycles are used.'], ['zener', 'Vz almost constant in breakdown', 'Used as a shunt regulator.']],
    ['A 12 V peak sine is half-wave rectified into a resistive load. Estimate Vdc.', 'Vm=12 V, half-wave', 'Vdc', 'Vdc = Vm/pi', 'Vdc=12/3.14', 'Vdc approx 3.8 V', '3.8 V average', 'The unused half-cycle is why half-wave DC is lower than full-wave.'],
    [['rectifier', 'half-wave', 'bridge'], ['diodes', 'one', 'four'], ['output', 'one polarity half', 'both halves, same polarity']],
    'Do not treat reverse bias as “no voltage”. The reverse voltage still appears across the diode.',
    'Power supplies, logic OR/AND diode gates and regulators start from this device.',
    { secondaryVisual: 'rectifierHalf', tertiaryVisual: 'rectifierFull', waveform: true },
  ),
  eceTransistors: m(
    'BJT Amplification, Biasing and FET Switches',
    'electronics', 'transistor',
    ['BJT voltages and currents', 'Amplification and switching', 'CB and CE characteristics', 'Fixed and voltage-divider bias', 'JFET', 'Enhancement MOSFET as switch'],
    'How can a small base current control a larger collector current, and when is the transistor a switch instead of an amplifier?',
    'In the active region Ic = beta Ib. At saturation/cutoff the BJT or MOSFET is used as a switch.',
    ['Bias point set', 'Small input applied', 'Device current changes', 'Load resistor converts current to voltage', 'Larger output appears'],
    [['current', 'Ie = Ib + Ic', 'Emitter current is the sum of the other two.'], ['beta', 'Ic = beta Ib', 'Active-region current gain.'], ['load line', 'Vce = Vcc - Ic Rc', 'The resistor maps current to voltage.'], ['MOSFET switch', 'Vgs above threshold -> channel on', 'Case-study switch behaviour.']],
    ['Ib=40 uA and beta=100. Find Ic and Ie.', 'Ib=40e-6 A, beta=100', 'Ic, Ie', 'Ic=beta Ib, Ie=Ib+Ic', 'Ic=4 mA, Ie=4.04 mA', 'Ic=4 mA', 'Ic=4 mA, Ie=4.04 mA', 'The small base current is the control input; collector current is the output action.'],
    [['use', 'amplifier', 'switch'], ['region', 'active', 'saturation/cutoff'], ['output', 'scaled analog', 'on or off']],
    'beta is not a design constant you can assume blindly; bias must keep the Q-point in the intended region.',
    'Audio stages, logic drivers and MOSFET power switches all rest on this current-control idea.',
    { secondaryVisual: 'graph', graphX: 'Vce', graphY: 'Ic', graphNote: 'Q-point sits on the DC load line' },
  ),
  eceOpamp: m(
    'Operational Amplifiers and Linear Applications',
    'electronics', 'opamp',
    ['Op-amp block diagram', 'Gain, Ri, Ro, CMRR, slew rate', 'Ideal op-amp', 'Inverting and non-inverting', 'Voltage follower', 'Integrator and differentiator'],
    'How do the two inputs and feedback set a precise gain instead of leaving the op-amp as a black box?',
    'Negative feedback makes closed-loop gain depend on the resistor network, not on the huge open-loop gain.',
    ['Inputs applied', 'Differential stage acts', 'Feedback network samples output', 'Closed-loop gain appears', 'Integrator/differentiator shape the waveform'],
    [['inverting', 'Av = - Rf/Rin', 'Input current through Rin continues through Rf.'], ['non-inverting', 'Av = 1 + Rf/Rg', 'The divider sets the feedback fraction.'], ['follower', 'Av = 1', 'Buffer: high Zin, low Zout.'], ['CMRR', 'Ad / Acm', 'Rejects what is common to both inputs.']],
    ['Inverting amplifier: Rin=1 k, Rf=10 k. Find Av and vout for vin=0.2 V.', 'Rin=1k, Rf=10k, vin=0.2 V', 'Av, vout', 'Av=-Rf/Rin', 'Av=-10, vout=-2 V', 'vout=-2 V', '-2.0 V', 'The minus sign is inversion, not a loss of energy.'],
    [['config', 'inverting', 'non-inverting'], ['sign', 'inverted', 'same polarity'], ['Zin', 'approx Rin', 'very high']],
    'The ideal virtual short is a closed-loop consequence, not a wire between the pins.',
    'Instrumentation, audio and analog computation use these exact configurations.',
    { secondaryVisual: 'waveform' },
  ),
  eceComm: m(
    'Communication Systems, Analog Modulation and PCM',
    'electronics', 'modulation',
    ['Elements of a communication system', 'Wire, fibre and wireless channels', 'AM, FM and PM waveforms', 'AM broadcast', 'Superheterodyne FM receiver', 'Mobile telephony', 'PCM'],
    'How does a message ride on a carrier, and why must analog become pulses in PCM?',
    'Modulation matches the message to the channel. PCM samples, quantizes and encodes analog into digital.',
    ['Source produces message', 'Transmitter modulates', 'Channel adds loss/noise', 'Receiver recovers', 'PCM path: sample-quantize-encode'],
    [['AM idea', 'envelope follows message', 'Amplitude of carrier is varied.'], ['FM idea', 'instantaneous frequency follows message', 'Better noise performance in the syllabus comparison.'], ['PCM', 'sample -> quantize -> encode', 'Analog to digital conversion chain.'], ['channel', 'bandwidth and noise limit rate', 'Wire, fibre and wireless differ.']],
    ['A 5 V, 1 kHz message amplitude-modulates a 10 V, 100 kHz carrier. Identify fc and fm.', 'Vc=10 V, fc=100 kHz, Vm=5 V, fm=1 kHz', 'carrier and message frequencies', 'spectrum centred at fc with message fm', 'fc=100 kHz, fm=1 kHz', 'envelope rate is 1 kHz', 'fc=100 kHz, fm=1 kHz', 'Students should see the fast carrier and the slow envelope, not a new formula.'],
    [['scheme', 'AM', 'FM'], ['what varies', 'amplitude', 'frequency'], ['classroom waveform', 'changing height', 'changing zero-crossing rate']],
    'FM is not “AM with a different name”. The drawn waveform must show frequency change, not only amplitude change.',
    'Broadcast radio, mobile links and digitised voice all follow this block chain.',
    { secondaryVisual: 'waveform' },
  ),
  eceDigital: m(
    'Number Systems, Boolean Algebra, Gates and Adders',
    'electronics', 'logic',
    ['Binary, octal, hex', 'Base conversion', '1’s and 2’s complement', 'Boolean theorems', 'Canonical forms', 'NAND/NOR universal gates', 'Half adder and full adder'],
    'How does a Boolean expression become a gate circuit and a truth table that an adder can use?',
    'Each gate realises a Boolean connective; a truth table is the complete input-output map.',
    ['Inputs presented', 'Active truth-table row selected', 'Gate computes', 'Sum and carry appear', '4-bit adder repeats the full-adder cell'],
    [['OR', 'Y = A + B', 'Output is 1 if any input is 1.'], ['AND', 'Y = A B', 'Output is 1 only if all inputs are 1.'], ['DeMorgan', "(A B)' = A' + B'", 'NAND is equivalent to inverted-input OR.'], ['half adder', 'Sum=A xor B, Carry=A B', 'Adds two bits with no Cin.']],
    ['Convert 23 decimal to binary and hex.', 'N=23_10', 'binary and hex', 'divide by 2 and group by 4', '10111_2 = 17_16', '10111_2 and 17_16', '10111_2 = 17_16', 'Hex is a readable grouping of binary nibbles.'],
    [['block', 'expression', 'gate', 'truth table'], ['link', 'symbols', 'circuit', 'all input cases']],
    'Do not force analog sine visuals onto logic. A gate is a discrete 0/1 map.',
    'Adders, ALUs and simple control logic are built from these identities.',
    { secondaryVisual: 'adder', truth: true },
  ),
  iecPsu: m(
    'Power Supplies, Rectifiers, Regulators and Amplifiers',
    'electronics', 'psu',
    ['PSU block diagram', 'Reservoir and smoothing', 'Full-wave and bridge rectifiers', 'Voltage regulators', 'Voltage doubler', 'SMPS idea', 'Amplifier gain, BW and negative feedback'],
    'How does a wall sine become a quiet DC, and how does an amplifier make a small signal large without becoming an oscillator?',
    'Rectify then filter then regulate. Negative feedback reduces gain but improves stability and bandwidth.',
    ['AC in', 'Rectifier polarity', 'Reservoir capacitor', 'Regulator holds Vout', 'Amplifier with NFB processes signal'],
    [['ripple', 'filter C reduces delta V', 'Larger C or load current sets ripple.'], ['regulation', 'Vnl - Vfl over Vfl', 'How much voltage sags with load.'], ['gain', 'Av = vout/vin', 'Ratio of output to input.'], ['NFB', 'reduces gain, extends BW', 'Trade gain for predictability.']],
    ['An amplifier with Av=50 has vin=20 mV. Find vout.', 'Av=50, vin=0.02 V', 'vout', 'vout=Av vin', 'vout=1.0 V', '1.0 V', '1.0 V', 'The circuit action, not a “boost magic”, produces the larger output.'],
    [['supply', 'linear PSU', 'SMPS'], ['path', 'transformer-rectify-filter-regulate', 'switching conversion'], ['ripple', 'mains related', 'switching related']],
    'A reservoir capacitor does not make a perfect DC; it reduces ripple. Regulation is a later block.',
    'Every digital board and audio stage sits on this analog power and gain chain.',
    { secondaryVisual: 'filter', waveform: true },
  ),
  iecOsc: m(
    'Oscillators and Operational Amplifier Circuits',
    'electronics', 'oscillator',
    ['Positive feedback', 'Barkhausen condition', 'Wien bridge', 'Ladder network', 'Astable', 'Crystal oscillator', 'Op-amp parameters and configurations'],
    'What must be true of loop gain and phase for a circuit to keep oscillating instead of amplifying once?',
    'Oscillation needs loop gain of unity and phase 0 or 360 degrees. Op-amp circuits then process that or other signals.',
    ['Noise or start-up', 'Amplifier gain', 'Feedback network selects frequency', 'Loop condition met', 'Steady waveform remains'],
    [['Barkhausen', 'A beta = 1, phase 0', 'Necessary oscillation condition in the syllabus treatment.'], ['Wien', 'frequency set by RC', 'No derivation required beyond working and waveform.'], ['crystal', 'very stable frequency', 'Resonator dominates the frequency.'], ['op-amp', 'open-loop huge, closed-loop set by network', 'Configurations use feedback.']],
    ['A Wien network uses R=10 k and C=0.01 uF. Estimate order of f0 ~ 1/(2 pi R C).', 'R=10e3, C=10e-9 F wait 0.01uF=10nF', 'f0', 'f0=1/(2 pi R C)', 'f0 approx 1.6 kHz', 'about 1.6 kHz', '1.6 kHz class of result', 'The RC pair is the frequency-setting part; the amplifier supplies the gain.'],
    [['feedback', 'negative', 'positive'], ['result', 'stable gain', 'oscillation if condition met'], ['use', 'op-amp amp', 'clock/tone generator']],
    'Positive feedback is not automatically an oscillator. The phase and |A beta| conditions must hold.',
    'Function generators, clocks and analog conditioners use these blocks.',
    { secondaryVisual: 'opamp', waveform: true },
  ),
  iecComm: m(
    'Analog and Digital Modulation Schemes',
    'electronics', 'modulation',
    ['Communication system blocks', 'Radio-wave paths', 'AM and angle modulation', 'Multiplexing', 'ASK, FSK, PSK waveforms', 'Digital vs analog communication'],
    'How is a bit made visible on a carrier using ASK, FSK or PSK, and how is that different from AM?',
    'Analog modulation varies a continuous property of the carrier. Digital schemes map bits onto amplitude, frequency or phase states.',
    ['Information source', 'Transmitter maps to carrier', 'Channel + noise', 'Receiver decides', 'Recovered message'],
    [['ASK', 'bit chooses amplitude', 'On-off or two amplitudes.'], ['FSK', 'bit chooses frequency', 'Two tones.'], ['PSK', 'bit chooses phase', 'Phase shift keying.'], ['mux', 'share a channel', 'Many signals on one medium.']],
    ['Identify the ASK waveform feature that encodes a 1 versus a 0.', 'binary message, ASK', 'what changes', 'carrier amplitude states', 'high envelope = 1, low/off = 0', 'amplitude states carry bits', 'amplitude states', 'Compare with FSK (frequency) and PSK (phase) on the same time axis.'],
    [['family', 'analog', 'digital'], ['examples', 'AM, FM', 'ASK, FSK, PSK'], ['decision', 'continuous recovery', 'symbol decision']],
    'PSK is not FSK. If the drawing does not show phase jumps, it is the wrong scheme.',
    'Broadcast, telemetry and short-range digital links are applications of these mappings.',
    { secondaryVisual: 'waveform' },
  ),
  iecEmbedded: m(
    'Embedded Systems, Processors, Memory and I/O',
    'electronics', 'embedded',
    ['Embedded vs general computing', 'Classification and applications', 'Microprocessor vs microcontroller', 'GPP vs ASIP, DSP, RISC vs CISC', 'ROM and sensors', 'Actuators, LED, 7-segment'],
    'Why is a washing-machine controller not designed like a laptop, and what sits around the core?',
    'An embedded system is dedicated, often real-time, with on-chip I/O. Sensors in, actuators out.',
    ['Sensor measures', 'MCU computes', 'Memory holds program/data', 'Actuator/LED acts', 'The loop repeats'],
    [['MCU vs MPU', 'MCU includes memory/I/O', 'MPU needs external support chips.'], ['RISC', 'simple instructions, faster clock cycles', 'CISC has richer instructions.'], ['sensor', 'physical -> electrical', 'Input transducer.'], ['actuator', 'electrical -> physical', 'Output transducer.']],
    ['Classify: 7-segment display showing a digit from an MCU port.', 'display driven by MCU', 'sensor, memory or actuator?', 'it is an output indicator', 'actuator/display class', 'output device', 'output / display', 'The MCU is the core; the display is not the computer.'],
    [['system', 'embedded', 'general computing'], ['goal', 'one job, constraints', 'many apps, UI rich'], ['example', 'ABS, thermostat', 'desktop OS']],
    'A microcontroller is not “a smaller microprocessor” only. Integration of memory and peripherals is the teaching point.',
    'Appliances, automobiles and instruments are embedded loops, not PC clones.',
    { secondaryVisual: 'logic' },
  ),
  iecBoolean: m(
    'Boolean Algebra, Logic Gates and Combinational Adders',
    'electronics', 'logic',
    ['Binary numbers and conversion', 'Complements', 'Boolean theorems', 'Canonical forms', 'Logic gates', 'Half adder', 'Full adder'],
    'How do you go from a number-system value to a Boolean function and then to an adder circuit?',
    'Boolean algebra is the algebra of 0/1. Combinational logic has outputs that depend only on present inputs.',
    ['Bits named', 'Expression written', 'Gates drawn', 'Truth table checked', 'Adder cell reused'],
    [['XOR', 'Sum bit without carry', 'Odd number of 1s.'], ['AND', 'carry generate', 'Both bits 1.'], ['full adder', 'three inputs, Sum and Cout', 'Cin plus two bits.'], ['canonical', 'SOP or POS', 'Standard complete forms.']],
    ['Half adder: A=1, B=1. Find Sum and Carry.', 'A=1, B=1', 'Sum, Carry', 'Sum=A xor B, Carry=A B', 'Sum=0, Carry=1', '0 and 1', 'Sum=0, Carry=1', 'Two 1s cannot make a 1 in a single sum bit; the extra 1 is carry.'],
    [['adder', 'half', 'full'], ['inputs', 'A,B', 'A,B,Cin'], ['use', 'first cell', 'ripple chain']],
    'A full adder is not two independent half adders without connecting the carry. Cin is a real input.',
    'ALUs begin as repeated full-adder cells.',
    { secondaryVisual: 'adder', truth: true },
  ),
}
