function m(title, domain, visual, topics, problem, principle, process, equationSteps, example, comparison, misconception, application, extras = {}) {
  return { title, domain, visual, topics, problem, principle, process, equationSteps, example, comparison, misconception, application, ...extras }
}

export const engineeringModules = {
  beeDc: m(
    'DC Circuits, Electrostatics and Electromagnetism',
    'electrical', 'seriesParallel',
    ['Ohm’s law', 'Kirchhoff’s laws', 'Series-parallel circuits', 'Power and energy', 'Coulomb’s law', 'Capacitance', 'Magnetic circuit'],
    'How does a source force current through series and parallel paths, and how do electric and magnetic fields store that effect?',
    'V = IR in each element; KCL at nodes and KVL around loops fix the unique current map.',
    ['Source applied', 'Current leaves positive terminal', 'Series drop on R1', 'Split at parallel node', 'Return to source'],
    [['Ohm', 'V = I R', 'Voltage across a resistor is current times resistance.'], ['power', 'P = V I = I^2 R', 'Power is the rate of energy conversion in the load.'], ['KCL', 'sum I_in = sum I_out', 'Charge is conserved at a node.'], ['KVL', 'sum V_loop = 0', 'Potential is single-valued around a closed path.']],
    ['A 12 V source feeds 4 ohm in series with two 8 ohm resistors in parallel. Find total current.', 'Vs=12 V, R1=4 ohm, R2=R3=8 ohm', 'I source', 'Req = R1 + (R2||R3)', 'R2||R3=4 ohm, Req=8 ohm', 'I=12/8=1.5 A', '1.5 A from the source', '1.5 A splits equally in the two 8 ohm branches after the series drop.'],
    [['construction', 'series string', 'parallel branches'], ['current', 'same in series', 'splits at node'], ['voltage', 'divides in series', 'same across parallel']],
    'Do not add parallel currents as if they were series voltages. Direction and node identity come first.',
    'DC analysis is the foundation for wiring, power and later AC phasor work.',
    { secondaryVisual: 'capacitor', graphX: 'I (A)', graphY: 'V (V)', graphNote: 'Ohm line: slope is R' },
  ),
  beeInduction: m(
    'Electromagnetic Induction, Inductance and Force on Conductors',
    'electrical', 'induction',
    ['Faraday’s law', 'Lenz’s law', 'Dynamically and statically induced emf', 'Self and mutual inductance', 'Fleming’s left- and right-hand rules', 'Force between current-carrying conductors'],
    'Why does a changing flux produce an emf, and why does the induced current oppose that change?',
    'Induced emf is e = -dPhi/dt; Lenz’s law sets the polarity so the induced current fights the flux change.',
    ['Flux change starts', 'Emf appears with opposing polarity', 'If circuit is closed, current flows', 'Magnetic force appears on the conductor', 'Stored energy 1/2 L I^2'],
    [['Faraday', 'e = - N dPhi/dt', 'Magnitude follows how fast flux linkage changes.'], ['Lenz', 'induced current opposes dPhi/dt', 'The minus sign is a physical direction rule.'], ['inductance', 'e = L di/dt', 'A coil resists current change.'], ['force', 'F = B I l', 'A current in a field feels a side force.']],
    ['Flux through a 200-turn coil falls from 8 mWb to 2 mWb in 40 ms. Find average emf.', 'N=200, dPhi=6e-3 Wb, dt=0.04 s', 'average e', 'e = N dPhi/dt', 'e = 200 * 0.006 / 0.04', 'e = 30 V', '30 V', 'The polarity opposes the decrease of flux if the coil is closed.'],
    [['rule', 'Fleming right hand', 'Fleming left hand'], ['use', 'generator emf direction', 'motor force direction'], ['input', 'motion in field', 'current in field']],
    'Reversing only one finger of Fleming’s rule flips the predicted direction. Keep field, current and motion consistent.',
    'Transformers, inductors and machines all start from induction and force on current.',
    { secondaryVisual: 'machine' },
  ),
  beeAc: m(
    'Single-Phase AC Circuits and Power Factor',
    'electrical', 'acrl',
    ['Sinusoidal generation', 'Average and RMS values', 'Form and peak factor', 'Phasors', 'R, L, C behaviour', 'Series and parallel R-L-C', 'Real, reactive and apparent power'],
    'How does a time-varying voltage create a current that may not peak at the same instant?',
    'RMS measures heating value; inductance delays current and capacitance advances it relative to voltage.',
    ['Sinusoid generated', 'Phasor drawn', 'Element impedance applied', 'Current found', 'P, Q, S and pf read'],
    [['rms', 'Vrms = Vm / sqrt(2)', 'Heating value of a sine wave.'], ['form factor', 'Vrms / Vav = 1.11 for sine', 'Shape check for a sinusoid.'], ['impedance', 'Z = R + j(XL - XC)', 'Net reactance sets phase.'], ['power', 'P = V I cos phi', 'Only the in-phase current does average work.']],
    ['A 230 V, 50 Hz supply feeds R=40 ohm in series with L=0.1 H. Find I and pf.', 'V=230 V, f=50 Hz, R=40, L=0.1 H', 'I and pf', 'XL=2 pi f L, Z=sqrt(R^2+XL^2), I=V/Z', 'XL=31.4 ohm, Z=50.8 ohm, I=4.53 A', 'cos phi = R/Z = 0.79 lag', 'I=4.53 A at 0.79 lag', 'Current lags because XL is present; P = V I pf is the real power.'],
    [['element', 'R', 'L', 'C'], ['phase', 'I in phase with V', 'I lags V', 'I leads V'], ['power', 'real', 'reactive stored', 'reactive stored']],
    'Do not treat peak, average and RMS as interchangeable. Instruments and energy bills use RMS.',
    'Single-phase analysis is the language of household loads and later three-phase systems.',
    { secondaryVisual: 'waveform', graphX: 'wt', graphY: 'v, i' },
  ),
  beeThree: m(
    'Three-Phase Circuits and Two-Wattmeter Power',
    'electrical', 'threephase',
    ['Three-phase generation', 'Phase sequence', 'Star and delta', 'Line and phase values', 'Balanced loads', 'Two-wattmeter method', 'Power factor from wattmeters'],
    'Why do three displaced voltages deliver steadier power, and how do star/delta change line quantities?',
    'For balanced star, VL = sqrt(3) Vph and IL = Iph; for balanced delta the current relation is swapped.',
    ['Three 120-degree voltages generated', 'Star or delta chosen', 'Line/phase relation applied', 'Total power  sqrt(3) VL IL cos phi', 'Two wattmeters confirm P and pf'],
    [['star voltage', 'VL = sqrt(3) Vph', 'Line voltage is across two phases.'], ['delta current', 'IL = sqrt(3) Iph', 'Line current is the difference of two phase currents.'], ['power', 'P = sqrt(3) VL IL cos phi', 'Total true power of a balanced load.'], ['2-wattmeter', 'tan phi = sqrt(3)(W1-W2)/(W1+W2)', 'Wattmeter split encodes pf.']],
    ['A balanced star load takes 10 A from a 415 V three-phase supply at 0.8 lag. Find power.', 'VL=415 V, IL=10 A, pf=0.8', 'P', 'P=sqrt(3) VL IL cos phi', 'P=1.732*415*10*0.8', 'P=5748 W', '5.75 kW', 'Three-phase power is not 3 times a wrongly mixed line/phase pair.'],
    [['connection', 'star', 'delta'], ['VL vs Vph', 'sqrt(3) Vph', 'equal'], ['IL vs Iph', 'equal', 'sqrt(3) Iph']],
    'Mixing line and phase values in the same formula is the most common three-phase error.',
    'Industrial feeders, motors and 2-wattmeter measurements all use this relation set.',
    { secondaryVisual: 'waveform' },
  ),
  beeWiring: m(
    'Domestic Wiring, Billing, Fuse/MCB and Earthing',
    'electrical', 'wiring',
    ['Service mains', 'Batten, casing and conduit wiring', 'Two-way and three-way control', 'Unit of energy', 'Two-part tariff', 'Fuse and MCB', 'Electric shock and earthing'],
    'How does a lighting circuit actually switch, how is energy billed, and what interrupts a dangerous current?',
    'Two-way switching changes the live path; energy is kWh; fuse/MCB open an overcurrent; earthing keeps exposed metal near earth potential.',
    ['Supply arrives on live and neutral', 'Switch selects the live path', 'Load converts energy', 'Meter records kWh', 'Protective device or earth path acts in a fault'],
    [['energy', 'kWh = kW * hours', 'The commercial unit is energy, not power.'], ['bill', 'fixed charge + unit charge', 'Two-part tariff uses sanctioned load and units.'], ['fuse', 'I^2 R heating melts the element', 'Cheap, one-time interrupt.'], ['MCB', 'thermal + magnetic trip', 'Resettable overcurrent protection.']],
    ['A 2 kW heater runs 3 hours/day for 30 days. Find energy and energy charge at Rs 7/unit.', 'P=2 kW, t=3*30=90 h, rate=Rs 7/kWh', 'energy and charge', 'E=P t', 'E=2*90=180 kWh', 'cost=180*7=1260', '180 kWh, Rs 1260 energy charge', 'Sanctioned-load fixed charge is added in a two-part bill.'],
    [['device', 'fuse', 'MCB'], ['action', 'melts', 'trips and can be reset'], ['use', 'simple cheap protection', 'repeatable domestic protection']],
    'Never treat earth as a spare neutral for load current. Earth is a safety path, not a working conductor.',
    'House wiring, tariff reading and shock prevention are the public-facing electrical system.',
    { secondaryVisual: 'psu' },
  ),
  ieePower: m(
    'Power Generation and DC Circuit Laws',
    'electrical', 'psu',
    ['Conventional and nonconventional sources', 'Single-line power system', 'Power grid', 'Ohm’s law', 'Kirchhoff’s laws', 'Series-parallel circuits', 'Power and energy'],
    'How does generated energy reach a load, and how do DC laws describe the local circuit at that load?',
    'A single-line diagram hides three phases into one diagrammatic line; Ohm and Kirchhoff still govern the local currents.',
    ['Source generates', 'Transmission transfers', 'Distribution delivers', 'Load draws current', 'Local circuit obeys KCL/KVL'],
    [['power', 'P = V I', 'Electrical power at a circuit port.'], ['energy', 'W = P t', 'Energy is power accumulated in time.'], ['Ohm', 'V = I R', 'Local resistive drop.'], ['grid', 'stations + lines + loads', 'The grid is a connected power network.']],
    ['A 230 V load draws 4 A for 5 hours. Find energy in kWh.', 'V=230 V, I=4 A, t=5 h', 'energy', 'P=VI, E=P t', 'P=920 W=0.92 kW, E=0.92*5', 'E=4.6 kWh', '4.6 kWh', 'Generation capacity is planned from such load-energy numbers.'],
    [['source', 'conventional', 'nonconventional'], ['example', 'coal/hydro/nuclear', 'solar/wind'], ['grid role', 'dispatchable bulk', 'variable but cleaner']],
    'A single-line diagram is not a one-wire physical circuit. It is a system map.',
    'Power stations, lines and DC load circuits are one energy path from source to use.',
    { secondaryVisual: 'seriesParallel' },
  ),
  ieeAc: m(
    'Single-Phase and Three-Phase Circuit Analysis',
    'electrical', 'waveform',
    ['AC generation', 'Average, RMS, form and peak factor', 'R, L, C relations', 'Power and pf', 'Star and delta', 'Balanced three-phase power'],
    'How do RMS and phasors let us treat sine voltages like DC numbers with an extra phase angle?',
    'RMS is the equivalent DC heating value; pf is the cosine of the angle between V and I.',
    ['Sine generated', 'RMS assigned', 'Impedance phasor used', 'Current computed', 'Three-phase extension if needed'],
    [['rms', 'Irms = Im/sqrt(2)', 'Heating equivalent of the sine.'], ['series RL', 'I = V / sqrt(R^2+XL^2)', 'Net impedance magnitude.'], ['pf', 'cos phi = R/Z', 'Fraction of apparent power that is real.'], ['3-ph', 'P=sqrt(3) VL IL pf', 'Balanced three-phase true power.']],
    ['An RC series circuit has R=30 ohm and XC=40 ohm on 200 V. Find I and pf.', 'R=30, XC=40, V=200', 'I and pf', 'Z=50 ohm, I=V/Z, pf=R/Z', 'I=4 A, pf=0.6 lead', '4 A at 0.6 leading', '4 A leading', 'Capacitance makes current lead voltage; pf is leading, not lagging.'],
    [['circuit', 'single-phase', 'three-phase'], ['power formula', 'V I pf', 'sqrt(3) VL IL pf'], ['wires', 'two live/neutral', 'three lines plus optional N']],
    'A leading pf is not “better voltage”; it means capacitive current. Name lag/lead explicitly.',
    'AC circuit skill is required for machines, transformers and industrial loads in later modules.',
    { secondaryVisual: 'threephase' },
  ),
  ieeDcMachines: m(
    'DC Generators and DC Motors',
    'electrical', 'machine',
    ['DC generator principle', 'Construction', 'Induced emf', 'Types of generators', 'DC motor back emf', 'Torque', 'Speed control of shunt motor'],
    'How does rotation in a field produce emf, and how does the same machine run as a motor when current is fed in?',
    'Generator: motion + field -> emf. Motor: current + field -> torque. Back emf limits motor current.',
    ['Field established', 'Armature conductors cut flux', 'Emf or torque appears', 'Terminal voltage or speed results', 'Load sets current'],
    [['generated emf', 'E = Phi Z N P / (60 A)', 'Flux, speed and winding data fix E.'], ['motor', 'Eb = V - Ia Ra', 'Back emf is less than supply by armature drop.'], ['torque', 'T proportional to Phi Ia', 'Torque follows flux and armature current.'], ['speed', 'N proportional to Eb / Phi', 'Shunt speed control uses flux or voltage.']],
    ['A shunt motor has V=220 V, Ra=0.5 ohm, Ia=40 A. Find back emf.', 'V=220, Ra=0.5, Ia=40', 'Eb', 'Eb=V-Ia Ra', 'Eb=220-20', 'Eb=200 V', '200 V', 'Without Eb the armature would take a damaging current.'],
    [['machine', 'generator', 'motor'], ['input', 'mechanical', 'electrical'], ['output', 'electrical', 'mechanical']],
    'Do not set Eb = V. Armature resistance drop is small but essential.',
    'Lifts, traction and lab machines still use these DC relations.',
    { secondaryVisual: 'induction' },
  ),
  ieeTransformerMotor: m(
    'Transformers and Three-Phase Induction Motors',
    'electrical', 'transformer',
    ['Need for transformers', 'Single-phase construction', 'EMF equation', 'Losses and efficiency', 'Rotating magnetic field', 'Squirrel-cage and wound rotor', 'Slip'],
    'How can a transformer change voltage without a moving part, and why does an induction motor need slip?',
    'Mutual induction transfers energy. An induction motor rotor current exists only if it slips relative to the rotating field.',
    ['Primary excited', 'Core flux couples', 'Secondary emf appears', 'Load current flows', 'In a motor, slip produces rotor current and torque'],
    [['emf', 'E = 4.44 f N Phi_m', 'RMS emf from flux and frequency.'], ['turns', 'Es/Ep = Ns/Np', 'Voltage ratio follows turns ratio.'], ['efficiency', 'n = output / (output + losses)', 'Iron and copper losses reduce output.'], ['slip', 's = (Ns - N)/Ns', 'Rotor must run below synchronous speed.']],
    ['A 400/200 V transformer has 800 primary turns. Find secondary turns.', 'Ep=400, Es=200, Np=800', 'Ns', 'Ns = Np Es/Ep', 'Ns=800*200/400', 'Ns=400', '400 turns', 'The core flux is common; turns set the voltages.'],
    [['device', 'transformer', 'induction motor'], ['motion', 'none', 'rotor with slip'], ['job', 'change voltage', 'produce torque']],
    'A transformer does not create power. Input minus losses is output.',
    'Distribution transformers and industrial motors are the workhorses of AC power.',
    { secondaryVisual: 'machine' },
  ),
  ieeSafety: m(
    'Domestic Wiring, Tariff and Electrical Safety',
    'electrical', 'wiring',
    ['Two-way and three-way control', 'Unit of energy', 'Appliance ratings', 'Two-part tariff', 'Fuse and MCB', 'Shock and earthing'],
    'How is a lamp controlled from two places, and what keeps a person and an appliance safe during a fault?',
    'Two-way switches re-route the live conductor. Earthing and protective devices limit touch voltage and fault duration.',
    ['Live path selected by switches', 'Load consumes kWh', 'Bill uses units and sanctioned load', 'Overcurrent opens fuse/MCB', 'Earth keeps metalwork safe'],
    [['unit', '1 unit = 1 kWh', 'Commercial energy unit.'], ['tariff', 'fixed + running charge', 'Two-part bill.'], ['fuse vs MCB', 'melt vs trip', 'Resetability differs.'], ['earth', 'pipe or plate', 'Low-resistance path to soil.']],
    ['A 100 W lamp used 10 h/day for 30 days. Find monthly units.', 'P=0.1 kW, t=300 h', 'energy', 'E=P t', 'E=30 kWh', '30 units', '30 units', 'The bill multiplies units by the energy rate plus fixed charges.'],
    [['protection', 'equipment', 'personal'], ['means', 'fuse/MCB', 'insulation, earthing, habits'], ['failure mode', 'overcurrent heat', 'shock current through body']],
    'Switch the live, not only the neutral, or the lamp holder can remain live when “off”.',
    'Billing and safety close the loop from generation to the occupied building.',
    { secondaryVisual: 'psu' },
  ),
}
