function m(title, domain, visual, topics, problem, principle, process, equationSteps, example, comparison, misconception, application, extras = {}) {
  return { title, domain, visual, topics, problem, principle, process, equationSteps, example, comparison, misconception, application, ...extras }
}

export const civilModules = {
  civForces: m(
    'Coplanar Force Systems, Moments and Couples',
    'civil', 'fbd',
    ['Idealisation and units', 'Force classification', 'Transmissibility', 'Composition and resolution', 'Free-body diagrams', 'Resultant of concurrent and non-concurrent systems', 'Moment, couple, Varignon'],
    'How do many forces on a body become one resultant and one moment that a student can draw?',
    'A force is a vector. Concurrent systems have a force resultant; non-concurrent systems generally have force plus moment.',
    ['Isolate the body', 'Draw every force', 'Resolve components', 'Sum Fx, Fy', 'Sum moments; replace by R and M'],
    [['resolve', 'Fx = F cos theta, Fy = F sin theta', 'Components in a chosen pair of axes.'], ['resultant', 'R = sqrt(Rx^2 + Ry^2)', 'Magnitude of the force resultant.'], ['moment', 'M = F * d_perp', 'Tendency to rotate about a point.'], ['Varignon', 'moment of a force = sum of moments of components', 'Useful shortcut.']],
    ['Forces 40 N at 0 deg and 30 N at 90 deg act at a point. Find R.', 'F1=40 N east, F2=30 N north', 'R', 'R=sqrt(40^2+30^2)', 'R=50 N at tan^-1(30/40)', '50 N at 37 deg', '50 N', 'The parallelogram (or components) is the diagram, not a guess.'],
    [['system', 'concurrent', 'non-concurrent'], ['resultant', 'through the common point', 'may need a moment too']],
    'Transmissibility does not let you slide a force off the body onto empty space when moments on a different body matter. Draw the FBD of the intended body.',
    'Every later beam and friction problem starts with this vector bookkeeping.',
    { secondaryVisual: 'beam' },
  ),
  civEquilibrium: m(
    'Equilibrium, Supports, Beams and Reactions',
    'civil', 'beam',
    ['Conditions of equilibrium', 'Lami’s theorem', 'Concurrent and non-concurrent equilibrium', 'Supports and loadings', 'Determinate vs indeterminate', 'Beam reactions'],
    'Why does a simply supported beam need two reactions, and how do you find them?',
    'Planar equilibrium: sum Fx=0, sum Fy=0, sum M=0. Support type decides which reactions exist.',
    ['Draw FBD', 'Identify support reactions', 'Write equilibrium equations', 'Solve RA, RB', 'Check with a second moment centre'],
    [['equilibrium', 'sum F = 0 and sum M = 0', 'No net force, no net moment.'], ['Lami', 'P/sin p = Q/sin q = R/sin r', 'Three concurrent forces in equilibrium.'], ['simple support', 'vertical reaction (and maybe horizontal if hinged)', 'Roller vs hinge.'], ['determinate', 'unknowns = independent equations', 'Indeterminate needs more than statics.']],
    ['A 4 m simply supported beam carries 20 kN at midspan. Find reactions.', 'L=4 m, W=20 kN centre', 'RA, RB', 'sum Fy=0, sum M=0', 'RA=RB=10 kN', '10 kN each', 'RA=RB=10 kN', 'Symmetry is a check, not a substitute for the moment equation when loads move.'],
    [['support', 'roller', 'hinge', 'fixed'], ['reactions', 'one force', 'two forces', 'two forces + moment']],
    'A roller does not take a moment. Do not invent a couple at a simple support.',
    'Floor beams, bridges and lab frames are this calculation.',
    { secondaryVisual: 'fbd' },
  ),
  civFriction: m(
    'Friction on Horizontal and Inclined Planes and Ladders',
    'civil', 'friction',
    ['Static and kinetic friction', 'Laws of friction', 'Angle of repose', 'Cone of friction', 'Blocks on horizontal and inclined planes', 'Ladder friction'],
    'When does a block start to slide, and why can a ladder slip at the floor?',
    'Limiting friction F = mu N at impending motion. On an incline, motion impends near the angle of repose.',
    ['Normal from the surface', 'Friction opposes impending slip', 'Write equilibrium', 'Set F = mu N at limiting case', 'Solve angle or force'],
    [['Coulomb', 'F <= mu N', 'Equality only at limiting friction.'], ['repose', 'alpha = tan^-1 mu', 'Angle where self-weight starts slip.'], ['kinetic', 'usually mu_k < mu_s', 'Moving friction is smaller.'], ['ladder', 'friction at floor (and sometimes wall)', 'FBD of the whole ladder.']],
    ['A 100 N block on a horizontal plane has mu_s=0.3. Find the horizontal force at impending motion.', 'W=100 N, mu=0.3', 'P', 'P = mu N = mu W', 'P=30 N', '30 N', '30 N', 'N is 100 N only if no other vertical forces exist.'],
    [['state', 'static, no slip', 'impending', 'kinetic'], ['friction', '< mu N', '= mu N', 'mu_k N']],
    'Friction does not always equal mu N. That is the limiting case only.',
    'Brakes, wedges, shoes and ladders are friction FBDs.',
    { secondaryVisual: 'fbd' },
  ),
  civCentroid: m(
    'Centroid of Simple and Composite Plane Areas',
    'civil', 'centroid',
    ['Centroid vs centre of gravity', 'Axes of symmetry', 'Integration for standard shapes', 'Composite areas', 'Built-up sections'],
    'Where does the area “balance”, and how do holes and extra rectangles move G?',
    'x_bar = sum Ai xi / sum Ai. Holes are negative areas. Symmetry places G on a centreline.',
    ['Split the composite', 'Tabulate Ai, xi, yi', 'Form first moments', 'Divide by total area', 'Plot G on the drawing'],
    [['definition', 'first moment / area', 'Geometric centre of area.'], ['rectangle', 'G at intersection of diagonals', 'Or mid-sides.'], ['triangle', 'G at 2/3 along median from vertex', 'Standard result from integration.'], ['hole', 'subtract its Ai xi', 'Negative area.']],
    ['A 6 cm by 4 cm rectangle has a 2 cm diameter hole at its geometric centre. Where is G?', 'symmetric hole at centre', 'G', 'symmetry unchanged', 'G remains at the rectangle centre', 'centre', 'still the geometric centre', 'A centred hole does not shift G; an offset hole does.'],
    [['quantity', 'centroid', 'centre of gravity'], ['depends on', 'area geometry', 'mass distribution in gravity']],
    'Do not average coordinates of corners without weighting by area.',
    'Beam sections, retaining-wall sections and built-up plates need G before inertia.',
    { secondaryVisual: 'beam' },
  ),
  civInertia: m(
    'Moment of Inertia of Plane Areas',
    'civil', 'centroid',
    ['I about an axis', 'Parallel-axis theorem', 'Perpendicular-axis theorem', 'Polar moment', 'Radius of gyration', 'Standard shapes and composites'],
    'Why is I larger when area is farther from the axis, and how do you move I from a centroidal axis to a parallel axis?',
    'I measures second moment of area. Parallel-axis: I = I_g + A d^2. Never skip the A d^2 term.',
    ['Locate G', 'Compute I_g of each piece', 'Add A d^2 to the required axis', 'Sum composites', 'Optional: k = sqrt(I/A)'],
    [['parallel axis', 'I = Ig + A d^2', 'd is distance between parallel axes.'], ['rectangle', 'Ig = b h^3 / 12 about centroidal axis', 'Stronger if h is the dimension away from the axis.'], ['polar', 'J = Ix + Iy', 'Perpendicular-axis theorem in plane.'], ['gyration', 'k = sqrt(I/A)', 'Equivalent radius.']],
    ['A 40 mm x 20 mm rectangle: I about the centroidal axis parallel to the 40 mm side.', 'b=40 mm, h=20 mm', 'Ig', 'bh^3/12', '40*20^3/12', '26667 mm^4', '2.67e4 mm^4', 'Using 40^3 would be the other centroidal axis — name the axis.'],
    [['axis', 'centroidal', 'parallel non-centroidal'], ['term', 'Ig only', 'Ig + Ad^2']],
    'Parallel-axis theorem requires a centroidal Ig. You cannot add A d^2 to a random axis as if it were G.',
    'Bending strength of beams is an I story.',
    { secondaryVisual: 'beam', graphX: 'y', graphY: 'I contribution' },
  ),
  bsmIntro: m(
    'Civil Disciplines, Construction Materials and Structural Elements',
    'civil', 'building',
    ['Surveying to construction management fields', 'Bricks, stones, cement, steel, wood, concrete', 'Foundation, plinth, lintel, chajja', 'Wall, column, beam, slab, floor, stair'],
    'What parts of a building actually carry load, and which civil field cares about which question?',
    'Materials make elements; elements form a load path from slab to soil. Each civil discipline owns part of that path.',
    ['Identify the field', 'Choose material', 'Name the element', 'See the load path', 'Connect to use'],
    [['foundation', 'transfers load to soil', 'Geotechnical + structural.'], ['column', 'compression member', 'Vertical path.'], ['beam', 'bends, carries slab', 'Horizontal path.'], ['concrete', 'composite of cement, aggregate, water', 'Not “just cement”.']],
    ['A window opening needs a member above it to carry masonry. Name it.', 'opening in wall', 'lintel', 'lintel spans the opening', 'lintel', 'lintel', 'lintel', 'A lintel is not a foundation.'],
    [['element', 'slab', 'beam', 'column', 'foundation'], ['job', 'floor plate', 'span load', 'vertical load', 'soil transfer']],
    'Cement is an ingredient; concrete is the structural material. Do not swap the words.',
    'Reading a building is the first civil literacy.',
    { secondaryVisual: 'green' },
  ),
  bsmGreen: m(
    'Emerging Materials, Smart Cities and Green Building Ratings',
    'civil', 'green',
    ['AAC blocks, bamboo, recycled plastics', 'Selection, durability, sustainability', 'Smart city concept', 'IGBC, LEED, GRIHA purpose and points'],
    'How does a material choice become a rating point, and what is a green building actually scoring?',
    'Green ratings assign weighted points to energy, water, materials and indoor environment. Material selection is one evidence stream.',
    ['Need (energy/water/material)', 'Candidate material', 'Durability check', 'Rating credit', 'Documented building'],
    [['AAC', 'light cellular concrete block', 'Lower dead load, insulation.'], ['bamboo', 'renewable structural/finish use', 'Must meet durability.'], ['GRIHA', 'Indian rating with weighted points', 'Purpose: measure green performance.'], ['smart city', 'integrated urban systems', 'Not only gadgets.']],
    ['Why might AAC replace some clay bricks in a wall?', 'wall material', 'dead load and insulation', 'cellular structure lowers density', 'lighter + thermal', 'AAC where specified', 'lighter insulated masonry', 'Ratings still want evidence, not a brand name.'],
    [['system', 'IGBC', 'LEED', 'GRIHA'], ['role', 'Indian green council', 'international', 'Indian integrated habitat']],
    'A recycled-plastic claim is not automatic sustainability. Durability and use class still govern.',
    'Campuses and cities now specify materials against rating checklists.',
    { secondaryVisual: 'building' },
  ),
  bsmForce: m(
    'Force Systems for Building Mechanics',
    'civil', 'fbd',
    ['Idealisation', 'System of forces', 'Transmissibility', 'Resolution and composition', 'Parallelogram law', 'Concurrent and non-concurrent', 'Moment, couple, Varignon'],
    'How do you replace a messy set of building loads with a resultant a student can equilibrate later?',
    'The same statics as engineering mechanics, taught on building-scale objects: beams, walls, trusses.',
    ['Idealise the member', 'Place loads', 'Resolve', 'Resultant', 'Moment about a support'],
    [['parallelogram', 'two forces at a point -> diagonal', 'Concurrent composition.'], ['couple', 'two equal opposite forces, not collinear', 'Pure moment, resultant force 0.'], ['Varignon', 'M_F = M_components', 'About the same point.'], ['units', 'N, kN, m', 'Keep N-m consistent.']],
    ['A 8 kN horizontal and 6 kN vertical force act at a joint. Find R.', '8 kN and 6 kN perpendicular', 'R', 'R=10 kN', 'sqrt(64+36)=10', '10 kN', '10 kN', 'The joint still has a direction: tan^-1(6/8).'],
    [['load', 'point', 'distributed', 'couple'], ['diagram', 'arrow at point', 'load diagram on span', 'moment arrow']],
    'A couple has no resultant force. You cannot “resolve a couple into a single force” without moving the line of action context.',
    'Wind, self-weight and occupancy become these vectors on the FBD.',
    { secondaryVisual: 'beam' },
  ),
  bsmReactions: m(
    'Equilibrium, Determinate Beams and Support Reactions',
    'civil', 'beam',
    ['FBD', 'Equations of equilibrium', 'Lami’s theorem', 'Loadings, beams, supports', 'Determinate vs indeterminate', 'Reactions on determinate beams'],
    'Given a simply supported or cantilever determinate beam, how do the supports push back?',
    'Supports exist to cancel load. Statics finds those reactions only if the beam is determinate.',
    ['Draw beam and loads', 'Replace supports by reactions', 'Sum Fy and M', 'Solve', 'Sanity-check directions'],
    [['cantilever', 'fixed end: V and M (and maybe H)', 'Wall supplies the couple.'], ['SS beam', 'two vertical reactions (hinge may add H)', 'Three planar equations max.'], ['UDL resultant', 'wL acting at mid of the UDL', 'Replace before taking moments.'], ['indeterminate', 'extra unknown', 'Needs more than pure statics.']],
    ['Cantilever 2 m long, 5 kN at free end. Find fixed-end shear and moment.', 'L=2 m, P=5 kN', 'V, M', 'V=5 kN, M=10 kN m', 'M=P L', 'V=5 kN, M=10 kN·m', '5 kN and 10 kN·m', 'The wall moment is what keeps rotation from happening.'],
    [['beam', 'simply supported', 'cantilever'], ['key unknown', 'two Vs', 'V and M at root']],
    'UDL is not a point load at the end. Its resultant sits at the centroid of the loaded length.',
    'Every slab-on-beam sketch becomes this calculation.',
    { secondaryVisual: 'fbd' },
  ),
  bsmCentroid: m(
    'Centroid of Rectangles, Triangles, Circles and Built-up Sections',
    'civil', 'centroid',
    ['Integration for standard shapes', 'Composite areas', 'Simple built-up sections'],
    'How do you find G of a T-section or an area with a cut-out before talking about bending?',
    'Composite centroid is the area-weighted average of part centroids, with cut-outs negative.',
    ['Partition', 'Table Ai, xi, yi', 'sum Ai xi / sum Ai', 'Mark G', 'Use later for I if needed'],
    [['circle', 'G at centre', 'Symmetry.'], ['semicircle', '4R/(3 pi) from diameter', 'Standard integral result.'], ['quadrant', '4R/(3 pi) from both straight edges', 'Same offset both ways.'], ['T-section', 'two rectangles', 'Watch the common axis.']],
    ['A T has flange 100x20 and web 20x80 mm, aligned on the vertical centreline. Why is y_bar not at mid-height of the web?', 'T section', 'y_bar', 'flange area is large and high', 'area-weighted', 'G nearer the flange', 'closer to flange', 'Equal-thickness intuition fails when areas differ.'],
    [['shape', 'simple', 'composite'], ['method', 'known formula / integration', 'table of parts']],
    'Forgetting to use the same origin for all parts is the usual composite-centroid error.',
    'Steel and RC sections in later design start here.',
    { secondaryVisual: 'building' },
  ),
}
