import { Callout, Definition, Formula, Lead, Points, ResourceHub, Stage, osSlide } from './OsKit.jsx'
import {
  HierarchicalPaging,
  LiveFault,
  LiveThrash,
  LogicalPhysicalAddress,
  MemoryMap,
  SegmentationVisualizer,
  TLBLookup,
  WorkingSetVisualizer,
} from './OsMachine.jsx'
import {
  CopyOnWrite,
  NoteBoard,
  PageFrameMapping,
  StepFlow,
  SwapScene,
  TwoWorld,
} from './OsVisual.jsx'
import { Module4Opening, ModuleEnding } from './OsOpenings.jsx'
import { PageReplacementSimulator } from './OsSims.jsx'

const S = ['Bind', 'MMU', 'Contiguous', 'Paging', 'TLB', 'VM', 'Fault', 'Replace', 'Thrash']
const k = (t) => `MODULE 4 · ${t}`
const s = (cfg, body) => osSlide({ ...cfg, content: body })

export const osModule4Slides = [
  s({ id: 'm4-open', kicker: k('MEMORY IS AN ILLUSION'), title: 'The program is wrong about RAM', composition: 'inspect', camera: 'memory-dive', family: 'address-translation', object: 'illusion', action: 'pull-camera', film: { chapterOpener: true, hero: true } },
    <Stage composition="inspect" visual={<Module4Opening />}>
      <Lead>Pull the camera back from the process. Physical RAM is already fragmented.</Lead>
    </Stage>),

  s({ id: 'm4-bg', kicker: k('BACKGROUND'), title: 'Base and limit: a process sees a window', composition: 'inspect', camera: 'inspect-pcb', family: 'memory-fill', object: 'base-limit', action: 'protect-window' },
    <Stage composition="inspect" story={S} beat={0} visual={<MemoryMap />} takeaway="CPU checks: base ≤ addr < base+limit. Else trap.">
      <Definition term="Base and limit registers">Hardware fence: relocation + bound. The process cannot name another process’s memory.</Definition>
    </Stage>),

  s({ id: 'm4-bind', kicker: k('BINDING'), title: 'When does a name become an address?', composition: 'pipeline', camera: 'pull-timeline', family: 'address-translation', object: 'binding', action: 'three-times' },
    <Stage composition="pipeline" visual={<StepFlow accent="kernel" steps={[{ label: 'Compile time', note: 'absolute · MS-DOS .com' }, { label: 'Load time', note: 'relocatable code' }, { label: 'Execution time', note: 'MMU · can move', kind: 'ok' }]} />} exam="Absolute code vs relocatable vs runtime MMU.">
      <Points items={['Compile time — if you know the location', 'Load time — relocatable code', 'Execution time — process can move; needs hardware']} />
    </Stage>),

  s({ id: 'm4-lp', kicker: k('ADDRESSES'), title: 'Logical versus physical', composition: 'dashboard', camera: 'memory-dive', family: 'address-translation', object: 'two-spaces', action: 'contrast-addr' },
    <Stage composition="dashboard" visual={<TwoWorld tone="memory" a={{ title: 'Logical', lead: 'Generated by the CPU.', points: ['What the program believes', 'Also called virtual', 'Starts at 0 for the process'] }} b={{ title: 'Physical', lead: 'Seen by memory.', points: ['What the chips decode', 'Where bytes really live', 'The MMU maps one to the other'] }} />} exam="Logical = virtual. The MMU maps one to the other.">
      <Lead>The program is never supposed to know the difference.</Lead>
    </Stage>),

  s({ id: 'm4-mmu', kicker: k('MMU'), title: 'The MMU is the translator in the path', composition: 'full-stage', camera: 'page-table', family: 'address-translation', object: 'mmu', action: 'travel-address', film: { hero: true } },
    <Stage composition="full-stage" visual={<LogicalPhysicalAddress />} takeaway="CPU emits a logical address. The MMU adds relocation / looks up a frame. RAM sees physical.">
      <Lead>Watch 0x3A7C split, translate, and land.</Lead>
    </Stage>),

  s({ id: 'm4-dyn', kicker: k('LOADING'), title: 'Dynamic loading and dynamic linking', composition: 'dashboard', camera: 'wide-system', family: 'execution-flow', object: 'linking', action: 'defer' },
    <Stage composition="dashboard" visual={<TwoWorld tone="process" a={{ title: 'Dynamic loading', lead: 'Load a routine on first call.', points: ['Unused code stays on disk', 'Better memory use', 'No special OS support needed'] }} b={{ title: 'Dynamic linking', lead: 'Bind libraries at runtime.', points: ['Stubs find DLL / .so', 'One copy, many processes', 'Needs OS help to share'] }} />} />),

  s({ id: 'm4-swap', kicker: k('SWAPPING'), title: 'Swap a whole process to backing store', composition: 'full-stage', camera: 'travel-disk', family: 'page-fault', object: 'swap', action: 'roll-out' },
    <Stage composition="full-stage" visual={<SwapScene />} takeaway="Modern systems swap pages, not whole processes — that is virtual memory, later.">
      <Lead>When RAM is full, the OS rolls a whole process out to disk and another in. Pending I/O complicates it.</Lead>
    </Stage>),

  s({ id: 'm4-cont', kicker: k('CONTIGUOUS'), title: 'Contiguous allocation: one block per process', composition: 'split-left', camera: 'memory-dive', family: 'memory-fill', object: 'partitions', action: 'first-fit' },
    <Stage composition="split-left" story={S} beat={2} visual={<MemoryMap />} exam="Relocation register + limit. First-fit, best-fit, worst-fit.">
      <Points items={['OS usually in low memory, with the interrupt vector', 'Hole list: first-fit is generally fastest', 'Best-fit searches all; worst-fit leaves big leftovers']} />
    </Stage>),

  s({ id: 'm4-frag', kicker: k('CONTIGUOUS'), title: 'External versus internal fragmentation', composition: 'dashboard', camera: 'memory-dive', family: 'memory-fill', object: 'holes', action: 'contrast-frag' },
    <Stage composition="dashboard" visual={<TwoWorld tone="wait" a={{ title: 'External', lead: 'Waste between processes.', points: ['Holes scattered around', 'Total free is enough', 'No single hole is big enough'] }} b={{ title: 'Internal', lead: 'Waste inside a block.', points: ['Allocated more than requested', 'The slack is unusable', 'Fixed by paging'] }} />} exam="Compaction needs runtime relocation. 50-percent rule: 0.5 N holes for N processes.">
      <Lead>Paging was invented to kill external fragmentation.</Lead>
    </Stage>),

  s({ id: 'm4-page', kicker: k('PAGING'), title: 'Pages in, frames out, no need to be neighbours', composition: 'full-stage', camera: 'memory-dive', family: 'memory-fill', object: 'pages', action: 'split-frames' },
    <Stage composition="full-stage" story={S} beat={3} visual={<PageFrameMapping />} takeaway="Logical address = page number + offset. Page table maps page → frame." exam="Logical address = page number + offset. PT[p] = frame.">
      <Lead>Physical memory becomes equal frames; logical memory becomes equal pages — placed wherever they fit.</Lead>
    </Stage>),

  s({ id: 'm4-pt', kicker: k('PAGING'), title: 'The page table is the map', composition: 'pipeline', camera: 'page-table', family: 'address-translation', object: 'page-table', action: 'lookup' },
    <Stage composition="pipeline" visual={<LogicalPhysicalAddress page="p" off="d" frame="f" />} takeaway="PTBR points at the table. PTLR can limit its size. A free-frame list feeds allocation.">
      <Points items={['Logical address splits into page number p and offset d', 'Page table entry gives the frame f', 'Physical address = f, d']} />
    </Stage>),

  s({ id: 'm4-tlb', kicker: k('TLB'), title: 'TLB: a tiny associative memory in the path', composition: 'split-right', camera: 'page-table', family: 'address-translation', object: 'tlb', action: 'hit-miss', film: { hero: true } },
    <Stage composition="split-right" story={S} beat={4} visual={<TLBLookup hit />} takeaway="Hit: frame from TLB. Miss: walk the page table, then fill the TLB." exam="Associative lookup. ASID avoids a flush on every switch.">
      <Lead>Without a TLB, every memory reference would touch the page table first — twice the RAM traffic.</Lead>
    </Stage>),

  s({ id: 'm4-eat', kicker: k('TLB'), title: 'Effective access time', composition: 'inspect', camera: 'inspect-pcb', family: 'timeline-build', object: 'eat', action: 'substitute' },
    <Stage composition="inspect" visual={<NoteBoard accent="kernel" eyebrow="What the formula says" headline="Keep the hit ratio high" points={[{ lead: 'A hit', rest: 'costs ε + m' }, { lead: 'A miss', rest: 'costs ε + 2m — it walks the table' }, { lead: 'Even 80% hits', rest: 'is not enough for hot code' }]} />} exam="Plug in numbers. Interpret: hit ratio must stay high.">
      <Formula vars={[['α', 'TLB hit ratio'], ['ε', 'TLB lookup time'], ['m', 'memory cycle']]}>(ε + m)α + (ε + 2m)(1 − α)</Formula>
    </Stage>),

  s({ id: 'm4-prot', kicker: k('PAGING'), title: 'Protection bits and shared pages', composition: 'split-left', camera: 'page-table', family: 'lock-motion', object: 'bits', action: 'rwx-share' },
    <Stage composition="split-left" visual={<NoteBoard accent="ok" eyebrow="Per-page control" headline="One bit guards; one frame is shared" points={[{ lead: 'Valid / invalid bit', rest: 'invalid ⇒ trap' }, { lead: 'Read / write / execute' }, { lead: 'Shared code', rest: 'one frame, many page tables' }, { lead: 'Reentrant only', rest: 'no self-modifying code' }]} />}>
      <Points items={['Invalid ⇒ trap', 'Shared libraries live once in RAM', 'Copy-on-write comes with virtual memory']} />
    </Stage>),

  s({ id: 'm4-hier', kicker: k('PAGE TABLE'), title: 'Hierarchical, hashed, inverted', composition: 'pipeline', camera: 'page-table', family: 'address-translation', object: 'multi-level', action: 'shrink-table' },
    <Stage composition="pipeline" visual={<HierarchicalPaging />} exam="32-bit two-level: p1 | p2 | offset. Hashed for 64-bit. Inverted: one entry per frame.">
      <Lead>A flat table for a huge virtual space is itself huge. Use forward-mapped trees, hashes, or invert the table.</Lead>
    </Stage>),

  s({ id: 'm4-seg', kicker: k('SEGMENTATION'), title: 'Memory as named variable-size segments', composition: 'tree', camera: 'memory-dive', family: 'memory-fill', object: 'segments', action: 'map-segments' },
    <Stage composition="tree" visual={<SegmentationVisualizer />} exam="Segment table: base + limit per segment. Offset must be < limit.">
      <Lead>The programmer thinks in code, data, stack — not pages. Hardware still checks the limit.</Lead>
    </Stage>),

  s({ id: 'm4-vm', kicker: k('VIRTUAL MEMORY'), title: 'A virtual space larger than the machine', composition: 'full-stage', camera: 'memory-dive', family: 'memory-fill', object: 'vm', action: 'bigger-than-ram', film: { hero: true } },
    <Stage composition="full-stage" story={S} beat={5} visual={<NoteBoard accent="memory" eyebrow="Virtual memory" headline="Only part of the program lives in RAM" points={[{ lead: 'Logical memory is separated from physical' }, { lead: 'Programs can be larger than RAM' }, { lead: 'Demand paging brings a page when it is touched' }, { lead: 'Shared libraries map into many virtual spaces' }]} />} takeaway="Only part of the process needs to be in RAM at any moment.">
      <Definition term="Virtual memory">Separation of logical memory from physical, so a program can be larger than RAM.</Definition>
    </Stage>),

  s({ id: 'm4-demand', kicker: k('DEMAND PAGING'), title: 'A valid bit that starts invalid', composition: 'split-right', camera: 'page-table', family: 'page-fault', object: 'valid-bit', action: 'lazy-load' },
    <Stage composition="split-right" visual={<NoteBoard accent="kernel" eyebrow="Demand paging" headline="Nothing loads until it is touched" points={[{ lead: 'The pager brings a page on first reference' }, { lead: 'Valid bit says: in a frame right now?' }, { lead: 'Pure demand paging', rest: 'starts with nothing in RAM' }]} />}>
      <Lead>The page table’s valid-invalid bit is the truth: is this page in a frame right now?</Lead>
    </Stage>),

  s({ id: 'm4-fault', kicker: k('PAGE FAULT'), title: 'The journey of a missing page', composition: 'full-stage', camera: 'travel-disk', family: 'page-fault', object: 'fault-path', action: 'cinematic-fault', film: { hero: true } },
    <Stage composition="full-stage" story={S} beat={6} visual={<LiveFault />} takeaway="Trap → save state → find page on disk → free/victim frame → disk→RAM → update PT/TLB → restart." exam="Draw the six (or more) steps of page-fault handling.">
      <Lead>The CPU asked for page 7. The table said no. Everything stops — then the OS moves.</Lead>
    </Stage>),

  s({ id: 'm4-perf', kicker: k('DEMAND PAGING'), title: 'Effective access time with faults', composition: 'inspect', camera: 'inspect-pcb', family: 'timeline-build', object: 'pf-eat', action: 'substitute' },
    <Stage composition="inspect" visual={<NoteBoard accent="fault" eyebrow="Why faults hurt" headline="Disk is ~100,000× slower than RAM" points={[{ lead: 'A hit', rest: 'is a memory access' }, { lead: 'A fault', rest: 'waits on the disk' }, { lead: 'Even a tiny p', rest: 'destroys the average' }]} />}>
      <Formula vars={[['p', 'page-fault probability'], ['ma', 'memory access'], ['pf', 'page-fault overhead']]}>(1 − p) · ma + p · pf</Formula>
      <Callout kind="warn" label="Interpretation">Keep the fault rate microscopic or the average access time collapses.</Callout>
    </Stage>),

  s({ id: 'm4-cow', kicker: k('FORK'), title: 'Copy-on-write: share until a write', composition: 'full-stage', camera: 'follow-process', family: 'memory-fill', object: 'cow', action: 'share-then-copy' },
    <Stage composition="full-stage" visual={<CopyOnWrite />} takeaway="vfork / COW makes fork cheap until exec or a store." exam="COW makes fork cheap until the first write.">
      <Lead>Process creation does not clone every page — parent and child share frames until one writes.</Lead>
    </Stage>),

  s({ id: 'm4-need-rep', kicker: k('REPLACEMENT'), title: 'No free frame: someone must leave', composition: 'cause-effect', camera: 'memory-dive', family: 'page-replacement', object: 'victim', action: 'must-evict' },
    <Stage composition="cause-effect" story={S} beat={7} visual={<StepFlow accent="fault" steps={['Fault', { label: 'Free frame?', kind: 'warn' }, 'Pick victim', { label: 'Write if dirty' }, 'Read new page', { label: 'Restart', kind: 'ok' }]} />}>
      <Lead>The dirty bit means write back only if modified. The reference string is how we grade algorithms.</Lead>
    </Stage>),

  s({ id: 'm4-fifo', kicker: k('FIFO'), title: 'First in, first out — live frames', composition: 'full-stage', camera: 'memory-dive', family: 'page-replacement', object: 'fifo-frames', action: 'simulate-fifo', film: { hero: true } },
    <Stage composition="full-stage" visual={<PageReplacementSimulator algo="fifo" frames={3} />} takeaway="Reference 1,2,3,4,1,2,5,1,2,3,4,5. Three frames → 9 faults." exam="Show the frame contents after each reference, not just the total.">
      <Lead>The oldest page is the victim. Simple — and sometimes foolish.</Lead>
    </Stage>),

  s({ id: 'm4-belady', kicker: k('FIFO'), title: 'Belady’s anomaly: more frames, more faults', composition: 'race', camera: 'memory-dive', family: 'comparison-race', object: 'belady', action: 'show-anomaly', film: { hero: true } },
    <Stage composition="race" visual={<PageReplacementSimulator algo="fifo" frames={3} />} visualB={<PageReplacementSimulator algo="fifo" frames={4} />} takeaway="3 frames: 9 faults. 4 frames: 10 faults. More memory made FIFO worse. Stack algorithms never do this." exam="Name Belady’s anomaly and the counter-example string." />),

  s({ id: 'm4-opt', kicker: k('OPTIMAL'), title: 'Replace the page used farthest in the future', composition: 'timeline', camera: 'pull-timeline', family: 'page-replacement', object: 'opt', action: 'simulate-opt' },
    <Stage composition="timeline" visual={<PageReplacementSimulator algo="opt" frames={4} />} takeaway="Four frames, same string: 6 faults. You cannot know the future — Optimal is the benchmark.">
      <Lead>The lowest possible fault rate. Used to measure how close LRU gets.</Lead>
    </Stage>),

  s({ id: 'm4-lru', kicker: k('LRU'), title: 'The past as a proxy for the future', composition: 'split-left', camera: 'memory-dive', family: 'page-replacement', object: 'lru', action: 'simulate-lru' },
    <Stage composition="split-left" visual={<PageReplacementSimulator algo="lru" frames={4} />} exam="Counter per page, or a stack (move the referenced page to the top).">
      <Points items={['Replace the least recently used page', 'Stack: no search for the victim', 'Approximate with a reference bit, then clock']} />
    </Stage>),

  s({ id: 'm4-clock', kicker: k('CLOCK'), title: 'Second chance: a sweeping hand', composition: 'radial', camera: 'zoom-cpu', family: 'page-replacement', object: 'clock', action: 'sweep' },
    <Stage composition="radial" visual={<PageReplacementSimulator algo="clock" frames={4} />}>
      <Lead>Reference bit 1? Give a second chance (bit←0, move on). Bit 0? Replace. Circular, like a clock face.</Lead>
    </Stage>),

  s({ id: 'm4-count', kicker: k('COUNTING'), title: 'LFU and MFU guess from counts', composition: 'dashboard', camera: 'inspect-pcb', family: 'comparison-race', object: 'lfu-mfu', action: 'contrast-counts' },
    <Stage composition="dashboard" visual={<TwoWorld tone="memory" a={{ title: 'LFU', lead: 'Least frequently used leaves.', points: ['Smallest count is the victim', 'Assumes rarely-used stays rare', 'Old hot pages linger'] }} b={{ title: 'MFU', lead: 'Most frequently used leaves.', points: ['A small count = just arrived', 'Give newcomers time', 'Both need extra bookkeeping'] }} />} />),

  s({ id: 'm4-alloc', kicker: k('FRAMES'), title: 'Equal, proportional, priority — local vs global', composition: 'dashboard', camera: 'wide-system', family: 'memory-fill', object: 'frames', action: 'allocate' },
    <Stage composition="dashboard" visual={<NoteBoard accent="process" eyebrow="Frame allocation" headline="How many frames does each process get?" points={[{ lead: 'Equal', rest: '100 frames, 5 processes → 20 each' }, { lead: 'Proportional', rest: 'to size, or to priority' }, { lead: 'Local replacement', rest: 'stays inside your allocation' }, { lead: 'Global replacement', rest: 'a thief can steal a neighbour’s frame' }]} />} exam="Equal vs proportional. Global vs local." />),

  s({ id: 'm4-thrash', kicker: k('THRASHING'), title: 'When the machine pages instead of running', composition: 'dashboard', camera: 'wide-system', family: 'page-fault', object: 'thrash-dash', action: 'collapse', film: { hero: true } },
    <Stage composition="dashboard" story={S} beat={8} visual={<LiveThrash />} takeaway="CPU high, faults low → healthy. Push multiprogramming until faults explode and CPU collapses — thrashing." exam="OS wrongly adds jobs because CPU is idle — it is idle because of paging.">
      <Lead>Watch the health gauges flip.</Lead>
    </Stage>),

  s({ id: 'm4-locality', kicker: k('THRASHING'), title: 'Locality is why demand paging works at all', composition: 'cause-effect', camera: 'memory-dive', family: 'memory-fill', object: 'locality', action: 'explain-why' },
    <Stage composition="cause-effect" visual={<WorkingSetVisualizer />}>
      <Lead>A process lives in a neighbourhood of pages. Thrashing starts when Σ localities &gt; RAM.</Lead>
    </Stage>),

  s({ id: 'm4-ws', kicker: k('WORKING SET'), title: 'Working-set model: keep Δ recent pages', composition: 'timeline', camera: 'pull-timeline', family: 'memory-fill', object: 'working-set', action: 'window' },
    <Stage composition="timeline" visual={<WorkingSetVisualizer />} exam="D = Σ WSSi. If D > m, suspend a process. Δ too small misses locality; too large merges several.">
      <Formula vars={[['Δ', 'window in references'], ['WSSi', 'pages touched in Δ'], ['D', 'total demand'], ['m', 'frames']]}>if D &gt; m then thrash</Formula>
    </Stage>),

  s({ id: 'm4-pff', kicker: k('PFF'), title: 'Page-fault frequency as a live thermostat', composition: 'split-right', camera: 'wide-system', family: 'page-fault', object: 'pff', action: 'give-or-take' },
    <Stage composition="split-right" visual={<LiveThrash />}>
      <Points items={['Above the upper bound: give more frames', 'Below the lower bound: take frames away', 'Track the working set with a timer + reference bits']} />
    </Stage>),

  s({ id: 'm4-end', kicker: k('CLOSE'), title: 'Module 4 map', composition: 'map', camera: 'wide-system', family: 'execution-flow', object: 'recap', action: 'remember', film: { chapterPayoff: true } },
    <Stage composition="map" visual={<ModuleEnding n={4} />} />),

  s({ id: 'm4-exam', kicker: k('EXAM'), title: 'Questions that keep returning', composition: 'full-stage', camera: 'inspect-pcb', family: 'timeline-build', object: 'questions', action: 'practise' },
    <Stage composition="full-stage" visual={<NoteBoard accent="wait" numbered eyebrow="Most-asked" headline="Rehearse these five" points={[{ lead: 'Logical vs physical', rest: '+ MMU' }, { lead: 'Paging hardware with TLB', rest: '+ EAT' }, { lead: 'Page-fault steps' }, { lead: 'FIFO / LRU / Optimal', rest: 'on the classic string + Belady' }, { lead: 'Thrashing, working set, PFF' }]} />} />),

  s({ id: 'm4-res', kicker: k('STUDY'), title: 'Notes and questions', composition: 'dashboard', camera: 'wide-system', family: 'file-tree', object: 'notes', action: 'continue', film: { finale: true } },
    <Stage composition="dashboard"><ResourceHub moduleId="module-4" /></Stage>),
]
