export const osResources = {
  'module-1': {
    notes: [
      ['Operating system', 'System software that is an intermediary between the user and the hardware — a resource allocator and a control program.'],
      ['Bootstrap', 'Firmware initializes registers, I/O and memory, locates the kernel, loads it, starts init, then waits for interrupts.'],
      ['Dual mode', 'Hardware mode bit: user vs kernel. Privileged instructions trap. System call enters kernel; return resets user mode. Timer prevents hogging.'],
      ['Multiprogramming / timesharing', 'Keep several jobs in memory so the CPU is never idle. Timesharing switches fast enough for interactive response < 1s.'],
      ['System calls', 'The programming interface. APIs (Win32, POSIX, Java) hide numbers. Parameters via registers, memory block, or stack.'],
      ['Six call types', 'Process control, file, device, information maintenance, communications, protection.'],
      ['Policy vs mechanism', 'Policy = what. Mechanism = how. Separation lets policy change without rewriting mechanisms.'],
      ['Structures', 'Simple (MS-DOS), layered, monolithic UNIX kernel, microkernel (messages, portable, slower), loadable modules (Solaris).'],
      ['Virtual machines', 'Host creates the illusion of a machine. Paravirtualization presents a similar-not-identical interface; guest is modified.'],
    ],
    questions: [
      'Define an operating system. Distinguish user view and system view.',
      'Explain dual-mode operation and the role of the timer.',
      'Describe system-call implementation and three parameter-passing methods.',
      'Compare simple, layered, microkernel and modular OS structures.',
      'What is a virtual machine? Distinguish full virtualization, paravirtualization and the JVM.',
      'List OS services for users and for the system.',
      'Explain SYSGEN and the boot process.',
    ],
  },
  'module-2': {
    notes: [
      ['Process', 'A program in execution: code, PC, stack, data. PCB holds state, PC, registers, scheduling, memory, I/O.'],
      ['States', 'new → ready → running → waiting → ready → terminated. Dispatcher latency is switch overhead.'],
      ['Schedulers', 'Long-term: degree of multiprogramming. Short-term: CPU. Medium-term: swapping.'],
      ['IPC', 'Shared memory (bounded buffer) or message passing (direct/indirect, blocking, buffering).'],
      ['Threads', 'Shared address space, private PC/stack. Models: many-to-one, one-to-one, many-to-many. Benefits: responsiveness, sharing, economy, scalability.'],
      ['Criteria', 'Max CPU util & throughput; min turnaround, waiting, response.'],
      ['FCFS', 'P1=24,P2=3,P3=3. Order P1,P2,P3 wait avg 17 (convoy). Reverse order avg 3.'],
      ['SJF / SRTF', 'Optimal average wait. Predict burst with τₙ₊₁ = α tₙ + (1−α) τₙ. Priority + aging against starvation.'],
      ['RR', 'Quantum q. Same three jobs, q=4. q large → FCFS. q tiny → switch overhead.'],
      ['MLQ / MLFQ', 'Fixed classes vs feedback demotion. Multiprocessor: affinity, NUMA, load balancing.'],
    ],
    questions: [
      'Draw the process state diagram and list PCB fields.',
      'Explain context switching with a diagram.',
      'FCFS numerical with convoy effect.',
      'SJF Gantt chart and exponential averaging.',
      'Round Robin with a given time quantum.',
      'Compare multithreading models.',
      'Multilevel feedback queue parameters.',
    ],
  },
  'module-3': {
    notes: [
      ['Race', 'Interleaved read-modify-write on a shared counter loses an update.'],
      ['CS conditions', 'Mutual exclusion, progress, bounded waiting.'],
      ['Peterson', 'flag[i]=true; turn=j; while(flag[j] && turn==j); CS; flag[i]=false.'],
      ['Hardware', 'TestAndSet / Swap atomic. Mutex acquire/release. Spin vs block.'],
      ['Semaphores', 'wait/signal. Binary vs counting. Bounded buffer: empty, full, mutex.'],
      ['Classics', 'Readers-writers; dining philosophers circular wait.'],
      ['Deadlock conditions', 'ME, hold-and-wait, no preemption, circular wait.'],
      ['RAG', 'Request Pi→Rj, assignment Rj→Pi. Cycle + single instance ⇒ deadlock.'],
      ['Banker', 'Need=Max−Alloc. Safe sequence ⟨P1,P3,P4,P2,P0⟩ for the classic 5×3 snapshot. Request only if still safe.'],
      ['Detection/recovery', 'Wait-for graph or Work/Finish. Abort processes or preempt resources (avoid victim starvation).'],
    ],
    questions: [
      'Explain a race condition with interleaved instructions.',
      'Three requirements of a CS solution. Peterson’s algorithm.',
      'Semaphore implementation without busy waiting. Bounded-buffer code.',
      'Dining philosophers: deadlock and one prevention.',
      'Four necessary conditions for deadlock.',
      'Banker’s algorithm: Need matrix and safety sequence.',
      'Deadlock detection and recovery methods.',
    ],
  },
  'module-4': {
    notes: [
      ['Binding', 'Compile / load / execution time. Logical vs physical. MMU translates.'],
      ['Dynamic load/link', 'Load routine when called. Shared libraries via stubs.'],
      ['Contiguous', 'First/best/worst fit. External vs internal fragmentation. Compaction.'],
      ['Paging', 'page|offset → frame|offset. TLB. EAT=(ε+m)α+(ε+2m)(1−α). Hierarchical, hashed, inverted tables. Segmentation: base+limit.'],
      ['Demand paging', 'Valid bit. Fault steps. EAT dominated by disk. Copy-on-write after fork.'],
      ['Replacement', 'String 1,2,3,4,1,2,5,1,2,3,4,5. FIFO 3 frames=9, 4 frames=10 (Belady). Optimal 4 frames=6. LRU stack/counter. Clock/second chance. LFU/MFU.'],
      ['Allocation', 'Equal, proportional, priority. Global vs local.'],
      ['Thrashing', 'High faults, collapsed CPU. Locality. Working set Δ. If D>m suspend. Page-fault frequency thermostat.'],
    ],
    questions: [
      'Logical vs physical addresses and the MMU.',
      'Paging hardware with TLB and EAT numerical.',
      'Steps in handling a page fault.',
      'FIFO, LRU and Optimal on 1,2,3,4,1,2,5,1,2,3,4,5. Belady’s anomaly.',
      'Segmentation hardware.',
      'Copy-on-write.',
      'Thrashing, working-set model, page-fault frequency.',
    ],
  },
  'module-5': {
    notes: [
      ['File', 'Named logical unit. Attributes + operations. Open-file tables (system + per-process). Locks.'],
      ['Access', 'Sequential, direct, indexed.'],
      ['Directories', 'Single, two-level, tree, acyclic graph (links), general graph (cycles). Mount point.'],
      ['Sharing', 'UNIX vs session consistency. Remote FS / NFS failure modes.'],
      ['Implementation', 'FCB/inode. VFS. Directory as list or hash.'],
      ['Allocation', 'Contiguous, linked (FAT), indexed (UNIX direct/indirect). Same file, three pictures.'],
      ['Free space', 'Bit vector, linked list, grouping, counting.'],
      ['Disk', 'Seek + rotation. NAS vs SAN. Queue 98,183,37,122,14,124,65,67 head 53. FCFS 640, SSTF 236, SCAN 331. C-SCAN, LOOK, C-LOOK. Format, partition, boot, sparing.'],
    ],
    questions: [
      'File attributes, operations and open-file data.',
      'Directory structures with diagrams.',
      'Contiguous vs linked vs indexed allocation.',
      'VFS and file-system implementation.',
      'Disk scheduling on 98, 183, 37, 122, 14, 124, 65, 67 starting at 53.',
      'SCAN vs C-SCAN vs LOOK vs C-LOOK.',
      'NAS versus SAN. Disk management (format, boot, bad blocks).',
    ],
  },
}
