/**
 * AELIC (1BEC304) curriculum — source of truth aligned to
 * AELIC_Module_1…5.pptx + Analog_Electronics_and_Linear_ICs_VTU_Complete.pptx
 */

export const AELIC_COURSE = {
  id: 'analog-electronics-linear-ics',
  title: 'Analog Electronics and Linear Integrated Circuits',
  code: '1BEC304',
  shortTitle: 'AELIC',
}

export const AELIC_MODULES = [
  {
    n: 1,
    id: 'module-1',
    title: 'BJT AC Models and Voltage Amplifiers',
    hours: 9,
    question: 'How does a biased BJT turn a tiny AC wiggle into a usable voltage?',
    story: ['Bias', 're′', 'Model', 'Gain', 'Cascade', 'Buffer'],
    syllabus: [
      'Base biased amplifier',
      'Emitter biased amplifier',
      'Small signal operation',
      'AC beta',
      'AC resistance of the emitter diode',
      'Two-transistor models',
      'Analyzing amplifier',
      'Voltage amplifiers',
      'Voltage gain',
      'Multistage amplifiers',
      'CC amplifier',
      'Output impedance',
      'Cascading CE and CC',
      'Darlington connections',
      'Voltage regulation',
      'Common-base amplifier',
    ],
    formulas: [
      { eq: 'Av ≈ −RC / re′', mean: 'CE voltage gain set by collector load over emitter diode resistance' },
      { eq: 're′ ≈ 25 mV / IE', mean: 'AC resistance of the forward-biased emitter diode' },
      { eq: 'βac = ic / ib', mean: 'AC beta relates collector and base signal currents' },
      { eq: 'Av,total = Av1 × Av2 × …', mean: 'Loaded stage gains multiply in a cascade' },
    ],
    units: [
      {
        topic: 'Base biased amplifier',
        terms: ['bias path', 'Q point', 'AC signal', 'coupling capacitor'],
        definition: 'Base bias fixes operating point so the BJT can amplify small AC variations.',
        takeaway: 'Bias must keep the transistor in active region.',
        visual: 'bjt-base-bias',
        formula: { eq: 'IB = (VCC − VBE) / RB', vars: [['IB', 'base bias current'], ['RB', 'base resistor'], ['VBE', '≈ 0.7 V']] },
        numerical: {
          given: ['VCC = 12 V', 'RB = 470 kΩ', 'RC = 2.2 kΩ', 'β = 100'],
          find: 'IC and VC',
          steps: ['IB = (12 − 0.7) / 470k ≈ 24 μA', 'IC = β IB ≈ 2.4 mA', 'VC = VCC − IC RC ≈ 6.7 V'],
          result: 'Q-point near mid-supply → room for AC swing',
        },
      },
      {
        topic: 'Emitter biased amplifier',
        terms: ['emitter resistor', 'thermal stability', 'bypass capacitor', 'gain'],
        definition: 'Emitter bias improves stability by adding negative feedback in DC operation.',
        takeaway: 'Stability and gain are traded through emitter resistance.',
        visual: 'bjt-emitter-bias',
        formula: { eq: 'IE ≈ (VEE − VBE) / RE', vars: [['RE', 'emitter resistor'], ['VEE', 'emitter supply']] },
        numerical: {
          given: ['VEE = 12 V', 'RE = 2.2 kΩ', 'RC = 3.3 kΩ'],
          find: 'IE and DC stability idea',
          steps: ['IE ≈ (12 − 0.7) / 2.2k ≈ 5.1 mA', 'If β drifts, IE still set mostly by RE', 'Bypass RE for AC to restore gain'],
          result: 'DC feedback stabilizes; AC bypass restores Av',
        },
      },
      {
        topic: 'Small signal operation',
        terms: ['incremental signal', 'active region', 'linearization', 'Q point'],
        definition: 'Small-signal analysis replaces nonlinear curves with local linear models.',
        takeaway: 'Amplifier math is built around the operating point.',
        visual: 'small-signal-ride',
        formula: { eq: 'v = VQ + vin', vars: [['VQ', 'DC bias'], ['vin', 'small AC']] },
        numerical: {
          given: ['VQ = 6 V', 'vin = 10 mV peak'],
          find: 'Whether linear small-signal assumption holds',
          steps: ['Peak AC ≪ thermal voltage scale (~26 mV) is safer', '10 mV is a classic small-signal drive', 'Stay in active region on both peaks'],
          result: 'Treat BJT as linearised around Q',
        },
      },
      {
        topic: 'AC beta and emitter diode resistance',
        terms: ['βac', 're′', 'thermal voltage', 'emitter current'],
        definition: 'AC beta relates collector signal current to base signal current; emitter resistance sets gain scale.',
        takeaway: 're′ falls as emitter current rises.',
        visual: 're-prime',
        formula: { eq: 're′ = VT / IE ≈ 25 mV / IE', vars: [['VT', 'thermal voltage'], ['IE', 'DC emitter current']] },
        numerical: {
          given: ['IE = 1 mA', 'RC = 4.7 kΩ'],
          find: 're′ and approximate Av',
          steps: ['re′ ≈ 25 / 1 = 25 Ω', 'Av ≈ −RC / re′ = −4700 / 25 = −188', 'Higher IE → smaller re′ → larger |Av|'],
          result: 'Av ≈ −188 (ideal unloaded estimate)',
        },
      },
      {
        topic: 'Two-transistor models',
        terms: ['r′ model', 'hybrid model', 'input resistance', 'current gain'],
        definition: 'Models simplify the BJT into resistances and controlled sources.',
        takeaway: 'Choose the model that makes the circuit easiest to analyze.',
        visual: 'bjt-r-model',
        formula: { eq: 'rin(base) ≈ βac · re′', vars: [['rin', 'looking into base'], ['βac', 'AC beta']] },
        numerical: {
          given: ['βac = 150', 're′ = 25 Ω'],
          find: 'Base input resistance of the intrinsic BJT',
          steps: ['rin ≈ 150 × 25 = 3750 Ω', 'Bias network appears in parallel', 'Use hybrid-π or r′ model consistently'],
          result: 'rin ≈ 3.75 kΩ (device only)',
        },
      },
      {
        topic: 'Voltage amplifiers',
        terms: ['input', 'output', 'phase inversion', 'loading'],
        definition: 'A voltage amplifier converts small input voltage changes into larger output voltage changes.',
        takeaway: 'Common-emitter stages give voltage gain and phase inversion.',
        visual: 'amp-gain-phase',
        formula: { eq: 'Av = vout / vin', vars: [['vout', 'AC output'], ['vin', 'AC input']] },
        numerical: {
          given: ['vin = 5 mV', 'measured vout = 0.8 V inverted'],
          find: 'Voltage gain',
          steps: ['|Av| = 0.8 / 0.005 = 160', 'Phase = 180° for CE', 'Check loading of next stage'],
          result: 'Av = −160',
        },
      },
      {
        topic: 'Multistage amplifiers',
        terms: ['stage gain', 'loading', 'coupling', 'overall gain'],
        definition: 'Cascaded stages multiply gain but interact through impedances.',
        takeaway: 'Overall gain must include loading between stages.',
        visual: 'multistage',
        formula: { eq: 'Av = Av1′ × Av2′', vars: [["Av1′", 'stage 1 with load of stage 2'], ["Av2′", 'stage 2 loaded']] },
        numerical: {
          given: ['Unloaded Av1 = −80', 'Unloaded Av2 = −40', 'heavy loading reduces each by ~0.7'],
          find: 'Overall estimate',
          steps: ['Av1′ ≈ −56', 'Av2′ ≈ −28', 'Product ≈ 1568'],
          result: 'Always redesign with Zin/Zout of neighbours',
        },
      },
      {
        topic: 'CC amplifier and output impedance',
        terms: ['emitter follower', 'high Zin', 'low Zout', 'buffer'],
        definition: 'The CC stage buffers signals with near-unity voltage gain.',
        takeaway: 'Emitter followers are impedance transformers.',
        visual: 'emitter-follower',
        formula: { eq: 'Av ≈ 1', vars: [['Zout', 'much smaller than CE'], ['Zin', 'high']] },
        numerical: {
          given: ['vin = 1 V', 'measured vout ≈ 0.98 V'],
          find: 'Role of the stage',
          steps: ['Av ≈ 0.98 ≈ 1', 'No phase inversion', 'Drives low-Z loads that would kill a CE stage'],
          result: 'Use CC as buffer / impedance match',
        },
      },
      {
        topic: 'Darlington and voltage regulation',
        terms: ['compound β', 'high input resistance', 'regulator', 'load change'],
        definition: 'Darlington connections increase current gain; regulators hold output against load changes.',
        takeaway: 'Current gain helps drive loads without heavy source loading.',
        visual: 'darlington',
        formula: { eq: 'βD ≈ β1 · β2', vars: [['βD', 'compound current gain']] },
        numerical: {
          given: ['β1 = β2 = 100'],
          find: 'Darlington β',
          steps: ['βD ≈ 10 000', 'Base current demand falls dramatically', 'Useful in series regulators and high-Z drivers'],
          result: 'βD ≈ 10⁴ (ideal product)',
        },
      },
      {
        topic: 'Common-base amplifier',
        terms: ['low Zin', 'high frequency', 'current buffer', 'no inversion'],
        definition: 'The CB stage is useful when low input impedance or high-frequency response is needed.',
        takeaway: 'Not every amplifier is optimized for voltage gain.',
        visual: 'common-base',
        formula: { eq: 'Ai ≈ 1', vars: [['Zin', 'low'], ['phase', '0°']] },
        numerical: {
          given: ['ie = 1 mA AC', 'α ≈ 0.99'],
          find: 'ic',
          steps: ['ic = α ie ≈ 0.99 mA', 'Voltage can still be developed across RC', 'No phase inversion at collector vs emitter input'],
          result: 'Current buffer with wideband behaviour',
        },
      },
    ],
  },
  {
    n: 2,
    id: 'module-2',
    title: 'MOSFET Biasing, Small Signal Models, and Amplifier Configurations',
    hours: 9,
    question: 'How does gate voltage become drain current — and then voltage gain?',
    story: ['VGS', 'Bias', 'gm', 'CS', 'CG', 'Follower'],
    syllabus: [
      'Fixing VGS',
      'Fixing VG',
      'Drain-to-gate feedback resistor',
      'DC bias point',
      'Signal current in drain',
      'Voltage gain',
      'Small-signal equivalent circuit models',
      'Transconductance',
      'Equivalent circuit model',
      'Basic configurations',
      'Characterizing amplifiers',
      'CS amplifier with and without source resistance',
      'Common-gate amplifier',
      'Source follower',
    ],
    formulas: [
      { eq: 'id = gm · vgs', mean: 'Small-signal drain current from gate voltage' },
      { eq: 'Av ≈ −gm RD', mean: 'CS voltage gain (no source degeneration)' },
      { eq: 'Av ≈ −gm RD / (1 + gm RS)', mean: 'CS with unbypassed source resistance' },
      { eq: 'Av (follower) < 1', mean: 'Source follower buffers with near-unity gain' },
    ],
    units: [
      {
        topic: 'Fixing VGS',
        terms: ['gate-source voltage', 'bias', 'threshold', 'drain current'],
        definition: 'Fixing VGS sets the MOSFET operating current from the transfer characteristic.',
        takeaway: 'Bias must place the device in the intended operating region.',
        visual: 'mos-vgs',
        formula: { eq: 'ID = k (VGS − VT)²', vars: [['VT', 'threshold'], ['k', 'device constant']] },
        numerical: {
          given: ['VT = 1 V', 'VGS = 2.5 V', 'k = 0.5 mA/V²'],
          find: 'ID',
          steps: ['Overdrive = 1.5 V', 'ID = 0.5 × (1.5)² = 1.125 mA'],
          result: 'ID ≈ 1.13 mA',
        },
      },
      {
        topic: 'Fixing VG',
        terms: ['voltage divider', 'source resistor', 'self bias', 'stability'],
        definition: 'A fixed gate voltage with source feedback stabilizes the operating point.',
        takeaway: 'Source feedback reduces sensitivity to device variation.',
        visual: 'mos-vg-divider',
        formula: { eq: 'VG = VDD · R2 / (R1 + R2)', vars: [['VG', 'gate Thevenin voltage']] },
        numerical: {
          given: ['VDD = 12 V', 'R1 = R2 = 1 MΩ', 'RS = 1 kΩ'],
          find: 'VG and bias idea',
          steps: ['VG = 6 V', 'VS = ID RS', 'VGS = VG − VS self-adjusts'],
          result: 'Divider + RS = stable bias',
        },
      },
      {
        topic: 'Drain-to-gate feedback bias',
        terms: ['feedback resistor', 'gate current', 'drain voltage', 'self correction'],
        definition: 'Drain-to-gate feedback adjusts gate voltage when drain current shifts.',
        takeaway: 'Feedback makes bias less fragile.',
        visual: 'mos-dg-feedback',
        formula: { eq: 'VG ≈ VD (IG ≈ 0)', vars: [['RF', 'drain-gate resistor']] },
        numerical: {
          given: ['Target VD mid-supply', 'IG ≈ 0'],
          find: 'Bias behaviour',
          steps: ['If ID rises, VD falls', 'VG follows VD downward', 'ID is pulled back'],
          result: 'Negative feedback around the bias point',
        },
      },
      {
        topic: 'DC bias point',
        terms: ['Q point', 'load line', 'saturation region', 'signal swing'],
        definition: 'The DC bias point determines available signal swing and linearity.',
        takeaway: 'Poor bias clips the signal before amplification helps.',
        visual: 'mos-loadline',
        formula: { eq: 'VDS = VDD − ID RD', vars: [['Q', 'intersection with transfer/load']] },
        numerical: {
          given: ['VDD = 10 V', 'ID = 1 mA', 'RD = 4.7 kΩ'],
          find: 'VDS',
          steps: ['IR drop = 4.7 V', 'VDS = 5.3 V'],
          result: 'Mid-rail Q allows large AC swing',
        },
      },
      {
        topic: 'Signal current and voltage gain',
        terms: ['gm', 'drain current', 'load resistance', 'inversion'],
        definition: 'Small drain-current changes through a load create output voltage gain.',
        takeaway: 'Gain is controlled mainly by transconductance and load resistance.',
        visual: 'mos-gain',
        formula: { eq: 'Av = vout / vin ≈ −gm RD', vars: [['gm', 'transconductance'], ['RD', 'drain load']] },
        numerical: {
          given: ['gm = 2 mS', 'RD = 4.7 kΩ'],
          find: 'Av',
          steps: ['gm RD = 9.4', 'Av ≈ −9.4'],
          result: 'Av ≈ −9.4 with phase inversion',
        },
      },
      {
        topic: 'Small-signal equivalent models',
        terms: ['controlled source', 'input resistance', 'output resistance', 'source resistance'],
        definition: 'A MOSFET model replaces the device with a controlled current source.',
        takeaway: 'The model turns device physics into circuit equations.',
        visual: 'mos-small-signal',
        formula: { eq: 'iin ≈ 0,  id = gm vgs', vars: [['Zin', 'very high at low frequency']] },
        numerical: {
          given: ['vgs = 10 mV', 'gm = 2 mS'],
          find: 'id',
          steps: ['id = 2e-3 × 0.01 = 20 μA'],
          result: 'id = 20 μA controlled source',
        },
      },
      {
        topic: 'Transconductance',
        terms: ['gm', 'slope', 'bias current', 'overdrive'],
        definition: 'Transconductance measures how strongly gate voltage controls drain current.',
        takeaway: 'Higher gm usually means higher gain.',
        visual: 'gm-slope',
        formula: { eq: 'gm = ∂ID / ∂VGS', vars: [['at Q', 'evaluated at bias']] },
        numerical: {
          given: ['ID doubles for +0.2 V on VGS around Q'],
          find: 'Rough gm',
          steps: ['ΔID / ΔVGS from measured slope', 'gm rises with √ID in square-law devices'],
          result: 'gm is the gain dial of MOSFET amps',
        },
      },
      {
        topic: 'Common-source amplifier',
        terms: ['CS stage', 'source resistance', 'bypass', 'phase inversion'],
        definition: 'The CS amplifier is the MOSFET voltage-gain workhorse.',
        takeaway: 'Source resistance improves stability but lowers gain.',
        visual: 'mos-cs',
        formula: { eq: 'Av ≈ −gm (RD ∥ RL)', vars: [['bypass', 'shorts RS for AC']] },
        numerical: {
          given: ['gm = 3 mS', 'RD = 3.3 kΩ', 'RS unbypassed = 330 Ω'],
          find: 'Degenerated Av',
          steps: ['Av ≈ −gm RD / (1 + gm RS)', '1 + gm RS = 1 + 0.99 ≈ 1.99', 'Av ≈ −3×3.3 / 1.99 ≈ −5'],
          result: 'Degeneration trades gain for linearity',
        },
      },
      {
        topic: 'Common-gate amplifier',
        terms: ['low Rin', 'current buffer', 'wideband', 'no inversion'],
        definition: 'The CG amplifier accepts current-like input with low input resistance.',
        takeaway: 'CG stages are useful in wideband interfaces.',
        visual: 'mos-cg',
        formula: { eq: 'Rin ≈ 1 / gm', vars: [['phase', 'non-inverting drain vs source input']] },
        numerical: {
          given: ['gm = 4 mS'],
          find: 'Rin',
          steps: ['Rin ≈ 250 Ω'],
          result: 'Low-Z input, wideband current buffer',
        },
      },
      {
        topic: 'Source follower',
        terms: ['common drain', 'buffer', 'high Rin', 'low Rout'],
        definition: 'The source follower provides near-unity gain and strong buffering.',
        takeaway: 'Use it when impedance matching matters more than voltage gain.',
        visual: 'mos-follower',
        formula: { eq: 'Av = gm RS / (1 + gm RS) < 1', vars: [['Rout', '≈ 1/gm']] },
        numerical: {
          given: ['gm = 5 mS', 'RS = 1 kΩ'],
          find: 'Av',
          steps: ['gm RS = 5', 'Av = 5 / 6 ≈ 0.83'],
          result: 'Av ≈ 0.83 buffer',
        },
      },
    ],
  },
  {
    n: 3,
    id: 'module-3',
    title: 'Negative Feedback, Oscillators, and 555 Timer',
    hours: 8,
    question: 'How can feedback stabilize an amplifier — or make it sing?',
    story: ['Feedback', 'VCVS', 'Barkhausen', 'RC/LC', 'Crystal', '555'],
    syllabus: [
      'Four feedback types / four types of negative feedback',
      'VCVS voltage gain',
      'Other VCVS equations',
      'ICVS amplifier',
      'VCIS amplifier',
      'ICIS amplifier',
      'No mathematical derivation',
      'Sinusoidal oscillator theory',
      'Wein-bridge oscillator',
      'RC phase-shift oscillator',
      'Colpitts oscillator',
      'Hartley oscillator',
      'Crystal oscillator',
      '555 timer monostable',
      '555 timer astable',
    ],
    formulas: [
      { eq: 'Af = A / (1 + Aβ)', mean: 'Closed-loop gain with negative feedback' },
      { eq: 'Barkhausen: |Aβ| ≥ 1, ∠Aβ = 0°', mean: 'Conditions for sustained oscillation' },
      { eq: 'T = 1.1 R C', mean: '555 monostable pulse width' },
      { eq: 'f ≈ 1.44 / ((RA + 2 RB) C)', mean: '555 astable frequency (typical form)' },
    ],
    units: [
      {
        topic: 'Four feedback types',
        terms: ['voltage sampling', 'current sampling', 'series mixing', 'shunt mixing'],
        definition: 'Feedback type depends on what is sampled and how it is mixed at input.',
        takeaway: 'Feedback changes gain, impedance, distortion, and bandwidth.',
        visual: 'feedback-four',
        formula: { eq: 'Topology = sample × mix', vars: [['VCVS', 'voltage-series'], ['ICIS', 'current-shunt']] },
        numerical: {
          given: ['Want stable voltage gain into a load'],
          find: 'Best topology family',
          steps: ['Sample output voltage', 'Series-mix at input', '→ VCVS'],
          result: 'Match topology to source/load',
        },
      },
      {
        topic: 'VCVS feedback amplifier',
        terms: ['voltage input', 'voltage output', 'closed-loop gain', 'gain stability'],
        definition: 'A VCVS amplifier uses voltage-series feedback for stable voltage gain.',
        takeaway: 'Closed-loop gain is less sensitive to device variation.',
        visual: 'vcvs',
        formula: { eq: 'Af ≈ 1 / β  (if Aβ ≫ 1)', vars: [['β', 'feedback factor']] },
        numerical: {
          given: ['A = 10 000', 'β = 0.1'],
          find: 'Af',
          steps: ['1 + Aβ = 1001', 'Af = 10000/1001 ≈ 10'],
          result: 'Af ≈ 1/β = 10',
        },
      },
      {
        topic: 'ICVS, VCIS, and ICIS amplifiers',
        terms: ['current input', 'voltage output', 'transresistance', 'transconductance'],
        definition: 'Feedback amplifiers can convert voltage/current inputs and outputs.',
        takeaway: 'The amplifier model must match the source and load.',
        visual: 'feedback-converters',
        formula: { eq: 'Choose V/I ports to match', vars: [['Rm', 'transresistance'], ['Gm', 'transconductance']] },
        numerical: {
          given: ['Photodiode current source → voltage needed'],
          find: 'Useful family',
          steps: ['Current in, voltage out → ICVS / transresistance'],
          result: 'Port type is the design choice',
        },
      },
      {
        topic: 'Oscillator theory',
        terms: ['positive feedback', 'loop gain', 'phase shift', 'Barkhausen'],
        definition: 'An oscillator sustains output without external signal when loop conditions are met.',
        takeaway: 'Magnitude and phase conditions decide oscillation.',
        visual: 'osc-build',
        formula: { eq: '|Aβ| = 1, ∠Aβ = 0°', vars: [['startup', '|Aβ| > 1 then limit']] },
        numerical: {
          given: ['Amplifier inverts; network must supply 180°'],
          find: 'Phase plan',
          steps: ['Total loop phase 360°/0°', 'Gain trims to unity after startup'],
          result: 'Noise → growth → sustained sine',
        },
      },
      {
        topic: 'Wein-bridge oscillator',
        terms: ['lead-lag network', 'low distortion', 'frequency selection', 'amplitude stabilization'],
        definition: 'A Wein-bridge oscillator uses an RC bridge to select sinusoidal frequency.',
        takeaway: 'It is a classic low-distortion sine-wave source.',
        visual: 'wein',
        formula: { eq: 'f = 1 / (2π R C)', vars: [['gain needed', '≥ 3']] },
        numerical: {
          given: ['R = 10 kΩ', 'C = 10 nF'],
          find: 'f',
          steps: ['f = 1 / (2π · 10k · 10n) ≈ 1.59 kHz'],
          result: 'f ≈ 1.59 kHz',
        },
      },
      {
        topic: 'RC phase-shift oscillator',
        terms: ['three RC sections', '180°', 'inverting amplifier', 'sine wave'],
        definition: 'RC sections create the needed phase shift for oscillation.',
        takeaway: 'Phase accumulation is the key idea.',
        visual: 'rc-phase',
        formula: { eq: 'f ≈ 1 / (2π R C √6)', vars: [['3 sections', '≈ 60° each at f0']] },
        numerical: {
          given: ['R = 4.7 kΩ', 'C = 10 nF'],
          find: 'f approx',
          steps: ['√6 ≈ 2.45', 'f ≈ 1/(2π·4.7k·10n·2.45) ≈ 1.4 kHz'],
          result: 'f ≈ 1.4 kHz',
        },
      },
      {
        topic: 'Colpitts oscillator',
        terms: ['capacitive divider', 'LC tank', 'feedback fraction', 'RF'],
        definition: 'Colpitts uses a split capacitor tank for frequency selection and feedback.',
        takeaway: 'LC oscillators suit higher-frequency sine generation.',
        visual: 'colpitts',
        formula: { eq: 'f ≈ 1 / (2π √(L Ceq))', vars: [['Ceq', 'C1 C2 / (C1 + C2)']] },
        numerical: {
          given: ['L = 50 μH', 'C1 = C2 = 200 pF'],
          find: 'f',
          steps: ['Ceq = 100 pF', 'f ≈ 2.25 MHz'],
          result: 'f ≈ 2.25 MHz',
        },
      },
      {
        topic: 'Hartley oscillator',
        terms: ['inductive divider', 'LC tank', 'feedback', 'tuning'],
        definition: 'Hartley uses an inductive divider in the resonant tank.',
        takeaway: 'The tank stores and returns energy each cycle.',
        visual: 'hartley',
        formula: { eq: 'f ≈ 1 / (2π √((L1+L2) C))', vars: [['tap', 'sets feedback']] },
        numerical: {
          given: ['L1 + L2 = 100 μH', 'C = 100 pF'],
          find: 'f',
          steps: ['f ≈ 1.59 MHz'],
          result: 'f ≈ 1.59 MHz',
        },
      },
      {
        topic: 'Crystal oscillator',
        terms: ['piezoelectric crystal', 'high Q', 'frequency stability', 'clock'],
        definition: 'A crystal oscillator uses mechanical resonance for stable frequency.',
        takeaway: 'High Q gives excellent frequency stability.',
        visual: 'crystal',
        formula: { eq: 'f set by crystal resonance', vars: [['Q', 'very high']] },
        numerical: {
          given: ['32.768 kHz watch crystal'],
          find: 'Use case',
          steps: ['Mechanical resonance locks frequency', 'Drift far below RC/LC'],
          result: 'Precision clocks and references',
        },
      },
      {
        topic: '555 timer operation',
        terms: ['monostable', 'astable', 'threshold', 'trigger'],
        definition: 'The 555 timer uses comparators and an SR latch to generate timing waveforms.',
        takeaway: 'Monostable makes one pulse; astable makes a clock.',
        visual: 'timer555',
        formula: { eq: 'T = 1.1 R C (mono)', vars: [['astable', 'charge/discharge via RA, RB']] },
        numerical: {
          given: ['R = 10 kΩ', 'C = 100 μF', 'monostable'],
          find: 'Pulse width',
          steps: ['T = 1.1 × 10k × 100μ = 1.1 s'],
          result: 'T = 1.1 s one-shot',
        },
      },
    ],
  },
  {
    n: 4,
    id: 'module-4',
    title: 'Power Amplifiers and Active Filters',
    hours: 8,
    question: 'How do we deliver power to a load — and sculpt frequency content?',
    story: ['Power', 'Load line', 'Class A/B/C', 'Filters', 'Q', 'MFB'],
    syllabus: [
      'Amplifier terms',
      'Two load lines',
      'Class A operation',
      'Class B operation',
      'Class B push-pull emitter follower',
      'Class C operation',
      'Active filters: ideal responses',
      'First-order stages',
      'VCVS unity-gain second-order low-pass filters',
      'VCVS equal-component low-pass filters',
      'VCVS high-pass filters',
      'MFB bandpass filters',
      'Bandstop filters',
    ],
    formulas: [
      { eq: 'η = Pout / Pdc', mean: 'Efficiency of a power stage' },
      { eq: 'Class A ≤ 50% (ideal), Class B ≤ 78.5%', mean: 'Conduction angle vs efficiency' },
      { eq: 'First-order slope ≈ 20 dB/decade', mean: 'Roll-off of a single pole' },
      { eq: 'Q = f0 / BW', mean: 'Selectivity of a resonant / bandpass response' },
    ],
    units: [
      {
        topic: 'Amplifier terms',
        terms: ['efficiency', 'power gain', 'load', 'distortion'],
        definition: 'Power amplifiers are designed to deliver energy to a load efficiently.',
        takeaway: 'Output power and efficiency dominate the design.',
        visual: 'power-terms',
        formula: { eq: 'Ap = Pout / Pin', vars: [['η', 'Pout/Pdc']] },
        numerical: {
          given: ['Pout = 5 W', 'Pdc = 12 W'],
          find: 'η',
          steps: ['η = 5/12 ≈ 42%'],
          result: 'η ≈ 42%',
        },
      },
      {
        topic: 'Two load lines',
        terms: ['DC load line', 'AC load line', 'Q point', 'signal swing'],
        definition: 'DC and AC load lines describe bias and signal operation separately.',
        takeaway: 'Large-signal stages must respect both limits.',
        visual: 'two-loadlines',
        formula: { eq: 'DC: VCE = VCC − IC RC', vars: [['AC', 'uses rL = RC ∥ RL']] },
        numerical: {
          given: ['VCC = 20 V', 'RC = 1 kΩ', 'RL = 1 kΩ'],
          find: 'AC load resistance',
          steps: ['rL = 500 Ω', 'AC swing steeper than DC line'],
          result: 'Design Q for both lines',
        },
      },
      {
        topic: 'Class A operation',
        terms: ['360° conduction', 'linear', 'low efficiency', 'heat'],
        definition: 'Class A conducts for the full cycle and gives high linearity.',
        takeaway: 'Linearity is bought with poor efficiency.',
        visual: 'class-a',
        formula: { eq: 'Conduction = 360°', vars: [['ηmax', '≤ 50% ideal']] },
        numerical: {
          given: ['Quiescent IC high even with no signal'],
          find: 'Efficiency implication',
          steps: ['DC power always drawn', 'Heat in device'],
          result: 'Best fidelity, worst η',
        },
      },
      {
        topic: 'Class B operation',
        terms: ['180° conduction', 'crossover', 'efficiency', 'complementary'],
        definition: 'Class B improves efficiency by splitting the waveform between devices.',
        takeaway: 'Crossover distortion must be controlled.',
        visual: 'class-b',
        formula: { eq: 'Conduction ≈ 180° each', vars: [['ηmax', '≈ 78.5%']] },
        numerical: {
          given: ['No idle current at Q'],
          find: 'Tradeoff',
          steps: ['High η', 'Crossover notch near zero'],
          result: 'Need bias tweak → AB in practice',
        },
      },
      {
        topic: 'Class B push-pull emitter follower',
        terms: ['push-pull', 'emitter follower', 'load drive', 'crossover'],
        definition: 'Push-pull followers provide current drive for low-resistance loads.',
        takeaway: 'Complementary action reconstructs the waveform.',
        visual: 'push-pull',
        formula: { eq: 'NPN pushes, PNP pulls', vars: [['load', 'speaker / low Z']] },
        numerical: {
          given: ['±12 V rails', '8 Ω load'],
          find: 'Role',
          steps: ['Each half-cycle one device on', 'Followers supply current'],
          result: 'Power buffer for the load',
        },
      },
      {
        topic: 'Class C operation',
        terms: ['<180° conduction', 'tank circuit', 'high efficiency', 'RF'],
        definition: 'Class C conducts for a small part of the cycle and uses a resonant load.',
        takeaway: 'It is efficient but suited mainly to tuned RF applications.',
        visual: 'class-c',
        formula: { eq: 'Tank restores sine', vars: [['η', 'can be very high']] },
        numerical: {
          given: ['Conduction pulses into LC tank'],
          find: 'Output shape',
          steps: ['Tank rings at f0', 'Harmonics filtered'],
          result: 'RF power, not audio fidelity',
        },
      },
      {
        topic: 'Active filters: ideal responses',
        terms: ['low-pass', 'high-pass', 'bandpass', 'bandstop'],
        definition: 'Active filters shape frequency content by passing some bands and rejecting others.',
        takeaway: 'A response plot is the easiest way to teach filter behavior.',
        visual: 'filter-ideal',
        formula: { eq: 'H(jω) selects band', vars: [['fc', 'cutoff'], ['f0', 'center']] },
        numerical: {
          given: ['Want to remove 50 Hz hum, keep voice'],
          find: 'Filter family',
          steps: ['Notch / bandstop at 50 Hz'],
          result: 'Match response to the problem',
        },
      },
      {
        topic: 'First-order active stages',
        terms: ['cutoff frequency', 'roll-off', 'op-amp buffer', 'RC network'],
        definition: 'First-order filters give a simple 20 dB/decade slope.',
        takeaway: 'Cutoff frequency sets the transition point.',
        visual: 'filter-first',
        formula: { eq: 'fc = 1 / (2π R C)', vars: [['slope', '−20 dB/dec (LP)']] },
        numerical: {
          given: ['R = 10 kΩ', 'C = 15 nF'],
          find: 'fc',
          steps: ['fc ≈ 1.06 kHz'],
          result: 'fc ≈ 1.06 kHz',
        },
      },
      {
        topic: 'VCVS second-order filters',
        terms: ['unity gain', 'equal component', 'Q factor', 'damping'],
        definition: 'Second-order VCVS filters sharpen the transition and shape Q.',
        takeaway: 'Component choices set cutoff and peaking.',
        visual: 'filter-vcvs',
        formula: { eq: '2nd order → 40 dB/decade', vars: [['Q', 'damping / peaking']] },
        numerical: {
          given: ['Equal-component LP, chosen Q'],
          find: 'Design idea',
          steps: ['Set R,C for fc', 'Set gain/resistors for Q'],
          result: 'Steeper skirts than first-order',
        },
      },
      {
        topic: 'MFB bandpass and bandstop filters',
        terms: ['multiple feedback', 'center frequency', 'bandwidth', 'notch'],
        definition: 'MFB filters use feedback paths to select or reject a band.',
        takeaway: 'Bandpass selects; bandstop removes.',
        visual: 'filter-mfb',
        formula: { eq: 'Q = f0 / BW', vars: [['MFB', 'multiple feedback topology']] },
        numerical: {
          given: ['f0 = 1 kHz', 'BW = 100 Hz'],
          find: 'Q',
          steps: ['Q = 10'],
          result: 'Q = 10 selective bandpass',
        },
      },
    ],
  },
  {
    n: 5,
    id: 'module-5',
    title: 'Linear and Nonlinear Op-Amp Applications and DC Regulators',
    hours: 8,
    question: 'How do linear ICs turn bits, thresholds and rails into clean analog behaviour?',
    story: ['DAC', 'ADC', 'Precision', 'Compare', 'Schmitt', 'Regulate'],
    syllabus: [
      'Weighted resistor DAC',
      'R-2R DAC',
      'Analog to digital conversion',
      'Digital ramp ADC',
      'Successive approximation ADC',
      'Signal processing circuits',
      'Precision rectifier: saturating and non-saturating precision HWR',
      'Precision FWR using HWR and summing circuit',
      'Zero crossing detector',
      'Inverting Schmitt trigger',
      'Non-inverting Schmitt trigger',
      'DC voltage regulator introduction',
      'Voltage regulator basics',
    ],
    formulas: [
      { eq: 'VDAC ∝ digital code', mean: 'DAC maps bits to analog level' },
      { eq: 'Resolution = FSR / 2ⁿ', mean: 'ADC/DAC step size for n bits' },
      { eq: 'VUT / VLT hysteresis', mean: 'Schmitt thresholds' },
      { eq: 'Line & load regulation', mean: 'Regulator quality metrics' },
    ],
    units: [
      {
        topic: 'Weighted resistor DAC',
        terms: ['binary weights', 'summing amplifier', 'resolution', 'output voltage'],
        definition: 'A weighted resistor DAC converts binary input into proportional analog voltage.',
        takeaway: 'Accurate resistor ratios are critical.',
        visual: 'dac-weighted',
        formula: { eq: 'Vout = −RF (b1/R + b2/2R + b3/4R + …) Vref', vars: [['bi', 'bit currents']] },
        numerical: {
          given: ['4-bit, Vref = 8 V, ideal weights'],
          find: 'LSB size',
          steps: ['2⁴ = 16 levels', 'LSB = 8/16 = 0.5 V'],
          result: 'LSB = 0.5 V',
        },
      },
      {
        topic: 'R-2R DAC',
        terms: ['ladder network', 'two resistor values', 'scalability', 'binary conversion'],
        definition: 'The R-2R ladder DAC uses only two resistor values for binary weighting.',
        takeaway: 'It is easier to scale than weighted resistors.',
        visual: 'dac-r2r',
        formula: { eq: 'Only R and 2R needed', vars: [['ladder', 'binary division']] },
        numerical: {
          given: ['Same 4-bit FSR'],
          find: 'Practical advantage',
          steps: ['Matched R, 2R easier than 8R, 16R…', 'Scales to more bits'],
          result: 'Preferred IC ladder topology',
        },
      },
      {
        topic: 'Analog to digital conversion',
        terms: ['sampling', 'quantization', 'encoding', 'resolution'],
        definition: 'ADC converts an analog input into a digital code.',
        takeaway: 'Resolution and conversion time are key tradeoffs.',
        visual: 'adc-idea',
        formula: { eq: 'Δ = FSR / 2ⁿ', vars: [['n', 'bits']] },
        numerical: {
          given: ['0–5 V', '8-bit'],
          find: 'Step size',
          steps: ['256 levels', 'Δ ≈ 19.5 mV'],
          result: 'Δ ≈ 19.5 mV',
        },
      },
      {
        topic: 'Digital ramp ADC',
        terms: ['counter', 'DAC', 'comparator', 'ramp'],
        definition: 'Digital ramp ADC counts upward until DAC output matches input.',
        takeaway: 'Simple design, but conversion can be slow.',
        visual: 'adc-ramp',
        formula: { eq: 'Count until VDAC ≥ Vin', vars: [['worst case', '2ⁿ clocks']] },
        numerical: {
          given: ['8-bit, 1 MHz clock'],
          find: 'Worst conversion time',
          steps: ['256 μs worst case'],
          result: 'Slow but simple',
        },
      },
      {
        topic: 'Successive approximation ADC',
        terms: ['SAR', 'binary search', 'sample-hold', 'comparator'],
        definition: 'SAR ADC tests bits from MSB to LSB using a binary-search process.',
        takeaway: 'SAR balances speed and circuit complexity.',
        visual: 'adc-sar',
        formula: { eq: 'n bit tests → n clocks', vars: [['S/H', 'holds Vin']] },
        numerical: {
          given: ['12-bit SAR', '1 MHz bit clock'],
          find: 'Conversion time',
          steps: ['≈ 12 μs'],
          result: 'Much faster than ramp for same n',
        },
      },
      {
        topic: 'Precision rectifier circuits',
        terms: ['op-amp diode', 'half-wave', 'full-wave', 'small signals'],
        definition: 'Precision rectifiers overcome diode drop using op-amp feedback.',
        takeaway: 'They rectify signals too small for ordinary diodes.',
        visual: 'precision-rect',
        formula: { eq: 'Effective drop ≈ 0 (closed loop)', vars: [['HWR/FWR', 'precision']] },
        numerical: {
          given: ['vin = 50 mV sine', 'silicon diode 0.7 V'],
          find: 'Why precision?',
          steps: ['Ordinary diode never turns on', 'Op-amp forces conduction path'],
          result: 'mV-level rectification',
        },
      },
      {
        topic: 'Signal processing circuits',
        terms: ['summing', 'scaling', 'rectifying', 'conditioning'],
        definition: 'Linear op-amp circuits shape signals before measurement or control.',
        takeaway: 'Op-amps are building blocks for analog computation.',
        visual: 'signal-process',
        formula: { eq: 'Vout = −(Va + Vb + …) scaled', vars: [['summing', 'inverting node']] },
        numerical: {
          given: ['Two 1 V inputs, RF = Rin'],
          find: 'Summing output',
          steps: ['Vout = −2 V'],
          result: 'Analog addition',
        },
      },
      {
        topic: 'Zero crossing detector',
        terms: ['comparator', 'reference zero', 'polarity', 'switching'],
        definition: 'A zero crossing detector changes output when input crosses zero.',
        takeaway: 'It turns analog polarity into a digital-like event.',
        visual: 'zcd',
        formula: { eq: 'Vout → ±Vsat when Vin crosses 0', vars: [['open loop', 'comparator']] },
        numerical: {
          given: ['Sine input'],
          find: 'Output shape',
          steps: ['Square-like ±sat', 'Edges at zero crossings'],
          result: 'Polarity square wave',
        },
      },
      {
        topic: 'Schmitt trigger circuits',
        terms: ['hysteresis', 'upper threshold', 'lower threshold', 'noise immunity'],
        definition: 'Schmitt triggers use positive feedback to create two switching thresholds.',
        takeaway: 'Hysteresis prevents noisy chatter.',
        visual: 'schmitt',
        formula: { eq: 'VUT ≠ VLT', vars: [['β', 'positive feedback']] },
        numerical: {
          given: ['VUT = 2 V', 'VLT = −2 V'],
          find: 'Hysteresis width',
          steps: ['Width = 4 V'],
          result: 'Noise inside ±2 V ignored',
        },
      },
      {
        topic: 'DC voltage regulators',
        terms: ['line regulation', 'load regulation', 'reference', 'pass element'],
        definition: 'Voltage regulators hold output voltage nearly constant under input/load changes.',
        takeaway: 'Regulation is the final link between supply and reliable circuits.',
        visual: 'regulator',
        formula: { eq: 'Vout ≈ Vref × feedback ratio', vars: [['line/load', 'quality metrics']] },
        numerical: {
          given: ['Vin 15→18 V, Vout shift 10 mV'],
          find: 'Line regulation idea',
          steps: ['Small ΔVout vs ΔVin'],
          result: 'Good line regulation',
        },
      },
    ],
  },
]

export function getAelicModule(n) {
  return AELIC_MODULES.find((m) => m.n === n)
}
