function lab(title, aim, principle, tools, setup, procedure, observation, result, error, viva, visual, extra = {}) {
  return { title, domain: 'lab', visual, aim, principle, tools, setup, procedure, observation, result, error, viva, ...extra }
}

export const electricalLabs = [
  lab('Verification of Ohm’s law and Kirchhoff’s laws', 'Verify V = IR and KCL/KVL on a simple board.', 'Ohm: voltage across a resistor is current times resistance. KCL conserves current at a node; KVL conserves voltage around a loop.', 'DC source, resistors, voltmeter, ammeter, breadboard/wires', 'Series resistor for Ohm; node with two branches for KCL; loop for KVL.', ['Identify polarity', 'Connect meters in correct mode', 'Vary voltage or resistance', 'Tabulate V, I', 'Check V/I and node/loop sums'], 'V/I is nearly constant; node currents add; loop voltages sum near zero.', 'Ohm and Kirchhoff hold within meter and contact error.', 'Reversing the ammeter or treating a voltmeter as a series element.', 'Why must the ammeter be in series?', 'circuit'),
  lab('Low resistance by voltmeter–ammeter method', 'Measure a low resistance from V and I.', 'R = V/I. Contact and meter burden matter for low R.', 'Low-value resistor or shunt, high-current capable source, V and A', 'Four-terminal idea if taught: sense voltage at the specimen, not at the supply leads.', ['Connect source', 'Place ammeter in series', 'Place voltmeter across the unknown', 'Read pair', 'Compute R'], 'R computed from several (V,I) pairs.', 'Unknown low R with stated unit (Ω).', 'Including lead resistance in V for a milliohm specimen.', 'Why is a single pair less trustworthy than a set?', 'circuit'),
  lab('Earth resistance by three-electrode method', 'Measure earth resistance with spike electrodes.', 'Fall-of-potential / 3-electrode arrangement separates current electrodes from the potential probe.', 'Earth tester or equivalent, three electrodes, connecting leads, mallet', 'Drive electrodes at specified spacing in soil; keep probes in a line.', ['Drive spikes', 'Connect C1, P1, P2 as marked', 'Take reading', 'Repeat after watering/spacing if required', 'Record Ω'], 'Earth resistance in ohms for the site.', 'Site earth resistance (typical tens of ohms, location-dependent).', 'Using a phase-neutral socket and calling it earth resistance.', 'Why spacing of electrodes changes the reading?', 'circuit'),
  lab('R, L, Z, P and pf in a single-phase AC circuit', 'Measure impedance quantities with V, A and wattmeter.', 'Z = V/I, P = wattmeter, pf = P/(VI), XL from Z and R.', 'AC supply, inductive load, V, A, wattmeter', 'Wattmeter current coil in series, pressure coil across the load.', ['Identify coils', 'Connect load', 'Read V, I, P', 'Compute Z, pf, XL', 'Comment lag'], 'Tabulated V, I, P, Z, pf.', 'Lagging pf for the inductive load.', 'Using DC formulae on AC meters without pf.', 'Which coil of the wattmeter is series?', 'circuit'),
  lab('Three-phase power by two-wattmeter method', 'Measure three-phase power of a star and a delta inductive load.', 'P = W1 + W2; pf from the two wattmeters for a balanced load.', '3-ph supply, two wattmeters, star/delta load', 'Wattmeters in two lines as in the standard 2-wattmeter diagram.', ['Connect star', 'Read W1, W2', 'Repeat delta', 'Compute P and pf', 'Compare line currents'], 'W1, W2 and total P for both connections.', 'Total power and pf for star and delta cases.', 'Adding line and phase voltages in the same formula.', 'What does a negative wattmeter reading mean at low pf?', 'circuit'),
  lab('Two-way and three-way control of a load', 'Wire 2-way (and 3-way) switching of a lamp.', 'Two-way switching reroutes the live, not the neutral.', 'Lamp, two-way switches, optional intermediate, wiring board', 'Supply live into first switch; travellers; switched live to load; neutral to load.', ['Plan live path', 'Wire travellers', 'Test both switch positions', 'Confirm lamp states', 'Never switch only neutral'], 'Truth of switch combinations vs lamp on/off.', 'Lamp controlled from two (or three) locations.', 'Using earth as a spare live.', 'Why must the switched conductor be live?', 'circuit'),
  lab('Fuse melting time versus length', 'Relate fuse-element length to time-to-open under short-circuit.', 'I²R heating melts a defined element. Length changes resistance and heat mass.', 'Fuse wire samples, source with protection, stopwatch, documentation sheet', 'Controlled short through the sample; never bypass lab protection.', ['Cut measured lengths', 'Apply the documented short', 'Time the open', 'Tabulate', 'Conclude trend'], 'Time increases or decreases with length as observed.', 'Documented trend and safety conclusion.', 'Removing the lab’s protective device to “see a bigger spark”.', 'Why is this an open-ended documentation experiment?', 'circuit'),
  lab('Troubleshooting a simple DC circuit', 'Find loose, open or short faults.', 'A fault is a topology change. Measure, do not guess.', 'Simple DC board with planted faults, V/A', 'Visual check, then voltage walk from source to load.', ['Inspect connections', 'Measure from source', 'Isolate branch', 'Name the fault class', 'Repair and re-test'], 'Fault class and evidence.', 'Circuit restored; cause recorded.', 'Replacing every component before measuring.', 'Open vs short: which voltage pattern?', 'circuit'),
  lab('Line, neutral and earth voltages on a 3-pin socket', 'Compare healthy vs unhealthy socket voltages.', 'L–N is ~supply; L–E similar; N–E should be small. Reversed or floating earth is unsafe.', '3-pin tester or meters used as instructed, known good and faulty demonstration sockets', 'Do not touch exposed metal. Follow staff procedure.', ['Identify L, N, E', 'Measure three pairs', 'Compare with healthy pattern', 'State allowable earth voltage idea', 'Conclude wiring fault'], 'Three voltages, two socket states.', 'Healthy vs reversed/open-earth diagnosis.', 'Assuming N–E = 0 always without measuring.', 'Why is a large N–E voltage a warning?', 'circuit'),
  lab('Obtain 3 V from a 12 V battery to charge a mobile (lab constraint)', 'Design a divider or regulator path that yields 3 V with stated ratings.', 'A divider shares voltage; ratings must survive the current. A regulator is cleaner if the syllabus kit allows it.', '12 V battery, resistors or recommended regulator, voltmeter, dummy/mobile load as permitted', 'Compute current; check resistor wattage; never short the battery.', ['Specify current', 'Choose network', 'Build', 'Measure 3 V on load', 'List ratings'], 'Vout ≈ 3 V on the intended load.', 'Circuit diagram, ratings and measured 3 V.', 'Two equal resistors with no current calculation (not 3 V from 12 V).', 'Why does unloaded divider voltage mislead?', 'circuit'),
  lab('Single-phase power with three ammeters and a standard resistance', 'Measure AC power without a wattmeter, using three ammeters.', 'Ammeter-around-a-known-R method reconstructs power from currents (as in the lab sheet).', 'Three ammeters, standard R, inductive load, AC supply', 'Follow the exact three-ammeter topology in the instruction sheet.', ['Wire the three-ammeter network', 'Read I1, I2, I3', 'Apply the lab formula', 'Obtain P', 'Comment pf if asked'], 'Three currents and computed P.', 'Power of the inductive load by the 3-ammeter method.', 'Treating the three ammeters as if they were all in series with the load.', 'Which current is through the standard R?', 'circuit'),
  lab('Single-phase power with three voltmeters and a standard resistance', 'Measure AC power using three voltmeters.', 'Three-voltmeter method uses voltages around a known R to find P.', 'Three voltmeters, standard R, inductive load', 'Match the lab’s voltage-network diagram exactly.', ['Connect', 'Read V1, V2, V3', 'Use the prescribed formula', 'Find P', 'Compare with expected order'], 'Three voltages and computed P.', 'Power by the 3-voltmeter method.', 'Using DC (V²/R) on one meter as if that were AC load power.', 'Why is a standard R required?', 'circuit'),
]

export const eceLabs = [
  lab('Half-wave and full-wave rectifiers with and without filter', 'Measure ripple, regulation and compare HWR/FWR.', 'Diode conducts one polarity. Capacitor filter reduces ripple. Full-wave uses both halves.', 'Transformer, diodes, load, capacitor, CRO/DMM', 'Build HWR then FWR; add C; keep polarity marks.', ['Sketch path for each half-cycle', 'Measure Vdc and ripple', 'Add filter', 'Compare', 'Compute regulation'], 'Waveforms and Vdc/ripple table.', 'FWR has higher average and lower ripple than HWR; filter improves both.', 'Calling the capacitor a “DC battery” without ripple language.', 'Why does C reduce ripple?', 'rectifier'),
  lab('Bridge rectifier with and without filter', 'Same metrics on a four-diode bridge.', 'Bridge uses both half-cycles without a centre tap.', 'Four diodes, transformer, load, C, meters/CRO', 'Check diode orientation; never reverse the filter capacitor.', ['Wire bridge', 'Observe polarity on load', 'Measure with/without C', 'Ripple and regulation', 'Compare with centre-tap if asked'], 'Bridge Vdc, ripple, regulation.', 'Bridge DC with stated ripple factor.', 'One reversed diode that opens a half-cycle.', 'Advantage of bridge vs centre-tap at this level?', 'rectifier'),
  lab('BJT CE input and output characteristics', 'Plot IB–VBE and IC–VCE families.', 'CE: small IB controls IC in the active region. Load line comes later in theory; here we record curves.', 'BJT, two supplies, meters, rheostats as in the board', 'Identify B, C, E. Observe VCE(max).', ['Set IB steps', 'Sweep VCE', 'Record IC', 'Plot', 'Mark active/sat/cutoff roughly'], 'Characteristic families.', 'CE curves with labelled axes.', 'Swapping C and E and forcing current.', 'What is the role of IB on the output family?', 'circuit'),
  lab('MOSFET CS transfer and drain characteristics', 'Plot ID–VGS and ID–VDS.', 'Enhancement MOSFET needs VGS above threshold to form a channel.', 'MOSFET, supplies, meters', 'Respect VGS(max). Identify G, D, S.', ['Vary VGS', 'Record ID', 'Sweep VDS at fixed VGS', 'Plot transfer and drain', 'Comment threshold'], 'Transfer and drain curves.', 'CS MOSFET characteristics.', 'Treating MOSFET like a BJT with a base current.', 'Why is gate current ideally negligible?', 'circuit'),
  lab('Op-amp inverting and non-inverting gain', 'Measure closed-loop gain of both configs.', 'Inverting Av = −Rf/Rin. Non-inverting Av = 1 + Rf/Rg.', '741 or kit op-amp, resistors, signal, CRO/DMM', 'Dual supply if required; never leave inputs floating.', ['Build inverting', 'Measure vin, vout', 'Repeat non-inverting', 'Compare sign and |Av|', 'Note saturation'], 'Gain table for both.', 'Measured gains close to resistor ratios until clipping.', 'Expecting +Rf/Rin for the inverting circuit.', 'Why is the inverting input a virtual ground in closed loop?', 'circuit'),
  lab('OR, AND, NOT, NAND, NOR truth tables', 'Verify gate truth tables; NAND/NOR as universal.', 'A gate is a 0/1 map. Universal gates can build the others.', 'Logic trainer or ICs, LEDs, switches', 'Use the kit’s logic levels; do not apply analog sine as if it were a bit.', ['Set inputs', 'Read LED/output', 'Fill table', 'Build NOT from NAND if asked', 'Compare'], 'Completed truth tables.', 'Tables match the gate definitions.', 'Forcing analog waveform language onto bits.', 'Why is NAND universal?', 'gates'),
  lab('Clipper and clamper transfer characteristics', 'Obtain desired clip/clamp transfer.', 'Clipper limits amplitude; clamper shifts DC level using C and diode.', 'Diodes, resistors, C, signal, CRO', 'DC couple vs AC couple as instructed.', ['Build clipper', 'Sketch vin/vout', 'Build clamper', 'Note DC shift', 'Draw transfer'], 'CRO captures and transfer sketch.', 'Clipping level and clamp shift as designed.', 'Swapping clipper and clamper names.', 'What component stores the clamp’s DC?', 'circuit'),
  lab('Single-stage BJT amplifier gain and bandwidth', 'Measure midband gain and bandwidth of a CE stage.', 'Gain is vout/vin. Bandwidth is the frequency span between half-power points.', 'BJT amplifier board, signal generator, CRO', 'Small-signal input; avoid saturation.', ['Set bias', 'Inject small vin', 'Measure Av at midband', 'Sweep frequency', 'Find fL, fH'], 'Av, fL, fH.', 'Gain and BW meeting the sheet’s intent.', 'Driving the amplifier into clipping and calling it gain.', 'What is a half-power frequency?', 'circuit'),
  lab('Op-amp voltage follower and weighted summer', 'Test buffer and analog sum.', 'Follower Av = 1, high Zin. Summer weights inputs by resistor ratios.', 'Op-amp, resistors, two sources, CRO', 'Tie unused inputs as required by the kit.', ['Build follower', 'Confirm vout ≈ vin', 'Build summer', 'Check weighted sum', 'Watch saturation'], 'Follower and summer waveforms.', 'Buffer and weighted sum verified.', 'Loading a source with a low-Z inverting input when a follower was specified.', 'Why buffer before a summer?', 'circuit'),
  lab('Op-amp integrator and differentiator', 'Waveform analysis of ∫ and d/dt circuits.', 'Integrator: capacitor feedback. Differentiator: capacitor input. Frequency and amplitude limits apply.', 'Op-amp, R, C, square/sine source, CRO', 'Start with recommended f so the op-amp is not in slew chaos.', ['Build integrator', 'Square → triangle (idealised)', 'Build differentiator', 'Square → spikes', 'Record'], 'Input/output waveform pairs.', 'Integrator and differentiator behaviour as designed.', 'Ignoring DC offset that walks an integrator into the rail.', 'Why must practical integrators include a DC path?', 'circuit'),
  lab('Amplitude modulation with discrete components', 'Generate AM for given specs.', 'Carrier amplitude varies with the message. m = Vm/Vc.', 'RF/audio sources as in kit, discrete modulator, CRO', 'Keep carrier >> message frequency.', ['Set fc, fm', 'Set amplitudes for m', 'Observe envelope', 'Estimate m', 'Note overmodulation'], 'AM envelope on CRO.', 'AM waveform with estimated modulation index.', 'Showing FM (changing zero-crossings) and labelling AM.', 'What happens if m > 1?', 'circuit'),
  lab('Half adder, full adder and subtractor with gates', 'Realise adders/subtractor; verify truth tables.', 'Half adder: Sum XOR, Carry AND. Full adder adds Cin. Subtractor uses similar XOR logic with borrow.', 'Gate ICs or trainer', 'Build bit-wise; check all input combinations.', ['Build HA', 'Extend to FA', 'Build subtractor as specified', 'Fill tables', 'Show one multi-bit idea if asked'], 'Truth tables for HA/FA/subtractor.', 'Logic matches the Boolean definition.', 'Leaving Cin unconnected and calling it a full adder.', 'Why does FA need three inputs?', 'gates'),
]
