function m(title, domain, visual, topics, why, principle, scenario, poor, good, example, mistake, practice, extras = {}) {
  return { title, domain, visual, topics, why, principle, scenario, poor, good, example, mistake, practice, ...extras }
}

export const theoryModules = {
  engComm: m(
    'Communication Skills: Process, Verbal and Non-Verbal Channels',
    'human', 'channel',
    ['Communication process', 'Verbal and non-verbal', 'Proxemics and chronemics', 'Barriers', 'Parts of speech', 'Sentence structure', 'Phonemes and intonation'],
    'A message fails when the channel, body, or timing contradicts the words.',
    'Sender encodes; channel carries; receiver decodes; feedback closes the loop. Noise is anything that distorts meaning.',
    { situation: 'A first-year student asks a lab instructor for a component.', issue: 'The request is mumbled, with no eye contact, while standing too close.', analysis: 'Verbal content is incomplete; proxemics and volume become the real message.', response: 'State the component, quantity and why, at a polite distance, then confirm.', learning: 'Clarity is process, not volume.' },
    'Give me that thing, sir, you know.',
    'Sir, I need two 1 kΩ resistors for the Ohm’s law board. May I take them from tray B?',
    ['Identify the barrier in: a noisy workshop + a whispered safety instruction.', 'channel noise + low volume', 'the instruction never arrives intact'],
    'Calling body language “optional extra” hides proxemics, chronemics and eye contact, which often carry the real meaning.',
    'Name sender, message, channel, receiver and one barrier in a campus announcement.',
  ),
  engInter: m(
    'Interpersonal Skills: Role Play, Group Discussion and Presentation',
    'human', 'channel',
    ['Workplace role play', 'PEP / self-introduction', 'Group discussion and debate', 'Technical presentation', 'Skimming and scanning', 'Sentence patterns', 'Idioms'],
    'Interpersonal skill is visible in turn-taking, not in a slogan about confidence.',
    'A group discussion is listening plus contribution. A presentation is structure plus evidence. Role play is tone matched to context.',
    { situation: 'Four students discuss “smart campus energy”.', issue: 'One speaker never yields; two stay silent.', analysis: 'Turn-taking failed; content quality cannot be heard.', response: 'Chair invites the silent members; speakers keep turns short.', learning: 'GD marks listening as well as speaking.' },
    'I will talk the whole time so we win the GD.',
    'I will make one clear point, quote one example, and invite the next speaker.',
    ['Rewrite “break the ice” in a first meeting.', 'idiom for starting talk', 'begin with a short introduction so others can join'],
    'A technical presentation that only lists slides is not a talk. Structure, example and a check with the audience are required.',
    'Write a 40-second self-introduction: name, branch, one skill, one goal.',
  ),
  engEmploy: m(
    'English for Employability: Letters, Email, Tense and Paragraph',
    'human', 'channel',
    ['Enquiry, order and complaint letters', 'Tenses, reported speech, voice', 'Email etiquette', 'Paragraph types', 'Blog writing', 'Proofreading', 'Questions and tags'],
    'Workplace English is a document that a stranger can act on.',
    'A formal email has subject, greeting, purpose in the first line, action requested, polite close. Tense must match the time of the event.',
    { situation: 'A student emails a company about internship dates.', issue: 'Subject is “hello”; body is one long unpunctuated line.', analysis: 'The reader cannot see purpose or dates.', response: 'Subject names the internship; body has purpose, dates, attachment.', learning: 'Etiquette is information design.' },
    'Subject: hi\npls give intern i am student',
    'Subject: Internship enquiry — First Year ECE, June 2026\nDear Sir/Madam,\nI am a first-year ECE student at VVIET seeking a June internship. Please find my résumé attached.\nRegards, …',
    ['Change to reported speech: “Submit the report today,” said the mentor.', 'command to reported', 'The mentor told us to submit the report that day.'],
    'A complaint letter that only vents anger without order number, date and requested action cannot be processed.',
    'Write a three-line enquiry email asking for a quotation for 20 lab kits.',
  ),
  engDigital: m(
    'English in the Digital World: Netiquette and Academic Integrity',
    'human', 'channel',
    ['Digital platforms', 'Netiquette', 'Academic integrity', 'Online collaboration', 'Responsible posting', 'Citation of digital sources'],
    'A post or a copied paragraph still has a reader and an author.',
    'Netiquette is the same communication process on a digital channel. Academic integrity requires naming the source of words and ideas.',
    { situation: 'A group WhatsApp dump of a classmate’s mistake goes viral in the class.', issue: 'Humour is used as a channel for humiliation.', analysis: 'Digital permanence and audience size change the harm.', response: 'Delete, apologise, take the issue offline.', learning: 'Netiquette is duty to the receiver.' },
    'Copy a blog paragraph into the assignment; nobody will notice.',
    'Quote or paraphrase, then cite. If the idea is not yours, the source must be visible.',
    ['Name one netiquette rule for a class forum.', 'respect + relevance', 'Stay on topic; do not share private screenshots.'],
    'Academic integrity is not only “no cheating in SEE”. It includes citation, collaboration limits and honest lab data.',
    'Rewrite a harsh class-group message as a professional request.',
  ),
  engJobs: m(
    'Applying for Jobs: Résumé, Application and Interview',
    'human', 'channel',
    ['Job application', 'Résumé and CV', 'Cover letter', 'Interview questions', 'Body language in interviews', 'Follow-up mail'],
    'A résumé is evidence mapped to a role, not a life story.',
    'Application: match skills to the notice. Interview: listen, answer with example, ask one informed question.',
    { situation: 'Campus interview for a technician internship.', issue: 'The candidate reads the résumé aloud and does not answer “Tell me about a team conflict.”', analysis: 'No situation–action–result.', response: 'Give one short STAR example.', learning: 'Interviews test usable examples.' },
    'I am a hardworking student looking for any job.',
    'I completed the C lab distance program and the electrical Ohm’s board. I want this internship to practice measurement and documentation.',
    ['List three résumé sections that an internship notice can actually read.', 'identity, education, evidence', 'contact, education, labs/projects, skills'],
    'Do not invent projects. Interviewers ask how you built them.',
    'Draft a 4-line cover opening for a lab-assistant internship.',
  ),
  icoIntro: m(
    'Making of the Constitution, Preamble and Salient Features',
    'human', 'org',
    ['Necessity of a constitution', 'Society before and after adoption', 'Constituent Assembly', 'Preamble and key concepts', 'Salient features'],
    'A constitution is the legal map of power, rights and limits — not a ceremonial preface.',
    'The Preamble states the aims. Salient features (length, federal-with-unitary-tilt, parliamentary executive, independent judiciary, fundamental rights) describe how those aims are organised.',
    { situation: 'A student asks why a written constitution was needed after 1947.', issue: 'Colonial rules and princely variety left no single citizen-state contract.', analysis: 'The Assembly drafted a supreme law.', response: 'Necessity: limited government + rights + unity.', learning: 'Before/after is a civic change, not nostalgia.' },
    'The Preamble is only decoration.',
    'The Preamble is the key to interpreting aims: justice, liberty, equality, fraternity, and the nature of the Republic.',
    ['Name the body that drafted the Constitution.', 'Constituent Assembly', 'Constituent Assembly of India, with Dr B. R. Ambedkar as chairman of the Drafting Committee (syllabus treatment).'],
    'Do not import current partisan slogans into the Preamble. Stay with the adopted text and classroom terms.',
    'List four salient features named in the module and one sentence on why each matters.',
    { timeline: [
      { when: '1946', text: 'Constituent Assembly formed' },
      { when: '1947', text: 'Independence; Assembly continues as constitution-maker' },
      { when: '26 Nov 1949', text: 'Constitution adopted' },
      { when: '26 Jan 1950', text: 'Republic / commencement' },
    ] },
  ),
  icoRights: m(
    'Fundamental Rights, Directive Principles and Fundamental Duties',
    'human', 'org',
    ['Fundamental Rights and reasonable restrictions', 'DPSP and present relevance', 'Fundamental Duties', 'Nation-building significance'],
    'Rights are enforceable claims; DPSPs are directions to the State; duties bind the citizen.',
    'FRs can be limited in complex situations by reasonable restriction. DPSPs remain relevant as policy goals. Duties complete the rights picture.',
    { situation: 'A protest blocks an ambulance.', issue: 'Speech versus others’ right to life/movement.', analysis: 'Rights collide; reasonable restriction is the constitutional tool.', response: 'The classroom answer names the clash and the limitation principle, not a party line.', learning: 'Complex situations are why restrictions exist.' },
    'Fundamental Rights mean I can do anything.',
    'FRs operate with reasonable restrictions, DPSPs, and duties. Liberty is ordered liberty.',
    ['Give one classroom example of a DPSP still visible in policy.', 'education / environment / workers', 'Free and compulsory education / environmental protection as directed goals.'],
    'Do not treat DPSPs as unenforceable and therefore unimportant. The syllabus asks for present relevance with examples.',
    'Map one FR, one restriction, one DPSP and one duty onto a single campus issue.',
  ),
  icoUnion: m(
    'Union Executive, Parliament and the Supreme Court',
    'human', 'org',
    ['Parliamentary system', 'President, Prime Minister, Cabinet', 'Lok Sabha and Rajya Sabha', 'Parliamentary committees and terms', 'Supreme Court, judicial review, judicial activism'],
    'Union power is a relationship: executive accountable to the legislature, judiciary reviewing both.',
    'Parliamentary executive means the Council of Ministers is responsible to the Lok Sabha. The President is the constitutional head; the PM leads the Cabinet.',
    { situation: 'A Bill is introduced.', issue: 'Students confuse the President with a daily executive like a CEO.', analysis: 'Aid and advice; collective responsibility.', response: 'Trace Bill → House → President. Court may review later.', learning: 'Roles are not interchangeable titles.' },
    'The Prime Minister is the Head of State.',
    'The President is Head of State; the Prime Minister is Head of Government in the parliamentary system taught here.',
    ['What is judicial review at this syllabus depth?', 'courts test laws/actions against the Constitution', 'Supreme Court can strike or read down what violates the Constitution.'],
    'Judicial activism is a syllabus term about assertive review, not a slogan for or against any government.',
    'Sketch LS vs RS in two columns: composition idea, and one function.',
  ),
  icoState: m(
    'State Executive, Elections, Amendments and Emergency Provisions',
    'human', 'org',
    ['State Executive', 'Election Commission and electoral process', 'How and why amendments', 'Important amendments', 'Emergency provisions'],
    'The same constitutional machine runs in the States, through elections, and can be formally changed or temporarily concentrated.',
    'Amendments follow a prescribed procedure because the Constitution is supreme but not frozen. Emergencies are named exceptions, not casual tools.',
    { situation: 'A voter asks who conducts the election.', issue: 'Confusing party, government and Election Commission.', analysis: 'EC is a constitutional authority for the process.', response: 'Name EC, adult suffrage, and the process steps at syllabus depth.', learning: 'Elections are a procedure with an umpire.' },
    'Any majority can rewrite the Constitution like a circular.',
    'Amendment follows the constitutional procedure (how and why). Emergency provisions are listed conditions, not everyday administration.',
    ['Why is an independent Election Commission required?', 'umpire of the process', 'So the executive that is being voted on does not run the count unobserved.'],
    'Do not narrate extra-constitutional politics. Use Assembly/PPTX terminology for emergencies and amendments.',
    'State one reason a constitution must be amendable and one reason amendment must be harder than ordinary law.',
  ),
  icoEthics: m(
    'Professional and Engineering Ethics, IPR, Risk and Safety',
    'human', 'org',
    ['Ethics and values', 'Types of ethics', 'Engineering ethics: positive and negative faces', 'Conflict of interest', 'Impediments to responsibility', 'Trust, IPR, risk, safety, liability'],
    'Engineering ethics is a decision under duty, not a motivational poster.',
    'A clash of ethics appears when safety, cost, employer instruction and public risk disagree. Responsibility can be blocked by ignorance, groupthink or fear.',
    { situation: 'A junior engineer is told to hide a failed test.', issue: 'Loyalty vs safety and truth in the report.', analysis: 'Conflict of interest and impediment to responsibility.', response: 'Record the data; escalate; do not falsify.', learning: 'Trust and liability sit on the report.' },
    'Ethics means whatever the client wants.',
    'Professional ethics binds the engineer to public safety, honest data, IPR respect and named conflicts of interest.',
    ['Name one impediment to responsibility.', 'groupthink / fear / “not my job”', 'Diffusion of responsibility in a team that saw the defect.'],
    'IPR is not “don’t copy songs”; here it is professional respect for designs, software and reports that are not yours to ship as original.',
    'Write a five-line ethics note: facts, duties, options, chosen action, who is protected.',
  ),
  sksSocial: m(
    'Social Skills: Clear Communication, Persuasion, SWOC and Listening',
    'human', 'channel',
    ['Clear professional communication', 'Persuasion: logos, pathos, ethos', 'SWOC self-awareness', 'Active listening: paraphrase and questions'],
    'Social skill is a behaviour in a room, not a personality label.',
    'Clear exchange states purpose. Persuasion uses reason, feeling and credibility. SWOC is evidence about the self. Listening is paraphrase plus a question.',
    { situation: 'A teammate explains a lab error quickly.', issue: 'You interrupt with a solution.', analysis: 'No paraphrase; they stop talking.', response: '“You measured X and got Y — did the polarity of the ammeter match?”', learning: 'Listening is a check, not silence.' },
    'I already know; let me finish for you.',
    'Let me repeat what I heard, then ask one clarifying question before I advise.',
    ['Fill SWOC for “first oral presentation”.', 'strength, weakness, opportunity, challenge', 'name one real item in each cell, not slogans.'],
    'Persuasion that is only emotional pressure is not the three-appeal model in this module.',
    'Paraphrase a classmate’s point in one sentence, then ask a question.',
  ),
  sksEmo1: m(
    'Emotional Skills I: EI, Stress, Time and Resilience',
    'human', 'channel',
    ['Emotional intelligence', 'Stress triggers and balance', 'Eisenhower matrix', 'SMART goals', 'Adaptability and growth mindset'],
    'Emotion, time and setback are skills because they change the next action.',
    'EI is notice–name–choose. The Eisenhower matrix separates urgent from important. Resilience is a recovery action, not “be positive”.',
    { situation: 'Two assignments and a lab viva land on the same day.', issue: 'Student only does the loudest task.', analysis: 'Urgent crowded out important.', response: 'Plot tasks; protect the viva prep block.', learning: 'Time skill is a matrix, not a slogan.' },
    'I work better under last-minute panic.',
    'Panic is a stress trigger. Schedule the important-not-urgent block first.',
    ['Place “revise Ohm’s viva” on the Eisenhower matrix the night before.', 'important, often urgent', 'Do it; do not park it in “someday”.'] ,
    'A growth mindset is not denying a poor mark. It is naming the next practice.',
    'Write one SMART goal for the next fortnight of lab work.',
  ),
  sksEmo2: m(
    'Emotional Skills II: Ambition, Empathy and Creative Problem Solving',
    'human', 'channel',
    ['Ambition and SMART goals', 'Sympathy versus empathy', 'Creativity', 'Mind-mapping and SCAMPER'],
    'Empathy is understanding the other’s map; creativity is a method for new options.',
    'Sympathy says “I feel sorry.” Empathy says “I can describe how it is for you.” SCAMPER is a checklist for idea change.',
    { situation: 'A teammate is anxious before a pitch.', issue: 'You say “don’t worry, it’s easy.”', analysis: 'Sympathy that denies their state.', response: 'Name their stake; ask what they need in the next ten minutes.', learning: 'Empathy is specific.' },
    'Creativity means waiting for a lightning idea.',
    'Use SCAMPER or a mind map on the actual problem sentence.',
    ['Substitute one part of a failed campus-queue idea (SCAMPER S).', 'change a component', 'e.g. replace a paper token with a time-slot message.'],
    'Ambition without a dated action is a wish. Align this week’s tasks to the long goal.',
    'Draw a five-node mind map for “reduce lab waiting time”.',
  ),
  sksPro1: m(
    'Professional Skills I: Problem Solving, Discipline and Scheduling',
    'human', 'channel',
    ['5 Whys and fishbone', 'Discipline and accountability', 'Prioritising and scheduling', 'Avoiding procrastination'],
    'Professional problem-solving names a root cause before a tool.',
    '5 Whys walks from event to cause. Fishbone groups causes. Discipline is a kept calendar, not a personality.',
    { situation: 'The rectifier board shows no DC.', issue: 'The team replaces the transformer first.', analysis: 'No why-chain; they guessed a costly part.', response: 'Check fuse, polarity, connections, then the device.', learning: 'Root cause before replacement.' },
    'We have no time for analysis; just change everything.',
    'Write the fault, five whys, then one test that would confirm the cause.',
    ['Give one fishbone bone for “late lab record”.', 'method / machine / man / material', 'e.g. method: no observation table template.'],
    'Discipline is visible in a kept time-block. Announcing “I will be regular” is not yet the skill.',
    'Run 5 Whys on a missed submission and stop at a cause you can change.',
  ),
  sksPro2: m(
    'Professional Skills II: Teamwork, Negotiation and Critical Thinking',
    'human', 'channel',
    ['Collaboration and trust', 'Negotiation and conflict', 'Win–win outcomes', 'Critical thinking: analyse, evaluate, decide'],
    'A team is a set of roles plus a conflict method, not a group photo.',
    'Negotiation seeks an interest behind a position. Critical thinking tests claims with evidence before deciding.',
    { situation: 'Two members want different project themes.', issue: 'Vote by loudness.', analysis: 'Position clash; interests not named.', response: 'Each states interest; decision matrix; mentor check.', learning: 'Conflict is a process.' },
    'If I am team lead, I decide alone so we go faster.',
    'Lead by making the decision rule visible: evidence, roles, deadline.',
    ['Separate position vs interest: “I want the drone theme.”', 'position vs need', 'interest might be “I can code sensors”; another theme may still serve it.'],
    'Critical thinking is not cynicism. It is asking what would disprove our favourite idea.',
    'Write a win–win proposal for sharing a single lab kit between two pairs.',
  ),
}
