function k(title, visual, topics, why, principle, vocab, passage, grammar, mistake, practice, extras = {}) {
  return { title, domain: 'kannada', visual, topics, why, principle, vocab, passage, grammar, mistake, practice, ...extras }
}

export const kannadaModules = {
  bkIntro: k(
    'ಬಳಕೆ ಕನ್ನಡ: ಸ್ಥಳೀಯ ಭಾಷೆಯ ಅವಶ್ಯಕತೆ, ವಿನಯ ಮತ್ತು ಸರ್ವನಾಮ',
    'channel',
    ['Necessity of local language', 'Listening and speaking', 'Polite conversation', 'Personal pronouns', 'Possessive forms', 'Interrogatives'],
    'ವಿದ್ಯಾರ್ಥಿ ಕನ್ನಡದಲ್ಲಿ ಕೇಳಬೇಕು, ನುಡಿಯಬೇಕು, ಓದಬೇಕು, ಬರೆಯಬೇಕು — ಅನುವಾದ ಪಟ್ಟಿಯಲ್ಲಿ ನಿಲ್ಲಬಾರದು.',
    'Personal pronouns and interrogatives are the first spoken frame: who, what, where, mine/yours.',
    [
      { word: 'ನಾನು', meaning: 'I', usage: 'ನಾನು ವಿದ್ಯಾರ್ಥಿ.' },
      { word: 'ನೀವು', meaning: 'you (polite)', usage: 'ನೀವು ಹೇಗಿದ್ದೀರಿ?' },
      { word: 'ಅವರು', meaning: 'he/she/they (respect)', usage: 'ಅವರು ಉಪನ್ಯಾಸಕರು.' },
      { word: 'ಯಾರು', meaning: 'who', usage: 'ಇದು ಯಾರ ಪುಸ್ತಕ?' },
      { word: 'ಏನು', meaning: 'what', usage: 'ಇದು ಏನು?' },
      { word: 'ಎಲ್ಲಿ', meaning: 'where', usage: 'ಪ್ರಯೋಗಾಲಯ ಎಲ್ಲಿ?' },
    ],
    { author: 'ಬಳಕೆ / usage frame', passage: 'ನಾನು ಕನ್ನಡ ಕಲಿಯುತ್ತಿದ್ದೇನೆ. ನಿಮ್ಮ ಹೆಸರು ಏನು?', meaning: 'A greeting plus an interrogative is the first polite exchange, not a word list.' },
    { from: 'ನಾನು', to: 'ನನ್ನ', note: 'Possessive: I → my. ನನ್ನ ಪುಸ್ತಕ.' },
    'Using ನೀನು with a teacher when ನೀವು is required is not “grammar only”; it is impolite usage.',
    'ಬರೆಯಿರಿ: ನಿಮ್ಮ ಹೆಸರು, ಊರು, ಮತ್ತು ಒಂದು ಪ್ರಶ್ನೆ.',
  ),
  bkNouns: k(
    'ನಾಮಪದಗಳ ಸ್ವಾಮ್ಯ, ಸಂಶಯಾರ್ಥ ಪ್ರಶ್ನೆ, ಗುಣವಾಚಕ ಮತ್ತು ಸಂಖ್ಯೆ',
    'channel',
    ['Possessive nouns', 'Dubitive questions', 'Relative nouns', 'Qualitative / quantitative / colour adjectives', 'Numerals', 'Predictive and locative forms'],
    'ಹೊಂದಿಕೆ: ಯಾರದು, ಎಷ್ಟು, ಯಾವ ಬಣ್ಣ, ಎಲ್ಲಿ — ಇವು ಮಾತಿನ ದೈನಂದಿನ ಅಂಕಿಗಳು.',
    'Possessive and locative case locate the object. Adjectives and numerals specify it.',
    [
      { word: 'ಮನೆ', meaning: 'house', usage: 'ಇದು ರಾಮನ ಮನೆ.' },
      { word: 'ಪುಸ್ತಕ', meaning: 'book', usage: 'ಕೆಂಪು ಪುಸ್ತಕ.' },
      { word: 'ಒಂದು / ಎರಡು', meaning: 'one / two', usage: 'ಎರಡು ಪೆನ್ನು.' },
      { word: 'ಇಲ್ಲಿ / ಅಲ್ಲಿ', meaning: 'here / there', usage: 'ಪುಸ್ತಕ ಅಲ್ಲಿ ಇದೆ.' },
      { word: 'ಚಿಕ್ಕ / ದೊಡ್ಡ', meaning: 'small / big', usage: 'ದೊಡ್ಡ ತರಗತಿ.' },
      { word: 'ಇದೆಯೇ?', meaning: 'is there? (doubt/check)', usage: 'ನೀರು ಇದೆಯೇ?' },
    ],
    { author: 'Locative practice', passage: 'ಪುಸ್ತಕ ಮೇಜಿನ ಮೇಲೆ ಇದೆ. ನೀರು ಇಲ್ಲ.', meaning: 'Locative + predictive (ಇದೆ / ಇಲ್ಲ) make a complete classroom sentence.' },
    { from: 'ಮನೆ', to: 'ಮನೆಯಲ್ಲಿ', note: 'Locative: in/at the house.' },
    'Do not stack English word-for-word. ಕೆಂಪು ಬಣ್ಣದ ಪುಸ್ತಕ is an adjective phrase, not “red colour of book” calque.',
    'ವಿವರಿಸಿ: ಮೂರು ವಸ್ತುಗಳ ಬಣ್ಣ, ಸಂಖ್ಯೆ ಮತ್ತು ಸ್ಥಳ.',
  ),
  bkDative: k(
    'ಚತುರ್ಥೀ ವಿಭಕ್ತಿ, ಕ್ರಮಸಂಖ್ಯೆ, ಬಹುವಚನ ಮತ್ತು ನಿಷೇಧ',
    'channel',
    ['Dative case', 'Numerals', 'Ordinals', 'Plural markers', 'Defective / negative verbs', 'Colour adjectives'],
    'ಯಾರಿಗೆ / ಯಾವುದಕ್ಕೆ ಎಂಬುದು ದಾನ ಅಥವಾ ಗುರಿಯ ವಿಭಕ್ತಿ.',
    'Dative marks the recipient. Ordinals order. Plurals and negatives change the verb, not only the noun.',
    [
      { word: 'ನನಗೆ', meaning: 'to/for me', usage: 'ನನಗೆ ನೀರು ಬೇಕು.' },
      { word: 'ಅವರಿಗೆ', meaning: 'to them (polite)', usage: 'ಅವರಿಗೆ ಹೇಳಿ.' },
      { word: 'ಮೊದಲನೆಯ', meaning: 'first', usage: 'ಮೊದಲನೆಯ ಪಾಠ.' },
      { word: 'ಪುಸ್ತಕಗಳು', meaning: 'books', usage: 'ಪುಸ್ತಕಗಳು ಮೇಜಿನ ಮೇಲೆ.' },
      { word: 'ಇಲ್ಲ', meaning: 'is not / no', usage: 'ಸಮಯ ಇಲ್ಲ.' },
      { word: 'ಬೇಡ', meaning: 'do not want (neg.)', usage: 'ನನಗೆ ಇದು ಬೇಡ.' },
    ],
    { author: 'Request frame', passage: 'ನನಗೆ ಒಂದು ನೋಟ್ಬುಕ್ ಕೊಡಿ. ಇನ್ನೊಂದು ಬೇಡ.', meaning: 'Dative + imperative + negative is a complete shop/lab request.' },
    { from: 'ನಾನು', to: 'ನನಗೆ', note: 'Nominative to dative for need/recipient.' },
    'Plural is not always +s. Learn the Kannada marker on the noun you are actually using.',
    'ಐದು ವಾಕ್ಯ: ಯಾರಿಗೆ ಏನು ಬೇಕು / ಬೇಡ.',
  ),
  bkImperative: k(
    'ಆಜ್ಞೆ, ಅನುಮತಿ, ದ್ವಿತೀಯಾ ವಿಭಕ್ತಿ ಮತ್ತು ಇರು / ಇರಲ್ಲ',
    'channel',
    ['Permission and commands', 'Encouraging / urging', 'Accusative', 'Potential forms', 'Helping verbs iru / iralla', 'Comparison and identification'],
    'ತರಗತಿ ಮತ್ತು ಪ್ರಯೋಗಾಲಯದಲ್ಲಿ ಹೆಚ್ಚು ಬಳಕೆಯಾಗುವುದು ಆಜ್ಞಾರ್ಥ ಮತ್ತು ಅನುಮತಿ.',
    'Imperative asks or allows. Accusative marks the object. iru/iralla locate existence now/future/negation.',
    [
      { word: 'ಕುಳಿತುಕೊಳ್ಳಿ', meaning: 'please sit', usage: 'ದಯವಿಟ್ಟು ಕುಳಿತುಕೊಳ್ಳಿ.' },
      { word: 'ಕೊಡಿ', meaning: 'please give', usage: 'ಪೆನ್ನು ಕೊಡಿ.' },
      { word: 'ಬರಬಹುದು', meaning: 'may come (permission)', usage: 'ನಾಳೆ ಬರಬಹುದು.' },
      { word: 'ಪುಸ್ತಕವನ್ನು', meaning: 'the book (object)', usage: 'ಪುಸ್ತಕವನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ.' },
      { word: 'ಇದೆ', meaning: 'is / exists', usage: 'ಸಮಯ ಇದೆ.' },
      { word: 'ಇರಲ್ಲ', meaning: 'will not be', usage: 'ನಾಳೆ ಅವರು ಇರಲ್ಲ.' },
    ],
    { author: 'Lab instruction', passage: 'ಸರ್ಕ್ಯೂಟ್ ಅನ್ನು ಮುಟ್ಟಬೇಡಿ. ಇಲ್ಲಿ ನಿಲ್ಲಿ.', meaning: 'Negative command plus locative: safety language.' },
    { from: 'ಪುಸ್ತಕ', to: 'ಪುಸ್ತಕವನ್ನು', note: 'Accusative object marker in a command.' },
    'A blunt command to a teacher (ನೀನು ಕೊಡು) fails politeness even if the verb is “correct”.',
    'ಬರೆಯಿರಿ: ಒಂದು ಅನುಮತಿ, ಒಂದು ಆಜ್ಞೆ, ಒಂದು ನಿಷೇಧ.',
  ),
  bkTense: k(
    'ಕಾಲ, ಕ್ರಿಯಾಪದ ರೂಪ ಮತ್ತು ಸಂಭಾಷಣಾ ಪದಕೋಶ',
    'channel',
    ['Tense and time verbs', 'Past, present, future formation', 'Conversation vocabulary'],
    'ಕಾಲವನ್ನು ಬದಲಾಯಿಸಿದಾಗ ವಾಕ್ಯದ ಕ್ರಿಯಾಪದವೇ ಬದಲಾಗುತ್ತದೆ.',
    'Present, past and future are built with verb forms, not by sticking English tense words onto Kannada nouns.',
    [
      { word: 'ಹೋಗುತ್ತೇನೆ', meaning: 'I go / will go (present/future family)', usage: 'ನಾನು ಕಾಲೇಜಿಗೆ ಹೋಗುತ್ತೇನೆ.' },
      { word: 'ಹೋದೆ', meaning: 'I went', usage: 'ನಾನು ನಿನ್ನೆ ಹೋದೆ.' },
      { word: 'ಬರುವೆ', meaning: 'I will come', usage: 'ನಾನು ನಾಳೆ ಬರುವೆ.' },
      { word: 'ತಿಂದೆ', meaning: 'I ate', usage: 'ನಾನು ಊಟ ತಿಂದೆ.' },
      { word: 'ಮಾತನಾಡುತ್ತೇನೆ', meaning: 'I speak', usage: 'ನಾನು ಕನ್ನಡ ಮಾತನಾಡುತ್ತೇನೆ.' },
      { word: 'ಶುಭ ದಿನ', meaning: 'good day', usage: 'ಶುಭ ದಿನ, ಸರ್.' },
    ],
    { author: 'Three-time drill', passage: 'ನಿನ್ನೆ ಓದಿದೆ. ಇಂದು ಓದುತ್ತೇನೆ. ನಾಳೆ ಓದುವೆ.', meaning: 'Same verb root, three time forms, one student subject.' },
    { from: 'ಓದು', to: 'ಓದಿದೆ / ಓದುತ್ತೇನೆ / ಓದುವೆ', note: 'Past / present / future of “read” for ನಾನು.' },
    'Do not leave the verb in English (“yesterday I go class”). The Kannada verb must carry time.',
    'ಒಂದೇ ಕ್ರಿಯೆಯನ್ನು ಮೂರು ಕಾಲದಲ್ಲಿ ಬರೆಯಿರಿ.',
  ),
  skCulture: k(
    'ಕನ್ನಡ ಸಂಸ್ಕೃತಿ, ಕರ್ನಾಟಕ ಏಕೀಕರಣ ಮತ್ತು ಆಡಳಿತ ಭಾಷೆ',
    'channel',
    ['Karnataka culture', 'Unification of Karnataka', 'Administrative Kannada'],
    'ಸಂಸ್ಕೃತಿಕ ಕನ್ನಡವು ಕೇವಲ ವ್ಯಾಕರಣವಲ್ಲ; ಇತಿಹಾಸ, ಆಡಳಿತ ಮತ್ತು ಸಾಹಿತ್ಯದ ನೆಲೆ.',
    'Unification is a historical process with writers and public debate. Administrative Kannada is the language of the office and the citizen.',
    [
      { word: 'ಸಂಸ್ಕೃತಿ', meaning: 'culture', usage: 'ಕನ್ನಡ ಸಂಸ್ಕೃತಿ.' },
      { word: 'ಏಕೀಕರಣ', meaning: 'unification', usage: 'ಕರ್ನಾಟಕ ಏಕೀಕರಣ.' },
      { word: 'ಆಡಳಿತ', meaning: 'administration', usage: 'ಆಡಳಿತ ಭಾಷೆ ಕನ್ನಡ.' },
      { word: 'ನಾಡು', meaning: 'land / state (cultural)', usage: 'ನಮ್ಮ ನಾಡು.' },
    ],
    { author: 'ಘಟಕ ೧ — ನೆಲೆ', passage: 'ಕನ್ನಡ ನಾಡಿನ ಸಂಸ್ಕೃತಿ, ಏಕೀಕರಣದ ಚರಿತ್ರೆ ಮತ್ತು ಆಡಳಿತ ಭಾಷೆಯ ಬಳಕೆ ಒಂದೇ ಪಾಠದ ಮೂರು ಕಿಟಕಿಗಳು.', meaning: 'Culture, political unification and office language are three syllabus windows, not one slogan.' },
    { from: 'ನಾಡು', to: 'ಆಡಳಿತ ಭಾಷೆ', note: 'From cultural land to the language of files and citizens.' },
    'Do not reduce unification to a single date meme. The syllabus asks for the process and its writers.',
    'ಮೂರು ವಾಕ್ಯ: ಸಂಸ್ಕೃತಿ, ಏಕೀಕರಣ, ಆಡಳಿತ ಭಾಷೆ.',
  ),
  skBhakti: k(
    'ವಚನ, ಕೀರ್ತನೆ ಮತ್ತು ತತ್ತ್ವಪದ — ಆಧ್ಯಾತ್ಮಿಕ ಸಾಹಿತ್ಯ',
    'channel',
    ['Vachanas: Basavanna, Akkamahadevi and others', 'Keerthanas', 'Tatvapadas'],
    'ವಚನವು ಸಾಲು-ಸಾಲಾಗಿ ನಡೆಯುವ ಆಲೋಚನೆ; ಕೇವಲ ಭಕ್ತಿಗೀತೆಯ ಲೇಬಲ್ ಅಲ್ಲ.',
    'Read author, context, a few lines, then the ethical idea. Do not stop at the poet’s name.',
    [
      { word: 'ವಚನ', meaning: 'vachana (sharana verse)', usage: 'ಬಸವಣ್ಣನ ವಚನ.' },
      { word: 'ಅನುಭಾವ', meaning: 'lived spiritual experience', usage: 'ವಚನದ ಅನುಭಾವ.' },
      { word: 'ಕೀರ್ತನೆ', meaning: 'devotional lyric', usage: 'ಕನಕದಾಸರ ಕೀರ್ತನೆ.' },
      { word: 'ತತ್ತ್ವಪದ', meaning: 'philosophical song', usage: 'ಶಿಶುನಾಳ ಷರೀಫರ ತತ್ತ್ವಪದ.' },
    ],
    { author: 'ಬಸವಣ್ಣ / ವಚನ ಪರಂಪರೆ', passage: 'ಕಾಯಕವೇ ಕೈಲಾಸ — ಕೆಲಸವೇ ಪೂಜೆ ಎಂಬ ನೆಲೆಗಟ್ಟು (ತರಗತಿ ಆಳದಲ್ಲಿ).', meaning: 'Work and ethical life are the teaching point, not a poster quote without the author.' },
    { from: 'ವಚನ', to: 'ಆಚರಣೆ', note: 'From line to social ethic: work, equality, inner devotion.' },
    'Do not mix vachana, keerthana and tatvapada as one “old song” pile. Each has a form and a community.',
    'ಒಂದು ವಚನದ ಎರಡು ಸಾಲು + ಒಂದು ವಾಕ್ಯದ ಅರ್ಥ.',
  ),
  skModern: k(
    'ಆಧುನಿಕ ಕಾವ್ಯ: ಕುವೆಂಪು, ಬೇಂದ್ರೆ ಮತ್ತು ಆಯ್ದ ಸಾಲುಗಳು',
    'channel',
    ['Selected modern poems', 'Kuvempu', 'Bendre', 'Reading for theme'],
    'ಆಧುನಿಕ ಕವಿತೆಗೆ ಲೇಖಕ, ಸಾಲು, ಭಾವ ಮತ್ತು ಪ್ರಶ್ನೆ ಬೇಕು.',
    'Author and context first, then the passage, then the theme in the student’s words.',
    [
      { word: 'ಕವಿತೆ', meaning: 'poem', usage: 'ಆಧುನಿಕ ಕವಿತೆ.' },
      { word: 'ಭಾವ', meaning: 'feeling / tone', usage: 'ಕವಿತೆಯ ಭಾವ.' },
      { word: 'ನೆಲೆ', meaning: 'ground / setting', usage: 'ಕಾವ್ಯದ ನೆಲೆ.' },
      { word: 'ಸಾಲು', meaning: 'line of verse', usage: 'ಮುಖ್ಯ ಸಾಲು.' },
    ],
    { author: 'ಕುವೆಂಪು / ಬೇಂದ್ರೆ — ತರಗತಿ ಓದು', passage: 'ಆಯ್ದ ಸಾಲುಗಳನ್ನು ಓದಿ, ಭಾವವನ್ನು ವಿದ್ಯಾರ್ಥಿಯ ಭಾಷೆಯಲ್ಲಿ ಹೇಳಿ, ನಂತರ ಪ್ರಶ್ನೆ ಕೇಳಿ.', meaning: 'Modern lyric is taught as voice + land + human feeling, not as exam keywords only.' },
    { from: 'ಸಾಲು', to: 'ಭಾವ', note: 'From the line on the page to the feeling it carries.' },
    'Paraphrase is not a replacement for the Kannada line. Keep the line, then explain.',
    'ಒಂದು ಸಾಲಿನ ಅರ್ಥವನ್ನು ಎರಡು ವಾಕ್ಯದಲ್ಲಿ ಬರೆಯಿರಿ.',
  ),
  skScience: k(
    'ವೈಜ್ಞಾನಿಕ ಬರಹ: ವಿಶ್ವೇಶ್ವರಯ್ಯ ಮತ್ತು ಆಡಳಿತ/ಇತಿಹಾಸ ನೆಲೆ',
    'channel',
    ['Sir M. Visvesvaraya', 'Scientific and public prose', 'History of ideas in Kannada'],
    'ವೈಜ್ಞಾನಿಕ ಲೇಖನವು ವಾದ, ಉದಾಹರಣೆ ಮತ್ತು ನಾಗರಿಕ ಜವಾಬ್ದಾರಿ.',
    'Read the person, the public work, then the idea of planned, ethical engineering citizenship at syllabus depth.',
    [
      { word: 'ಇಂಜಿನಿಯರ್', meaning: 'engineer', usage: 'ವಿಶ್ವೇಶ್ವರಯ್ಯ ಅವರು ಇಂಜಿನಿಯರ್.' },
      { word: 'ಯೋಜನೆ', meaning: 'plan', usage: 'ಜಲ ಯೋಜನೆ.' },
      { word: 'ಶಿಸ್ತು', meaning: 'discipline', usage: 'ಕೆಲಸದ ಶಿಸ್ತು.' },
      { word: 'ನಾಗರಿಕ', meaning: 'citizen', usage: 'ನಾಗರಿಕ ಜವಾಬ್ದಾರಿ.' },
    ],
    { author: 'ಸರ್ ಎಂ. ವಿಶ್ವೇಶ್ವರಯ್ಯ', passage: 'ಯೋಜನೆ, ನೀರು, ಶಿಸ್ತು ಮತ್ತು ರಾಷ್ಟ್ರಕಾರ್ಯ — ವೈಜ್ಞಾನಿಕ ಗದ್ಯದ ನೆಲೆ.', meaning: 'The prose is about public works and character, not a celebrity caption.' },
    { from: 'ಯೋಜನೆ', to: 'ನಾಗರಿಕ ಫಲ', note: 'Engineering plan exists for public outcome.' },
    'Do not turn the lesson into a general motivation quote. Stay with work, plan and civic effect.',
    'ವಿಶ್ವೇಶ್ವರಯ್ಯ ಅವರ ಬಗ್ಗೆ ಮೂರು ವಾಸ್ತವಿಕ ವಾಕ್ಯ.',
  ),
  skFolk: k(
    'ಸಾಂಸ್ಕೃತಿಕ, ಜನಪದ ಕಥೆ ಮತ್ತು ಸಣ್ಣ ಕಥನ',
    'channel',
    ['Cultural narrative', 'Folk tale', 'Short story'],
    'ಜನಪದ ಮತ್ತು ಸಣ್ಣಕಥೆ: ಪಾತ್ರ, ಸಂಘರ್ಷ, ಪಾಠ.',
    'Story teaching: teller/context → passage → meaning → theme → a question.',
    [
      { word: 'ಜನಪದ', meaning: 'folk', usage: 'ಜನಪದ ಕಥೆ.' },
      { word: 'ಕಥನ', meaning: 'narrative', usage: 'ಸಣ್ಣ ಕಥನ.' },
      { word: 'ಪಾತ್ರ', meaning: 'character', usage: 'ಮುಖ್ಯ ಪಾತ್ರ.' },
      { word: 'ಪಾಠ', meaning: 'moral / learning', usage: 'ಕಥೆಯ ಪಾಠ.' },
    ],
    { author: 'ಜನಪದ / ಸಣ್ಣಕಥೆ', passage: 'ಒಂದು ಘಟನೆ, ಒಂದು ಆಯ್ಕೆ, ಒಂದು ಪರಿಣಾಮ — ಆ ಬಳಿಕ ವಿದ್ಯಾರ್ಥಿ ಪ್ರಶ್ನೆ.', meaning: 'Folk and short story are not “entertainment slides”; they are situation → issue → learning.' },
    { from: 'ಘಟನೆ', to: 'ಪಾಠ', note: 'From incident to what the story asks us to notice.' },
    'A moral slapped on without the story’s conflict is not reading.',
    'ಕಥೆಯ ಸಂಘರ್ಷವನ್ನು ಒಂದು ವಾಕ್ಯದಲ್ಲಿ ಹೇಳಿ.',
  ),
}
