function lab(title, aim, principle, tools, setup, procedure, observation, result, error, viva, visual, extra = {}) {
  return { title, domain: 'lab', visual, aim, principle, tools, setup, procedure, observation, result, error, viva, ...extra }
}

export const mechanicalLabs = [
  lab('Facing, plain turning and step turning on a lathe', 'Produce a stepped cylinder by facing and turning.', 'Work rotates; tool feeds. Facing squares the end; turning sets diameter; steps need two diameters.', 'Lathe, cutting tool, chuck, caliper, job', 'Centre the job; set rpm for the material; never leave the chuck key.', ['Face the end', 'Turn first diameter', 'Turn second diameter', 'Measure with caliper', 'Deburr'], 'Diameters and lengths as specified.', 'Stepped job within shop tolerance.', 'Calling knurling a turning diameter-set.', 'What relative motion produces a cylinder?', 'bench'),
  lab('Facing, plain turning and knurling', 'Turn a diameter and knurl a grip.', 'Knurling impresses a pattern; it is not a cutting pass that sets a precision diameter.', 'Lathe, knurling tool, job', 'Support the job; moderate pressure on the knurl.', ['Face', 'Turn', 'Engage knurl', 'Check pattern', 'Measure diameter after knurl'], 'Knurl pattern quality and diameter.', 'Faced, turned and knurled specimen.', 'Using knurl pressure to “reduce diameter to size”.', 'Why is knurling a forming operation?', 'bench'),
  lab('Arc-welded joints', 'Prepare a specified welded joint.', 'Arc melts parent metal and electrode; joint type (butt/lap/tee) is a geometry.', 'Welding transformer/inverter, electrode, PPE, coupons', 'PPE on; earth clamp on the job; screen others.', ['Prepare edges', 'Tack', 'Weld the pass', 'Chip slag', 'Inspect bead'], 'Bead appearance and continuity.', 'Welded joint as specified, visually acceptable.', 'Looking at the arc without a helmet.', 'Butt vs lap: which faces are fused?', 'bench'),
  lab('Calibration of vernier caliper and micrometer with slip gauges', 'Check instrument error using slips.', 'Slip gauges are reference lengths. Error = indicated − true.', 'Vernier, micrometer, slip set, cloth', 'Clean wring slips; zero the instruments first.', ['Select slips', 'Wring', 'Measure', 'Tabulate error', 'Comment'], 'Error table vs nominal.', 'Calibration statement for both instruments.', 'Forcing a dirty slip stack.', 'Why zero before calibration?', 'bench'),
  lab('Angle of a specimen using a sine bar', 'Find an unknown angle.', 'sin θ = h / L. Height from slips, L is sine-bar length.', 'Sine bar, slips, DTI/surface plate, specimen', 'Plate clean; sine bar against the angle.', ['Set slips for a trial', 'Seat the bar', 'Use DTI for parallelism', 'Adjust h', 'Compute θ'], 'h, L, θ.', 'Angle of the specimen.', 'Using θ = h/L in degrees without arcsin.', 'Why must the surface plate be the datum?', 'bench'),
  lab('Hardness test', 'Measure hardness of given materials.', 'Indentation hardness (Brinell/Rockwell/Vickers as available) is load over impression geometry.', 'Hardness tester, indenters, specimens', 'Seat the specimen; select scale; never indent the edge.', ['Choose scale', 'Apply load', 'Read hardness', 'Repeat', 'Compare materials'], 'Hardness numbers.', 'Relative hardness ranking with the scale named.', 'Comparing HRC with HB as if the numbers were the same scale.', 'Why is the scale part of the result?', 'bench'),
  lab('Flash and fire point — open cup', 'Compare flash/fire points of oils (open cup).', 'Flash: vapour ignites briefly. Fire: sustained burning. Open cup is the specified method here.', 'Open-cup apparatus, oils, thermometer, flame', 'Heat slowly; never overfill; fire blanket ready.', ['Fill to mark', 'Heat', 'Apply test flame at intervals', 'Note flash', 'Note fire if required'], 'Temperatures for each oil.', 'Open-cup flash (and fire) comparison.', 'Heating so fast that the thermometer lags.', 'Flash vs fire: which is sustained?', 'bench'),
  lab('Flash and fire point — closed cup', 'Same comparison with closed cup.', 'Closed cup traps vapour; numbers differ from open cup. Do not mix methods in one table without naming the cup.', 'Closed-cup apparatus, oils', 'Lid protocol as in the manual.', ['Close cup', 'Heat', 'Open for test flame as specified', 'Record', 'Compare with open-cup data if both done'], 'Closed-cup temperatures.', 'Closed-cup ranking of oils.', 'Reporting open-cup data as closed-cup.', 'Why might closed-cup flash be lower?', 'bench'),
  lab('Viscosity of different base fuels', 'Compare viscosity of fuels.', 'Viscosity is resistance to flow. Redwood/Saybolt/U-tube as available — name the instrument.', 'Viscometer, bath, stopwatch, fuels', 'Bath at the stated temperature.', ['Bring to temperature', 'Time efflux or measure', 'Repeat', 'Tabulate', 'Rank fuels'], 'Times/viscosity values.', 'Relative viscosity ranking at T.', 'Comparing two fuels at two different bath temperatures.', 'Why is temperature on the result line?', 'bench'),
  lab('Effect of additives on viscosity', 'See how an additive changes viscosity of a base fuel.', 'Additive can thicken or thin. Compare base vs treated at the same T.', 'Viscometer, base fuel, additive, mixer', 'Same bath temperature as the previous experiment.', ['Measure base', 'Dose additive as instructed', 'Mix', 'Measure again', 'Conclude direction of change'], 'Two viscosity values.', 'Additive raised/lowered viscosity (as observed).', 'Changing temperature and additive at once.', 'What was held constant?', 'bench'),
  lab('Selecting a joining technique', 'Justify weld vs solder vs braze vs fastener for a given job.', 'Heat, parent melt, strength and disassembly decide the process.', 'Sample joints or cards, PPE if demo', 'Read the application: electrical, structural, temporary.', ['List requirements', 'Map to process', 'State limitation', 'Name inspection', 'Write justification'], 'Decision table.', 'A justified choice, not a favourite process.', 'Choosing arc weld for a PCB pad.', 'When is soldering preferred to welding?', 'bench'),
  lab('Sheet-metal part with soldering', 'Make a simple tray/box and solder a joint.', 'Development gives true lengths; solder melts filler, not usually the parent steel.', 'Snips, mallet, stakes, solder, flux, iron', 'Deburr; flux; heat the joint, not only the solder wire.', ['Develop pattern', 'Cut and fold', 'Tack geometry', 'Solder', 'Inspect'], 'Geometry and solder fillet.', 'Finished simple sheet-metal part.', 'Using the iron as a shovel to drip cold solder.', 'Why flux?', 'bench'),
]

export const materialsLabs = [
  lab('Verification of Lami’s theorem', 'Check Lami on three concurrent forces in equilibrium.', 'P/sin p = Q/sin q = R/sin r for three concurrent coplanar forces in equilibrium.', 'Force board, weights, protractor', 'Ensure concurrency at one knot.', ['Set two known forces', 'Adjust third', 'Measure angles', 'Compute Lami ratios', 'Compare'], 'Ratios nearly equal.', 'Lami verified within string/pulley error.', 'Using interior angles that are not the angles opposite the forces.', 'What does concurrent mean?', 'materials'),
  lab('Equilibrium of concurrent forces', 'Find the equilibrant of a concurrent system.', 'Equilibrant is equal and opposite to the resultant.', 'Force table or board', 'All lines through one point.', ['Apply known forces', 'Find equilibrant experimentally', 'Resolve on paper', 'Compare', 'Comment'], 'Experimental vs calculated equilibrant.', 'Agreement within error.', 'Vector addition of non-concurrent forces as if concurrent.', 'How is equilibrant different from resultant?', 'materials'),
  lab('Simply supported beam — parallel forces', 'Find support reactions of a beam with parallel loads.', 'ΣFy = 0 and ΣM = 0. Reactions are upward if loads are downward.', 'Beam apparatus, hangers, metre scale', 'Supports at marked ends; loads as specified.', ['Place loads', 'Read reactions if the kit allows', 'Take moments', 'Compute RA, RB', 'Check ΣFy'], 'RA, RB and check.', 'Reactions match statics.', 'Putting a moment capacity on a simple support.', 'Why take moments about one support?', 'materials'),
  lab('Verification of Varignon’s theorem', 'Moment of a force equals the sum of moments of its components.', 'Varignon: about the same point, M_F = M_components.', 'Force board, set square, weights', 'Resolve the force into two perpendicular components on paper and on the board if possible.', ['Apply F at an angle', 'Compute M = F d', 'Resolve', 'Sum component moments', 'Compare'], 'Two moment values.', 'Varignon holds.', 'Taking component moments about two different points.', 'Why must the point be the same?', 'materials'),
  lab('Specific gravity of fine/coarse aggregate, cement and soil', 'Measure Gs of four construction materials.', 'Gs = density of material / density of water. Bottle or pycnometer method as specified.', 'Pycnometer/density bottle, balance, water, samples', 'Dry sample mass; de-air as instructed.', ['Weigh empty', 'Weigh with sample', 'Weigh with water', 'Apply the formula', 'Repeat for each material'], 'Gs table for four materials.', 'Gs in expected ranges (cement ~3.1, soil/aggregate typical bands).', 'Using wet mass as if it were dry.', 'Why de-air the bottle?', 'materials'),
  lab('Sieve analysis of soil and visual identification of building materials', 'Plot a gradation curve; identify common building materials by sight.', 'Particle-size distribution is mass retained on each sieve. Visual ID uses colour, texture, form.', 'Sieve set, shaker, balance, material samples', 'Nest sieves; do not overload.', ['Weigh sample', 'Sieve', 'Mass retained', 'Plot % passing', 'Identify bricks/aggregates/steel/wood samples'], 'Gradation curve + ID list.', 'Well/poor grading comment plus named materials.', 'Skipping the pan and losing fines.', 'What does a steep curve mean?', 'materials'),
  lab('Field tests on cement', 'Perform the syllabus field tests on cement.', 'Field tests (colour, lumps, float, date, feel) are screening, not IS laboratory strength.', 'Cement sample, water, glass plate as required', 'Use fresh vs stale comparison if provided.', ['Colour/feel', 'Lump check', 'Float or other listed test', 'Record', 'Conclude fitness for field use'], 'Pass/fail against field criteria.', 'Field-test conclusion with limitations.', 'Calling a field test a 28-day compressive strength.', 'Why is a lab test still required for structural cement?', 'materials'),
  lab('Particle size distribution', 'Detailed PSD (often a second soil/aggregate set).', 'Same sieve logic; report D10/D30/D60 if the sheet asks.', 'Sieves, sample, chart paper', 'Log-scale x if the sheet uses it.', ['Sieve', 'Compute % finer', 'Plot', 'Read characteristic sizes if asked', 'Classify'], 'PSD plot.', 'Gradation classification.', 'Linear x-axis when the sheet specifies log.', 'What is uniformity coefficient at this level if asked?', 'materials'),
  lab('Well-graded soil / complementary identification', 'Recognise well-graded material and complete remaining ID.', 'Well-graded: wide size range, smooth curve. Poorly graded: gap or uniform.', 'Previous PSD plot, extra samples', 'Compare two curves side by side.', ['Place two curves', 'Name well vs poorly graded', 'State engineering implication', 'Finish visual ID', 'Write caution on sampling'], 'Classification plus implication.', 'Well-graded sample identified; implication for packing/voids.', 'Calling any soil with stones “well graded”.', 'Why does grading affect compaction?', 'materials'),
]

export const cLabs = [
  lab('Distance between two points', 'Compute straight-line distance on a 2D plane.', 'distance = sqrt((x2-x1)² + (y2-y1)²).', 'C compiler, editor', 'Read four numbers; print the distance.', ['Write algorithm', 'Include math.h', 'Read coordinates', 'Compute', 'Print with units in the comment'], 'Sample: (0,0) (3,4) → 5', 'Program prints the Euclidean distance.', 'Integer division of the squares.', 'Why include <math.h>?', 'code', {
    code: ['#include <stdio.h>', '#include <math.h>', 'int main(void) {', '  double x1=0,y1=0,x2=3,y2=4;', '  printf("%.2f", sqrt((x2-x1)*(x2-x1)+(y2-y1)*(y2-y1)));', '}'],
    dryRows: [['1', 'dx=3, dy=4', 'squares 9+16', 'sqrt 25', '5.00']],
  }),
  lab('Grade from marks', 'Map marks to A–F with a control structure.', 'Thresholds are mutually exclusive; order the conditions from high to low.', 'C compiler', 'One integer marks; print grade.', ['Decide if/else ladder or switch-on-range idea', 'Code high-to-low', 'Test boundaries 90, 89, 50, 49', 'Print grade'], 'Boundary table.', 'Correct grade including boundaries.', 'Testing 90 as B because of a reversed condition.', 'Which control structure did you choose and why?', 'code', {
    code: ['if (m >= 90) puts("A");', 'else if (m >= 75) puts("B");', 'else if (m >= 60) puts("C");', 'else if (m >= 50) puts("D");', 'else puts("F");'],
    dryRows: [['90', '>=90', 'A', 'stop', 'A'], ['89', '>=75', 'B', 'stop', 'B'], ['49', 'else', 'F', 'stop', 'F']],
  }),
  lab('KYC unique-ID verification', 'Match an integer ID against stored records.', 'A multi-way check (if/else or switch) compares input with stored keys.', 'C compiler', 'Assume IDs are integers as in the sheet.', ['Store a small set of IDs', 'Read one ID', 'Search', 'Print verified / not'], 'A known ID verifies; an unknown fails.', 'Correct verification message.', 'Using string IDs when the sheet says integer.', 'Why is switch natural if the IDs are discrete integers?', 'code', {
    code: ['int id; scanf("%d", &id);', 'if (id==101 || id==202) puts("verified");', 'else puts("not verified");'],
    dryRows: [['101', 'match', 'verified', '', 'verified'], ['0', 'no match', 'not verified', '', 'not verified']],
  }),
  lab('Quadratic roots', 'Classify and compute roots from a, b, c.', 'D = b²−4ac. D>0 real distinct; D=0 repeated; D<0 not real (at this lab depth).', 'C compiler, math.h', 'Protect a == 0.', ['Read a,b,c', 'If a==0, reject', 'Compute D', 'Branch', 'Print'], 'Three test triples.', 'Correct type and values for a sample.', 'sqrt of negative D without a message.', 'What must you test before dividing by 2a?', 'code', {
    code: ['double D = b*b - 4*a*c;', 'if (D < 0) puts("not real");', 'else { /* two roots */ }'],
    dryRows: [['1,-3,2', 'D=1', 'real distinct', '2 and 1', 'ok']],
  }),
  lab('sin(x) by series (no library sin)', 'Approximate sin x by a series for a robotic-angle demo.', 'sin x ≈ x − x³/3! + x⁵/5! − … with x in radians.', 'C compiler', 'Convert degrees if the user enters degrees.', ['Decide n terms', 'Loop factorial/power or running term', 'Add with sign', 'Print', 'Compare mentally with 30° = 0.5'], 'sin(π/6) near 0.5', 'Series value close to expected.', 'Using x in degrees inside the series.', 'Why radians?', 'code', {
    code: ['double t = x, s = x;', 'for (int k=1;k<n;k++) { t *= -x*x/((2*k)*(2*k+1)); s += t; }'],
    dryRows: [['k=0', 'term=x', 's=x', '', ''], ['k=1', 'subtract x^3/6', 's updated', '', 'closer']],
  }),
  lab('Keyword search in a course string', 'Find whether a keyword occurs in a description.', 'Use strstr (or a manual scan). Report found / not found with the keyword shown.', 'C compiler, string.h', 'Read line safely as the lab allows.', ['Read description', 'Read keyword', 'Search', 'Print the exact required sentence'], 'Found and not-found cases.', 'Messages match the syllabus wording.', 'Matching case-insensitively when not asked, or overflowing the buffer.', 'What does strstr return on failure?', 'code', {
    code: ['if (strstr(desc, key)) printf("Keyword \'%s\' found in the course description.\\n", key);', 'else printf("Keyword \'%s\' not found in the course description.\\n", key);'],
    dryRows: [['C lab / lab', 'strstr hits', 'found sentence', '', 'found']],
  }),
  lab('Pass/fail via a function', 'Three marks; function decides pass (min 40 each) and average.', 'A function returns a status; main prints. Average is a separate value.', 'C compiler', 'Pass only if every subject ≥ 40.', ['Write int passed(int,int,int)', 'Compute avg', 'Print', 'Test 40,40,39'], 'Fail when one subject is 39.', 'Correct pass/fail and average.', 'Averaging first and ignoring a 39.', 'Why is the check a function?', 'code', {
    code: ['int passed(int a,int b,int c){ return a>=40 && b>=40 && c>=40; }'],
    dryRows: [['40,40,40', 'true', 'pass', 'avg 40', 'pass'], ['40,40,39', 'false', 'fail', '', 'fail']],
  }),
  lab('Swap two balances with pointers', 'ATM validation swap using a pointer function.', 'A function that sees addresses can exchange the caller’s variables.', 'C compiler', 'Print before and after.', ['void swap(int *p, int *q)', 'Call with &a, &b', 'Print'], '80 and 20 become 20 and 80.', 'Balances swapped.', 'swap(a,b) by value — originals unchanged.', 'What does *p = *q do in the swap?', 'code', {
    code: ['void swap(int *p, int *q){ int t=*p; *p=*q; *q=t; }'],
    dryRows: [['before', 'a=80 b=20', 'swap(&a,&b)', 'after 20,80', 'ok']],
  }),
  lab('Library Book ID search', 'Search a unique Book ID in an organised shelf (array).', 'Linear or ordered search as designed; report found index or not found.', 'C compiler', 'Array of IDs; read a key.', ['Fill IDs', 'Read key', 'Search', 'Print position or fail'], 'Known ID found.', 'Correct search result.', 'Off-by-one past the last book.', 'If the shelf is sorted, what can you change later?', 'code', {
    code: ['for (int i=0;i<n;i++) if (id[i]==key) { printf("%d", i); break; }'],
    dryRows: [['i=2', 'id=105', 'match', 'print 2', 'found']],
  }),
  lab('Sort race scores', 'Sort student 100 m scores for a result sheet.', 'A simple sort (bubble/selection) orders the array.', 'C compiler', 'Print unsorted then sorted.', ['Read n scores', 'Sort', 'Print'], 'Ascending or descending as specified.', 'Ordered result sheet.', 'Swapping indices incorrectly so one score is lost.', 'Is the sort stable at this lab depth? (only if asked)', 'code', {
    code: ['for (int i=0;i<n-1;i++) for (int j=0;j<n-1-i;j++) if (a[j]>a[j+1]) { int t=a[j]; a[j]=a[j+1]; a[j+1]=t; }'],
    dryRows: [['pass 1', 'adjacent swap', 'largest toward end', '', 'sorted']],
  }),
  lab('Warehouse 2D shipments', 'Use a 2D array for products × branches.', 'a[i][j] is product i from branch j. Nested loops sum.', 'C compiler', 'Small matrix; print totals.', ['Read matrix', 'Row/column sums', 'Print'], 'Totals match a hand check.', 'Correct 2D totals.', 'Mixing row-major loops so an index is swapped.', 'What does a[1][0] mean in your legend?', 'code', {
    code: ['for (int i=0;i<r;i++) for (int j=0;j<c;j++) row[i]+=a[i][j];'],
    dryRows: [['i,j', 'add cell', 'row sum grows', '', 'totals']],
  }),
  lab('Join first and last names', 'Concatenate contact names.', 'strcpy/strcat or sprintf into a large enough buffer.', 'C compiler, string.h', 'Two strings in; one full name out.', ['Read first, last', 'Join with space', 'Print'], 'Ada Lovelace style example.', 'Full name displayed.', 'Buffer overflow from strcat into a tiny array.', 'Why +1 for the null?', 'code', {
    code: ['char full[64]; snprintf(full, 64, "%s %s", first, last);'],
    dryRows: [['Ada', 'Lovelace', 'join', 'Ada Lovelace', 'ok']],
  }),
  lab('Currency conversion (functions)', 'Convert with a function; show before confirm.', 'A function takes amount and rate and returns converted value. Main confirms.', 'C compiler', 'Print original, rate, converted.', ['Write convert()', 'Call', 'Print confirmation line'], '100 * 0.012 style example as given in class.', 'Converted amount.', 'Integer rate wiping paise.', 'Why confirm before “doing” the exchange?', 'code', {
    code: ['double convert(double amt, double rate){ return amt * rate; }'],
    dryRows: [['100, 83', '8300', 'print confirm', '', 'ok']],
  }),
  lab('Book structure', 'Store title, author, year in a struct and display.', 'A struct groups fields. An array of struct is a shelf.', 'C compiler', 'Read one or more books; print a table.', ['Define struct', 'Read fields', 'Print'], 'Title/author/year line.', 'Structured display.', 'Printing uninitialized fields.', 'Why not three parallel arrays only?', 'code', {
    code: ['struct Book { char title[40]; char author[40]; int year; };'],
    dryRows: [['assign', 'year=1932', 'print', 'fields shown', 'ok']],
  }),
]
