function stage(title, why, activities, deliverable, roles, pitfall, next, extra = {}) {
  return { title, domain: 'project', visual: 'project', why, activities, deliverable, roles, pitfall, next, ...extra }
}

export const idtStages = [
  stage('Orientation: innovation vs invention and the five DT stages', 'Teams must share a vocabulary before field work.', ['Meet the lab', 'Innovation vs invention discussion', 'Walk Empathize–Define–Ideate–Prototype–Test', 'Warm-up activities'], 'Shared notes on the five stages', 'Multidisciplinary groups of 4–6; one faculty per division (~60)', 'Treating invention and innovation as synonyms', 'Form teams and schedule the field visit'),
  stage('Team formation and interdisciplinary mix', 'A single-branch clique cannot see a civic problem whole.', ['Ice-break', 'Mix branches', 'Name a working agreement', 'Assign a notebook keeper'], 'Team list with branches', 'Min 4 max 6, mixed branches', 'Friends-only teams from one section', 'Plan the public-place visit'),
  stage('Empathy and field exploration', 'The user is not in the classroom.', ['Visit a public place / office / village / NGO as permitted', 'Stakeholder interviews', 'Handwrite the activity book', 'Capture quotes, not slogans'], 'Interview notes in the university activity book', 'Interviewer, note-taker, observer', 'Taking selfies instead of interviews', 'Cluster the notes'),
  stage('Problem definition with How Might We', 'A fuzzy complaint is not a challenge statement.', ['Categorise notes', 'Affinity clustering', 'Problem tree', 'Write HMW statements'], 'One clear challenge statement', 'Facilitator keeps the cluster honest', 'Jumping to a gadget before HMW', 'Prepare the defined-problem presentation'),
  stage('Ideation sprint and filtering', 'Many ideas, then one feasible, eco-aware choice.', ['Present defined problems', 'Brainstorm and mind-map', 'Filter creative / eco / feasible', 'Pick one idea and sketch the prototype'], 'Shortlist + chosen idea sketch', 'Time-keeper for silent brainstorm', 'Voting by loudness instead of filters', 'Enter the makerspace plan'),
  stage('Low-fidelity prototype in Atal / makerspace', 'A prototype is a question you can test, not a product launch.', ['Use Arduino, 3D print, kits, recycled material as available', 'Build low-fi', 'Keep a change log'], 'Working or low-fi model', 'Builder, documenter, safety', 'Decorating instead of testing a function', 'User test'),
  stage('User test, iteration and draft venture plan', 'Feedback is data.', ['Test with a user', 'Observation notes and feedback forms', 'Iterate', 'Draft impact/scalability notes if possible'], 'Feedback log + iterated model + draft plan', 'Tester does not defend the prototype during the interview', 'Ignoring negative feedback', 'Prepare the pitch'),
  stage('Final demo, poster and social pitch', 'The jury should see problem, user, prototype, impact.', ['Poster', 'Live demo', 'Pitch to jury', 'Sustainability / next step'], 'Pitch + prototype + assessment pack as specified', 'Speaker, demo operator, Q&A', 'Showing only a slide deck with no artefact', 'Record what you would test next'),
]

export const projectStages = [
  stage('Orientation, teams and literature survey', 'Interdisciplinary project work starts with a theme and prior work, not a random gadget.', ['PBL introduction', 'Case studies', 'Team of 4–6', 'Brainstorm 5W1H / SCAMPER', 'Mentor approval of problem', 'Search journals/patents/cases'], 'Team list + theme + literature survey report', 'All branches represented if the division allows', 'Skipping literature and copying a YouTube robot', 'Write a problem statement'),
  stage('Problem statement and multiple solution ideas', 'Objectives and constraints make the problem examinable.', ['Refine problem', 'Objectives and outcomes', 'Many solution sketches', 'Feasibility: technical, economic, social', 'Assign roles: design, research, code, docs, test'], 'Finalised problem + list of concepts', 'Named roles', 'One idea only, no alternatives', 'Decision matrix'),
  stage('Select the best idea and plan the prototype', 'A decision matrix is the selection method, not friendship.', ['Score ideas', 'Rough sketches / block diagrams / flowcharts', 'Resource list', 'WBS and timeline', 'Safety and ethics'], 'Design document + prototype development plan', 'Planner owns the timeline', 'Choosing the flashiest idea that cannot be built in the weeks left', 'Start subsystems'),
  stage('Subsystem development', 'Classroom knowledge (circuits, code, mechanics, CAD) enters here.', ['Build modules', 'Peer and mentor review', 'Safety check'], 'Subsystem demos (partial models)', 'Each role delivers a module', 'Waiting until the last week to integrate', 'Integration'),
  stage('Integration in the makerspace', 'The project becomes one system.', ['Join subsystems', 'Debug', 'Improve from tests'], 'Integrated prototype', 'Integrator + tester', 'Forcing a demo that was never tested as a whole', 'Test against objectives'),
  stage('Testing against objectives and users', 'Tables and graphs are the evidence.', ['Test vs objectives', 'User requirements', 'Record failures', 'Limitations'], 'Test results + limitations', 'Someone records numbers, not vibes', 'Changing the objective after a failed test to “pass”', 'Refine'),
  stage('Refinement and pre-final review', 'Efficiency, cost, sustainability — then visuals.', ['Refine prototype', 'Internal review', 'Posters, PPT, demo video'], 'Final experimental/test results + working model', 'Editor of the poster is not the only engineer', 'A pretty poster of an untested box', 'Jury pitch'),
  stage('Final demo and social pitch', 'Impact, prototype, assessment, sustainability plan.', ['Pitch to jury', 'Demo', 'Answer limits honestly'], 'Presentation pack as in the syllabus', 'Speaker + demo + evidence folder', 'Hiding limitations', 'Stop. Do not add invented extra deliverables.'),
]
