/** Lab program catalog — source of truth for selector, switcher and routing. */

export const LAB_PROGRAMS = [
  {
    id: 'lab-p1',
    number: '1',
    title: 'HDFS File Management',
    shortTitle: 'HDFS',
    tech: 'HDFS',
    techNote: 'Hadoop Distributed File System',
    objective: 'Add files and directories, retrieve them, and explore the HDFS namespace.',
    difficulty: 'BEGINNER',
    time: '10–15 MIN',
    tone: 'hdfs',
    accent: '#0f766e',
  },
  {
    id: 'lab-p2',
    number: '2',
    title: 'Matrix Multiplication using MapReduce',
    shortTitle: 'Matrix Multiply',
    tech: 'Hadoop MapReduce',
    techNote: 'Mapper + Reducer',
    objective: 'See how two matrices are distributed, multiplied and accumulated into the result.',
    difficulty: 'INTERMEDIATE',
    time: '15–20 MIN',
    tone: 'mr',
    accent: '#2563eb',
  },
  {
    id: 'lab-p3',
    number: '3',
    title: 'Weather Data Analysis using MapReduce',
    shortTitle: 'Weather',
    tech: 'Hadoop MapReduce',
    techNote: 'Fixed-width parse',
    objective: 'Parse weather records and label hot and cold days from max and min temperature.',
    difficulty: 'INTERMEDIATE',
    time: '12–18 MIN',
    tone: 'weather',
    accent: '#d97706',
  },
  {
    id: 'lab-p4',
    number: '4',
    title: 'MovieLens Movie Tags using MapReduce',
    shortTitle: 'Movie Tags',
    tech: 'MapReduce • MultipleInputs',
    techNote: 'Reduce-side join',
    objective: 'Join movie titles with tags on movieId and emit each movie with its tag list.',
    difficulty: 'ADVANCED',
    time: '15–20 MIN',
    tone: 'movie',
    accent: '#7c3aed',
  },
  {
    id: 'lab-p6',
    number: '6',
    title: 'Pig Latin Data Operations',
    shortTitle: 'Pig Latin',
    tech: 'Apache Pig',
    techNote: 'LOAD · FILTER · ORDER · FOREACH · GROUP · AVG · STORE',
    objective: 'Transform a student relation with LOAD, FILTER, ORDER, FOREACH, GROUP, AVG and STORE.',
    difficulty: 'INTERMEDIATE',
    time: '12–18 MIN',
    tone: 'pig',
    accent: '#c2410c',
  },
  {
    id: 'lab-p7',
    number: '7',
    title: 'Hive Database Operations',
    shortTitle: 'Hive',
    tech: 'Apache Hive',
    techNote: 'HiveQL on HDFS',
    objective: 'Create a database and table, load emp.txt from HDFS, and query employee rows.',
    difficulty: 'BEGINNER',
    time: '10–15 MIN',
    tone: 'hive',
    accent: '#ca8a04',
  },
  {
    id: 'lab-p8',
    number: '8',
    title: 'Word Count using Spark',
    shortTitle: 'Spark Word Count',
    tech: 'Apache Spark • PySpark',
    techNote: 'textFile → collect',
    objective: 'Follow words through textFile, flatMap, map, reduceByKey and collect.',
    difficulty: 'INTERMEDIATE',
    time: '12–18 MIN',
    tone: 'spark',
    accent: '#e11d48',
  },
]

export function getLabProgram(id) {
  return LAB_PROGRAMS.find((item) => item.id === id) || null
}
