export function overlay(base, title, topics, phenomenon, principle, misconception, application, extra = {}) {
  return { base, title, topics, phenomenon, principle, misconception, application, ...extra }
}

export const scienceSubjectModules = {
  '1BCHEC102/202': [
    'electrochemGreen',
    'structuralPolymers',
    overlay('cementWaterCorrosion', 'Conventional and Sustainable Construction Materials',
      ['Cement composition', 'Manufacturing of cement', 'Setting and hardening', 'Sustainable substitutes', 'Durability in service'],
      'Cement paste hydrates into a binding matrix whose composition decides strength and environmental load.',
      'Clinker chemistry plus water reaction, not the bag label, makes the structural material.',
      'OPC, PPC and blended cements are not interchangeable without checking the exposure class.',
      'Choose cement and aggregate for the structure’s moisture, sulphate and carbonation environment.'),
    overlay('cementWaterCorrosion', 'Corrosion Science and Surface Protection',
      ['Ferrous vs non-ferrous metals', 'Electrochemical corrosion cell', 'Uniform and localized attack', 'Coatings and inhibitors', 'Cathodic protection'],
      'A metal surface becomes many anodes and cathodes when oxygen, water and ions complete a cell.',
      'Protection works only if it breaks anodic dissolution, cathodic reduction or the ionic path.',
      'Paint that hides rust without isolating electrolyte is cosmetic, not protection.',
      'Specify coating plus drainage/detailing so the cell cannot stay wet.'),
    overlay('cementWaterCorrosion', 'Water Chemistry and Analytical Techniques',
      ['pH, turbidity, hardness', 'Alkalinity and dissolved solids', 'Softening and disinfection', 'Boiler/cooling water risk', 'Simple analytical tests'],
      'Dissolved ions decide scale, corrosion and treatment cost long before a pipe fails.',
      'Hardness as CaCO3 equivalent is a comparable engineering number, not a taste score.',
      'Softening does not remove every contaminant; name the ion you actually treated.',
      'Treat water to the process limit: drinking, boiler or concrete mixing are different specs.'),
  ],
  '1BCHEE102/202': [
    overlay('electronicsMaterials', 'Materials for Energy Devices',
      ['n-type and p-type semiconductors', 'Organic vs inorganic semiconductors', 'Carrier type and device role', 'Energy-device stacks', 'Why doping is design'],
      'A p–n junction works because majority-carrier type is engineered, not because the wafer is “electronic”.',
      'Conductivity σ = n q μ is a materials equation: change n or μ and the device changes.',
      'Calling every semiconductor a silicon chip hides organic and compound options in this module.',
      'Pick the semiconductor family from the energy-conversion function, then dope it.'),
    overlay('electronicsMaterials', 'Nano and Quantum Dot Materials',
      ['Size-dependent properties', 'Surface-area-to-volume', 'Quantum confinement', 'Optical shift with size', 'Why “nano” is not enough'],
      'When particle size approaches the exciton Bohr radius, allowed energies move and colour changes.',
      'Surface-to-volume rise is a geometric fact that also changes catalysis and scattering.',
      'A powder is not a quantum dot unless confinement, not just millimetre-scale grinding, is present.',
      'Use size as a design knob for band gap and surface reaction rate.'),
    overlay('structuralPolymers', 'Functional Polymers and Hybrid Composites in Flexible Electronics',
      ['Stretchable conductors', 'Wearable interconnects', 'Polymer/inorganic hybrids', 'Bending vs cracking', 'Interface adhesion'],
      'A wearable circuit must carry current while the substrate strains without opening the conductor.',
      'Hybrid composites mix a polymer matrix that flexes with a filler that conducts or senses.',
      'A rigid PCB layout printed on fabric is not stretchable electronics.',
      'Design the strain path first, then the conductor geometry.'),
    overlay('electrochemGreen', 'Electrode System and Electrochemical Sensors',
      ['Indicator vs reference electrodes', 'Nernst response of a sensor', 'Selectivity and interference', 'Calibration slope', 'Sensor failure modes'],
      'A potentiometric sensor reports activity of one ion against a stable reference, not a mystery voltage.',
      'E = E0 − (0.0591/n) log Q is the calibration idea of the electrode, not only of a battery.',
      'A drifting reference electrode looks like a sample change.',
      'Calibrate slope and check interferents before trusting a field reading.'),
    overlay('cementWaterCorrosion', 'Corrosion Science and E-waste Management',
      ['Electrochemical corrosion of devices', 'Galvanic couples on PCBs', 'E-waste streams', 'Recovery vs dumping', 'Design for disassembly'],
      'A wet, mixed-metal gadget is a galvanic museum; corrosion and leaching start the e-waste harm.',
      'E-waste management begins with material identity: copper, solder, plastics, batteries.',
      'Recycling a phone is not the same as throwing it in municipal wet waste.',
      'Specify take-back and material recovery as part of the device life cycle.'),
  ],
  '1BCHEM102/202': [
    overlay('cementWaterCorrosion', 'Corrosion Science and Coating Technologies',
      ['Electrochemical theory of corrosion', 'Types of corrosion', 'Metallic and organic coatings', 'Inhibitors', 'Inspection of coated steel'],
      'A coating is a barrier or a sacrificial anode; it is not a colour layer.',
      'If electrolyte reaches the steel, the cell restarts under the film.',
      'A shiny coat over mill scale without blast-cleaning fails at the mill-scale interface.',
      'Match coating system to C-class environment and maintenance interval.'),
    'sustainableFuels',
    overlay('electronicsMaterials', 'Materials for Energy Systems',
      ['TiO2 nanoparticles by sol-gel', 'Photo/catalytic surfaces', 'Energy-storage electrodes', 'Why synthesis route matters', 'Scale-up caution'],
      'Sol-gel TiO2 is a controlled wet-chemical route to a high-surface oxide used in energy and photocatalytic stacks.',
      'Particle size and calcination temperature change the active phase, not only the recipe name.',
      'Sol-gel in a beaker is not automatically a battery cathode.',
      'Report synthesis conditions with the application claim.'),
    overlay('structuralPolymers', 'Materials for Engineering Applications',
      ['Number-average and weight-average molecular weight', 'PDI', 'Engineering polymer selection', 'Thermal vs mechanical demand', 'Why averages disagree'],
      'Mn and Mw answer different questions; a few long chains pull Mw up.',
      'PDI = Mw/Mn is a distribution width, not a strength grade.',
      'Naming nylon does not fix Mn; the grade does.',
      'Select polymer grade from the average that controls the property you need.'),
    overlay('chemicalEngineering', 'Fluid Technology and Smart Sensors',
      ['Lubricant classification', 'Viscosity and film formation', 'Additives', 'Condition monitoring sensors', 'Failure when film collapses'],
      'A lubricant works by keeping a film between surfaces; viscosity and additives set that film.',
      'Smart sensors on a machine watch temperature, vibration or oil quality because film failure is sudden.',
      'Thicker oil is not always better; start-up drag and heat matter.',
      'Choose lubricant by load, speed and temperature, then monitor it.'),
  ],
  '1BEBT105/205': [
    overlay('biotechnologyBasics', 'Basics of Biology: Cell and Central Dogma',
      ['Prokaryotic vs eukaryotic cells', 'Organelles that matter to engineers', 'DNA → RNA → protein', 'Transcription vs translation', 'Why cell type changes process design'],
      'Information in DNA is transcribed to RNA and translated to protein; that flow is the operating system of the cell.',
      'Prokaryotes lack a nucleus; bioprocess contamination and product location follow from that architecture.',
      'Drawing a nucleus in a bacterium is a category error, not a simplification.',
      'Choose host (E. coli vs mammalian) from where the protein must fold and glycosylate.'),
    overlay('biotechnologyBasics', 'Overview of Biotechnology: History, Scope and Branches',
      ['Red/medical', 'Green/agricultural', 'White/industrial', 'History that changed tools', 'Scope limits of this course'],
      'Biotechnology is named by the problem it solves: health, crop or industrial molecule.',
      'A branch is a use-case plus a toolset, not a separate biology.',
      'Medical biotech is not “all of biology with a hospital”.',
      'Place a case in red/green/white before choosing a method.'),
    overlay('biotechnologyBasics', 'Biotechnology Processes and Sustainability: Bioethanol Case',
      ['Agri-waste substrate', 'Pretreatment', 'Hydrolysis to sugars', 'Fermentation', 'Recovery and residue'],
      'Bioethanol from agri-waste is a sequence: unlock cellulose, make sugars, ferment, separate.',
      'Sustainability is in feedstock and energy of pretreatment, not in the word bio.',
      'Food-crop ethanol and agri-waste ethanol are not the same sustainability claim.',
      'Write the mass-balance story: what enters, what is fuel, what is still waste.'),
    overlay('biotechnologyBasics', 'AI Application in Biological Research',
      ['Genomics pipelines', 'Drug-development loops', 'Where a model is trained', 'Where wet-lab validation sits', 'Failure of unvalidated prediction'],
      'AI in genomics proposes sequence function; the wet lab still confirms it.',
      'A flowchart that ends at a predicted molecule is not a drug.',
      'Training on biased sequence sets quietly repeats the bias in “discovery”.',
      'Use AI to rank experiments, not to skip them.'),
    overlay('biotechnologyBasics', 'Bioinspired Engineering and Biomimetics',
      ['History of biomimicry', 'Nacre and toughness', 'Lotus and wetting', 'Function vs appearance', 'Transfer into a material spec'],
      'Nacre is tough because of brick-and-mortar architecture, not because it looks like a shell.',
      'Biomimetics copies a mechanism: layered ceramic/polymer, hierarchical roughness, not a motif.',
      'A building shaped like a tree is not biomimetic unless load paths copy wood.',
      'Write the biological mechanism, then the engineering analogue, then the test.'),
  ],
  '1BECHE105/205': [
    overlay('chemicalEngineering', 'Introduction to Chemical Engineering and the Engineer’s Role',
      ['Everyday chemical engineering', 'From molecule to plant', 'Safety and society', 'Unit operations idea', 'What a first-year engineer actually does'],
      'Chemical engineering scales a reaction from flask to plant without losing heat, mass or people.',
      'The role is process: invent, measure, control, and take responsibility for hazards.',
      'Chemistry in a beaker is not plant design.',
      'Name the scale-up question: heat, mixing, separation or safety first.'),
    overlay('chemicalEngineering', 'Modern Chemical Engineering Plants: Batch and Continuous',
      ['Batch processing', 'Continuous processing', 'When to switch', 'Hold-up and residence time', 'Quality variation'],
      'Batch is a recipe in a vessel; continuous is a steady flow through equipment.',
      'Residence time replaces “cook for 2 hours” when the plant is continuous.',
      'Running a continuous pipe as if it were a bigger flask ignores start-up and recycle.',
      'Choose batch for specialty/changing recipes; continuous for stable high volume.'),
    overlay('chemicalEngineering', 'Natural Sciences in Chemical Engineering: Gas Law and Rates',
      ['Ideal gas law', 'Infinitesimal change / rates', 'Why P-V-T belongs in a plant', 'When ideal gas fails', 'Link to vessel design'],
      'PV = nRT is the first model of how a gas in a vessel answers to heat and moles.',
      'Rates (dP/dt, dT/dt) are why control loops exist.',
      'Using ideal gas on a near-critical refrigerant is a wrong constitutive choice.',
      'State the model, the assumption, and the safety margin on pressure.'),
    overlay('chemicalEngineering', 'Fluid Flow Phenomena and Dimensional Analysis',
      ['Newtonian vs non-Newtonian', 'Shear stress vs velocity gradient', 'Laminar/turbulent cue', 'Dimensionless groups', 'Scaling a pipe or agitator'],
      'Shear stress related to du/dy is the constitutive start of viscous flow.',
      'Dimensional analysis collapses many variables into Re, Fr, etc., so a lab pipe can inform a plant pipe.',
      'Reynolds number is not a decoration; it decides laminar vs turbulent mixing and pressure drop.',
      'Non-dimensionalise before copying a lab rpm to a tank ten times larger.'),
    overlay('chemicalEngineering', 'Safety in Chemical Process Industries',
      ['Lessons from incidents', 'Layers of protection', 'Management responsibility', 'Inherently safer design', 'Emergency vs prevention'],
      'Safety is a designed layer: eliminate hazard, control it, then plan emergency — in that order.',
      'Management systems fail as surely as vessels if permits and isolation are theatre.',
      'A poster of PPE is not a HAZOP.',
      'Ask what energy is present and how it is isolated before start-up.'),
  ],
  '1BPHEC102/202': [
    'quantumPhysics',
    overlay('electricalMaterials', 'Electrical Properties of Metals and Semiconductors',
      ['Failure of classical free-electron theory', 'Scattering mechanisms', 'Drift and mobility', 'Band picture of metals vs semiconductors', 'Temperature trends'],
      'Classical free-electron theory cannot explain heat capacity and the T-dependence of conductivity that semiconductors show.',
      'Mobility falls with scattering; carrier density in a semiconductor rises with T — opposite stories.',
      'Treating a semiconductor as a worse metal misses the gap.',
      'Use band gap plus scattering, not “electrons as billiard balls”, to read a resistivity curve.'),
    overlay('electricalMaterials', 'Superconductivity',
      ['Zero resistance', 'Persistent current', 'Meissner effect', 'Tc, Ic, Hc', 'Why Meissner is not just R=0'],
      'A superconductor expels magnetic flux (Meissner) and carries current with R=0 below Tc.',
      'Critical current and field destroy the state; it is a phase, not a better copper.',
      'A shorted coil of copper is not a persistent current.',
      'Quote Tc and the field when you claim a superconducting application.'),
    overlay('quantumApplications', 'Photonics: Einstein A and B Coefficients',
      ['Absorption, spontaneous and stimulated emission', 'A and B coefficients', 'Population inversion', 'Laser threshold idea', 'Why inversion is non-equilibrium'],
      'Stimulated emission copies a photon; lasers need inversion so that process wins.',
      'Einstein A (spontaneous) and B (stimulated/absorption) connect thermal equilibrium to optical gain.',
      'A bright LED is not automatically a laser.',
      'Name the three processes before drawing a cavity.'),
    overlay('electronicsMaterials', 'Semiconductor Devices and Sensors',
      ['Direct vs indirect gap', 'Zener diode', 'LED', 'Photodiode', 'Why gap type decides light'],
      'Direct-gap materials emit light efficiently; photodiodes absorb it; Zener uses a controlled breakdown.',
      'Band-gap engineering sets the photon energy of an LED.',
      'A silicon photodiode is not a silicon LED of the same efficiency.',
      'Match gap (direct/indirect) to emit vs detect.'),
  ],
  '1BPHEE102/102': [
    overlay('electricalMaterials', 'Dielectric and Magnetic Materials',
      ['Polarization mechanisms', 'Internal field', 'Dielectric constant and loss', 'Magnetic ordering', 'Why a capacitor dielectric is chosen'],
      'Polarization is bound-charge displacement; five mechanisms turn on at different frequencies.',
      'Dielectric loss is energy per cycle, not a moral failing of the insulator.',
      'High εr with huge loss is a heater, not a capacitor.',
      'Specify frequency when you quote dielectric constant.'),
    overlay('electricalMaterials', 'Thermoelectric Materials and Devices',
      ['Seebeck emf', 'Peltier heat', 'Thermo current', 'Figure of merit idea', 'Why a thermocouple is not a Peltier cooler'],
      'A temperature difference produces emf (Seebeck); a current pumps heat (Peltier).',
      'They are inverse thermoelectric effects, not two names for one meter.',
      'A thermocouple junction is a sensor; a Peltier module is a heat pump.',
      'State which effect you are using before wiring the module.'),
    overlay('electricalMaterials', 'Electrical Properties of Metals and Semiconductors',
      ['Classical free-electron failures', 'Electron scattering', 'Fermi-level picture', 'n and p semiconductors', 'Resistivity vs T'],
      'Metals and semiconductors disagree on how resistivity changes with temperature because n(T) differs.',
      'Scattering plus carrier freeze-out/generation beat the classical kinetic-gas model.',
      'Drawing metal and semiconductor resistivity with the same slope is wrong physics.',
      'Read the ρ–T curve before naming the material class.'),
    overlay('electricalMaterials', 'Superconductivity',
      ['Zero resistance', 'Persistent current', 'Meissner effect', 'Critical parameters', 'Magnets and lossless lines as applications'],
      'Meissner expulsion plus R=0 define the superconducting state under limits Tc, Hc, Ic.',
      'Persistent current is a test of R=0 that a copper loop fails in minutes.',
      'Cooling copper to 4 K does not make it a superconductor.',
      'Stay inside the critical surface or the magnet quenches.'),
    overlay('electricalMaterials', 'Electrical Engineering Materials: Rare Earths and Phase Diagrams',
      ['Rare-earth roles in magnets and phosphors', 'Energy-system materials', 'Electrical/magnetic phase diagrams', 'Why composition is a design variable', 'Substitution and supply constraints'],
      'Rare-earth magnets and phosphors work because 4f states set magnetic moment and optical lines.',
      'A phase diagram tells which structure exists at a composition and temperature.',
      '“Rare earth” is not a single material.',
      'Read the phase field before claiming a magnet grade.'),
  ],
  '1BPHYC102/202': [
    overlay('sustainableStructuresPhysics', 'Oscillations and SHM for Structures',
      ['SHM differential equation', 'Stiffness k and mass m', 'Natural frequency', 'Resonance risk', 'Why a spring model is a first building model'],
      'A restoring force proportional to displacement gives SHM: ẍ + ω²x = 0 with ω = √(k/m).',
      'A building’s first model is a mass on a lateral stiffness, not a static sketch.',
      'Higher k always “safer” ignores that it also moves the natural frequency toward a wind/earthquake peak.',
      'Compute ω before you add a damper or change mass.'),
    overlay('sustainableStructuresPhysics', 'Waves and Their Role in Structural Behaviour',
      ['Wave types', 'Propagation in beams, rods, slabs', 'Boundary reflection', 'Dispersion idea', 'Damage as a change of path'],
      'A wave in a beam is a travelling disturbance; boundaries reflect and mode-shape the member.',
      'v = fλ still organises the numbers once you know which wave (flexural vs axial).',
      'A slab does not “vibrate in general”; name the wave and the boundary.',
      'Use wave speed and length to guess natural periods of members.'),
    overlay('sustainableStructuresPhysics', 'Acoustics, Radiometry and Photometry',
      ['Reverberation', 'Types of acoustics', 'Sound absorption', 'Radiometric vs photometric quantities', 'Why lighting and noise are measurable'],
      'Reverberation time is a room energy-decay time, not a taste in music.',
      'Photometry weights light by the eye; radiometry does not — they are different unit systems.',
      'Lux is not watts per square metre.',
      'Specify RT60 or illuminance with the human/task criterion.'),
    overlay('sustainableStructuresPhysics', 'Non-Destructive Testing',
      ['Need for inspection', 'Ultrasonic, rebound, cover-meter families', 'Input–interaction–received signal', 'Benefits vs sampling cores', 'What NDT cannot claim'],
      'NDT sends energy in and reads the altered return so the member can stay in service.',
      'A method is defined by the physics of the interaction, not by the brand of the gun.',
      'NDT that “proves strength” without a calibration to cores overclaims.',
      'Pair NDT mapping with a few destructive calibrations.'),
    overlay('sustainableStructuresPhysics', 'Smart Materials for Sustainable Structures',
      ['Piezoelectric', 'Magnetostrictive', 'Electrostrictive', 'Shape-memory', 'Sensing vs actuating'],
      'A piezo crystal couples stress to voltage so a structure can sense or poke itself.',
      'Smart is a coupling, not a marketing adjective.',
      'A piezo buzzer is not a magnetostrictive damper.',
      'Name the coupling (stress–voltage, field–strain) before placing the patch.'),
  ],
  '1BPHYM102/202': [
    overlay('sustainableStructuresPhysics', 'Oscillations: SHM and Spring Stiffness',
      ['SHM equation', 'Stiffness factor', 'Energy in the oscillator', 'Damping as a next correction', 'Link to machine mounts'],
      'Stiffness k is force per displacement; with mass it sets ω.',
      'The same SHM law describes a machine on mounts and a lab mass-spring.',
      'Ignoring damping is a first model, not the finished machine.',
      'Measure k from slope of F–x before quoting a natural frequency.'),
    overlay('physicsMaterials', 'Elasticity: Stress–Strain and Moduli',
      ['Stress–strain curve', 'Strain hardening/softening', 'E, G, ν relations', 'Elastic vs plastic design', 'Why slope changes after yield'],
      'E is the elastic slope; after yield the curve is a different material story.',
      'Poisson ratio couples axial and lateral strain in the elastic range.',
      'Using E in the plastic region to size a part is a unit-and-model error.',
      'Read yield, UTS and fracture as separate points on the same graph.'),
    overlay('electricalMaterials', 'Thermoelectric Materials and Devices',
      ['Seebeck', 'Peltier', 'Thermo current', 'Device as heat engine/heat pump', 'Contact and gradient errors'],
      'A thermocouple measures ΔT via Seebeck; a Peltier module moves heat via current.',
      'Figure of merit combines electrical conductivity, thermopower and thermal conductivity.',
      'A hot wire is not a Seebeck measurement without a reference junction.',
      'Control both junctions when you claim a temperature.'),
    overlay('physicsMaterials', 'Cryogenics and Low-Temperature Methods',
      ['Carnot limit', 'Joule–Thomson expansion', 'Why inversion temperature matters', 'Liquefaction idea', 'Materials that change at low T'],
      'Joule–Thomson cooling works only in a temperature window set by the inversion curve.',
      'Carnot efficiency is the ceiling for a heat engine between two reservoirs.',
      'Opening a compressed-air valve always “makes cold” is false above inversion.',
      'State the gas and the inversion temperature before claiming liquefaction.'),
    overlay('physicsMaterials', 'Material Characterization and Instrumentation',
      ['Wave–particle dualism in probes', 'Schrödinger idea at instrument scale', 'What XRD/SEM/spectroscopy each see', 'Sample prep as part of the measurement', 'Resolution vs damage'],
      'An instrument is an interaction: electrons, X-rays or photons in, a structured signal out.',
      'Schrödinger/wave models justify why a microscope has a resolution limit.',
      'A pretty SEM image is not a composition analysis.',
      'Name the probe and the signal before claiming a property.'),
  ],
  '1BPHYS102/202': [
    overlay('quantumApplications', 'Quantum Mechanics: de Broglie and Uncertainty',
      ['Matter waves', 'Heisenberg pair', 'Spectral-line broadening as application', 'Why classical orbits fail', 'Estimate λ = h/p'],
      'A particle with momentum p has a wave λ = h/p; localising it costs Δp.',
      'Line broadening can be an uncertainty-budget story, not only Doppler.',
      'An electron planet model is not this module’s ontology.',
      'Compute λ before arguing that a ball “is a wave” in daily life.'),
    overlay('electricalMaterials', 'Electrical Properties of Metals and Semiconductors',
      ['Free-electron failures', 'Scattering', 'Gap and thermal generation', 'Mobility', 'Device implication'],
      'Semiconductors conduct by generating carriers across a gap; metals already have a sea of them.',
      'Resistivity vs T is the classroom discriminator.',
      'Calling both “conductors” erases the exam question.',
      'Sketch n(T) and μ(T) separately.'),
    overlay('electricalMaterials', 'Superconductivity',
      ['R = 0', 'Meissner', 'Critical surface', 'Persistent current', 'Application constraint'],
      'The superconducting state is bounded by T, B and J; leaving the surface quenches it.',
      'Flux expulsion is independent evidence from zero resistance.',
      'A cooled resistor with a dead voltmeter is not Meissner.',
      'Stay inside Hc and Ic in any magnet example.'),
    overlay('quantumApplications', 'Photonics: Einstein Coefficients and Lasers',
      ['A and B', 'Stimulated emission', 'Inversion', 'Cavity as feedback', 'LED vs laser'],
      'Lasers require inversion so stimulated emission dominates absorption.',
      'Derivation of energy density from A and B is the thermal-equilibrium anchor.',
      'Population inversion is not “more voltage”.',
      'Draw the three Einstein processes on the two-level sketch.'),
    overlay('quantumApplications', 'Quantum Computing: Qubit versus Bit',
      ['Moore/VLSI limit', 'Bit vs qubit', 'Superposition α|0⟩+β|1⟩', 'Measurement collapses the lecture-model', 'Why this is not a faster laptop'],
      'A qubit is a two-level quantum state, not a bit that is 0 and 1 in two drawers.',
      'VLSI scaling hits physics; the course only introduces why a new information carrier is discussed.',
      'Superposition is not parallel classical RAM.',
      'Normalise |α|²+|β|²=1 before claiming a computation.'),
  ],
  '1BSSA105/205': [
    overlay('soilAgronomy', 'Fundamentals of Agronomy',
      ['Agriculture branches', 'Scope of agronomy', 'National food context', 'Crop vs soil roles', 'Why agronomy is not gardening folklore'],
      'Agronomy is the field science of crop production in a soil–climate system.',
      'National yield questions are agronomic: variety, calendar, water, nutrient — together.',
      'Agronomy is not “soil science with plants mentioned”.',
      'State the production constraint (water, nutrient, weed) before the practice.'),
    overlay('soilAgronomy', 'Agronomic Practices: Tillage and Sowing',
      ['Objectives of tillage', 'Seed-bed characteristics', 'Types of tillage', 'Sowing methods', 'What tillage destroys as well as creates'],
      'Tillage is a physical rearrangement of soil to a seed-bed; it also oxidises carbon and can smash structure.',
      'A good seed-bed is tilth plus moisture plus absence of a plough pan — measurable, not poetic.',
      'More tillage is not more agronomy.',
      'Match implement and depth to the objective (weed, residue, seed-soil contact).'),
    overlay('soilAgronomy', 'Fundamentals of Soil Science: Rocks to Soil',
      ['Definition of soil', 'Branches of soil science', 'Igneous, sedimentary, metamorphic rocks', 'Weathering path', 'Why parent rock is not the soil'],
      'Soil is a living, three-phase system produced by weathering plus time, not crushed rock in a bag.',
      'Parent material sets mineral inheritance; climate and organisms rewrite it.',
      'A granite boulder is not a soil profile.',
      'Name the rock class before predicting clay mineralogy.'),
    overlay('soilAgronomy', 'Physical Properties of Soil and Their Management',
      ['Soil profile horizons', 'Structure types', 'Bulk density and porosity', 'Texture vs structure', 'Management that protects aggregates'],
      'Structure is how sand, silt and clay are arranged; texture is the size mix.',
      'Profile horizons are a history book; compaction writes a new, harmful chapter.',
      'Adding sand to clay “to lighten it” without organic matter often makes concrete.',
      'Manage traffic and residue to keep pore continuity.'),
    overlay('soilAgronomy', 'Chemical Properties of Soil and Plant Nutrition',
      ['Cation and anion exchange', 'Factors of CEC', 'pH and nutrient availability', 'Essential elements', 'Why exchange sites feed the plant'],
      'CEC is the soil’s rechargeable ion bank; plants withdraw against that bank.',
      'pH changes which ions sit on the exchange and which precipitate.',
      'A high fertiliser bag grade does not override a locked pH.',
      'Test pH and CEC idea before prescribing a nutrient.'),
  ],
}
